"""Opt-in actual skill-source and public/private verified-TLS registry UI proof.

Uses an isolated host, managed Chromium and a host-composed test CA/resolver.
Production requests cannot supply these transport hooks. No paid queries,
external sites, OS credential writes or automatic trust occur.
"""
from __future__ import annotations
import asyncio,json,os,socket,sys,tempfile,threading
from pathlib import Path
from time import monotonic,sleep
import uvicorn
from playwright.sync_api import sync_playwright,expect
from test_https_registries import tls,publish,bundle
from test_skill_sources import TEXT
from termx.agent.secrets import CredentialStore

def run(destination):
    destination=Path(destination);destination.mkdir(parents=True,exist_ok=True)
    report={'proof':'actual-managed-skill-sources-and-verified-TLS-registries','paid_queries':0,'OS_credential_writes':0,'errors':[],'states':[],'steps':[]}
    with tempfile.TemporaryDirectory(prefix='termx-extension-ui-') as temporary:
        root=Path(temporary);os.environ.update(TERMX_CONFIG_DIR=str(root/'config'),TERMX_AGENTS_DIR=str(root/'agents'),TERMX_ENGINE_STARTUP_REFRESH='0')
        project_root=root/'project';project_root.mkdir();global_skill=root/'agents/skills/inspect';global_skill.mkdir(parents=True);(global_skill/'SKILL.md').write_text(TEXT+' Global')
        legacy=project_root/'.claude/skills/LegacySkill';legacy.mkdir(parents=True);compat_text=TEXT.replace('Useful skill','Compatibility skill')+' Compatibility';(legacy/'SKILL.md').write_text(compat_text)
        fixture=tls.__wrapped__(root);url,transport,responses,requests=next(fixture);publish(responses,bundle('registry-skill'))
        from termx.app import AppState,create_app
        from test_agent import FakeAdapter
        from workspace_ui_snapshot import snapshot_ui
        adapter=FakeAdapter();state=AppState(passcode=None,credentials=CredentialStore(memory={}),adapter_factory=lambda *_:adapter)
        owner=state.identity.setup_owner('extension-owner','extension-proof-password-123');project=state.projects.register(str(project_root),name='Extension proof')
        app=create_app(state,web_dir=snapshot_ui(root,Path(os.environ.get('TERMX_UI_PROOF_DIST',str(Path(__file__).resolve().parents[1]/'desktop/workspace/dist')))))
        state.extensions.transport=transport;state.skill_sources.compatibility_home=root/'compat-home'
        state.workspace.save_memory(owner,content='Manager header geometry fixture',provenance='Isolated rendered proof',project_id=project['id']);report['UI_asset_snapshot']=json.loads((root/'fixture-ui-snapshot.json').read_text());session=state.workspace.create_session(owner,title='Extension manager proof',project_id=project['id'],cwd=str(project_root),mode='ask')
        listener=socket.socket();listener.bind(('127.0.0.1',0));listener.listen();port=listener.getsockname()[1]
        server=uvicorn.Server(uvicorn.Config(app,log_level='error',lifespan='on'));worker=threading.Thread(target=lambda:asyncio.run(server.serve(sockets=[listener])),daemon=True);worker.start();deadline=monotonic()+25
        while not server.started:
            if monotonic()>deadline:raise RuntimeError('Extension fixture did not start')
            sleep(.05)
        try:
            with sync_playwright() as playwright:
                browser=playwright.chromium.launch(headless=True);context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce');page=context.new_page();page.on('pageerror',lambda error:report['errors'].append(str(error)))
                page.goto(f'http://127.0.0.1:{port}/?session={session["id"]}');page.get_by_label('Username',exact=True).fill('extension-owner');page.get_by_label('Password',exact=True).fill('extension-proof-password-123');page.get_by_role('button',name='Continue with password').click();page.get_by_label('Message',exact=True).wait_for(timeout=60000);page.wait_for_function('document.querySelector(".breadcrumb strong")?.textContent==="Extension manager proof"',timeout=60000)
                page.get_by_role('button',name='Managers',exact=True).click();page.get_by_role('button',name='Plugins & skills',exact=True).click();page.get_by_role('heading',name='Plugins & skills',exact=True,level=1).wait_for();page.get_by_text('Useful skill',exact=True).wait_for();assert page.get_by_label('Skill scope',exact=True).input_value()=='project';page.on('response',lambda response:report.setdefault('source_HTTP',[]).append({'status':response.status,'path':response.url.split('/api/workspace/')[-1]}) if '/api/workspace/skill-sources/' in response.url else None)
                page.get_by_label('Skill folder name',exact=True).fill('inspect');page.get_by_label('Skill instructions',exact=True).fill(TEXT);page.get_by_role('button',name='Validate skill',exact=True).click();page.get_by_text('Skill metadata and instructions validated',exact=True).wait_for();page.get_by_role('button',name='Save source',exact=True).click();page.get_by_text('Skill source saved',exact=True).wait_for();assert (project_root/'.agents/skills/inspect/SKILL.md').read_text()==TEXT
                page.get_by_text('Overridden by project',exact=False).wait_for();report['steps'].append('Actual project SKILL.md saved; global source remains intact and effective override is inspectable')
                source_path=project_root/'.agents/skills/inspect/SKILL.md';source_path.write_text(TEXT+' External')
                page.get_by_label('Skill instructions',exact=True).fill(TEXT+' My draft');page.get_by_role('button',name='Save source',exact=True).click();page.get_by_role('heading',name='Source changed on disk').wait_for();assert page.get_by_label('Skill instructions').input_value()==TEXT+' My draft';assert source_path.read_text()==TEXT+' External';page.get_by_role('button',name='Use current revision with my draft').click();page.get_by_role('button',name='Save source',exact=True).click();page.get_by_text('Skill source saved',exact=True).wait_for();assert source_path.read_text()==TEXT+' My draft';report['steps'].append('External file edit triggers conflict; draft survives and explicit current revision permits save')
                page.get_by_text('Immutable version history',exact=True).click();page.get_by_role('button',name='Restore as draft').first.click();assert page.get_by_role('button',name='Review skill publication').is_disabled();assert source_path.read_text()==TEXT+' My draft';page.get_by_role('button',name='Save source',exact=True).click();page.get_by_text('Skill source saved',exact=True).wait_for()
                with page.expect_download() as exported:page.get_by_role('button',name='Export source').click()
                assert Path(exported.value.path()).read_text()==source_path.read_text()
                page.get_by_role('button',name='Review skill publication').click();page.get_by_role('heading',name='Review inspect · 1').wait_for();assert state.workspace.store.get('extension','inspect') is None;page.get_by_role('button',name='Install reviewed version').click();page.get_by_text('Reviewed immutable version installed',exact=True).wait_for();assert state.extensions.export(owner,'inspect')['files']['skills/inspect/SKILL.md']==source_path.read_text();report['steps'].append('Version history restores a draft; reviewed publication activates exact immutable instructions')
                page.get_by_text('Compatibility discovery · read-only',exact=True).click();page.get_by_role('button',name='Import as draft',exact=True).click();page.get_by_text('Compatibility source imported as a draft',exact=True).wait_for();assert page.get_by_label('Skill folder name',exact=True).input_value()=='LegacySkill';assert page.get_by_label('Skill instructions',exact=True).input_value()==compat_text;assert page.get_by_role('button',name='Review skill publication').is_disabled();assert not (project_root/'.agents/skills/LegacySkill/SKILL.md').exists();page.get_by_role('button',name='Save source',exact=True).click();page.get_by_text('Skill source saved',exact=True).wait_for();assert (project_root/'.agents/skills/LegacySkill/SKILL.md').read_text()==compat_text;assert (legacy/'SKILL.md').read_text()==compat_text;assert state.workspace.store.get('extension','legacyskill') is None
                page.get_by_label('Skill folder name',exact=True).fill('file-import');expect(page.get_by_role('button',name='Save source',exact=True)).to_be_enabled();page.get_by_label('Import SKILL.md',exact=True).set_input_files({'name':'SKILL.md','mimeType':'text/markdown','buffer':(TEXT+' Uploaded draft').encode()});page.get_by_text('Imported draft',exact=True).wait_for();assert page.get_by_role('button',name='Review skill publication').is_disabled();assert not (project_root/'.agents/skills/file-import/SKILL.md').exists();page.get_by_role('button',name='Validate skill',exact=True).click();page.get_by_text('Skill metadata and instructions validated',exact=True).wait_for();page.get_by_role('button',name='Save source',exact=True).click();page.get_by_text('Skill source saved',exact=True).wait_for();assert (project_root/'.agents/skills/file-import/SKILL.md').read_text()==TEXT+' Uploaded draft';assert state.workspace.store.get('extension','file-import') is None;report['steps'].append('Actual compatibility and file imports remain unsaved drafts until validation/save; original native source untouched and no implicit activation')
                page.get_by_text('Public & private registries',exact=True).click();page.get_by_label('Registry name',exact=True).fill('Private TLS');page.get_by_label('Registry adapter',exact=True).select_option('private_https');page.get_by_label('HTTPS index URL',exact=True).fill(url+'/index');page.get_by_label('Registry credential',exact=True).fill('private-ui-fixture-secret');page.get_by_role('button',name='Add registry',exact=True).click();page.get_by_text('Registry registered',exact=True).wait_for();assert page.get_by_label('Registry credential').input_value()==''
                registry_article=page.locator('article').filter(has=page.get_by_role('heading',name='Private TLS',exact=True));registry_article.get_by_role('button',name='Browse packages').click();page.get_by_role('heading',name='registry-skill · 1',exact=True).wait_for();page.get_by_role('button',name='Review package',exact=True).click();page.get_by_role('heading',name='Review registry-skill · 1').wait_for();page.get_by_text('Exact provenance, digests & files',exact=True).click();exact=page.get_by_role('region',name='Reviewed extension provenance and files');assert 'private-ui-fixture-secret' not in exact.inner_text();assert 'private_https' in exact.inner_text();exact.focus();assert exact.evaluate('(el)=>el===document.activeElement');registry_article.get_by_role('button',name='Rotate credential',exact=True).click();page.get_by_label('New registry credential',exact=True).fill('rotated-ui-fixture-secret');page.get_by_role('button',name='Save registry credential',exact=True).click();page.get_by_text('Credential rotated; previous package reviews invalidated',exact=True).wait_for();assert page.get_by_label('Registry credential',exact=True).input_value()=='';page.get_by_role('button',name='Install reviewed version').click();page.get_by_role('alert').wait_for();assert state.workspace.store.get('extension','registry-skill') is None;page.get_by_role('heading',name='Review registry-skill · 1').wait_for();page.get_by_role('button',name='Review package',exact=True).click();page.get_by_text('Downloaded package ready for review',exact=True).wait_for();page.get_by_role('button',name='Install reviewed version').click();page.get_by_text('Reviewed immutable version installed',exact=True).wait_for();assert state.extensions.export(owner,'registry-skill')==bundle('registry-skill');report['steps'].append('Real private HTTPS catalog/package fetched and reviewed; rotation rejects prior review, refresh installs exact bytes, host secret absent from UI/durable metadata')
                page.get_by_label('Registry adapter',exact=True).select_option('public_https');page.get_by_label('Registry name',exact=True).fill('Public TLS');page.get_by_label('HTTPS index URL',exact=True).fill(url+'/index');page.get_by_role('button',name='Add registry',exact=True).click();page.get_by_text('Registry registered',exact=True).wait_for();page.locator('article').filter(has=page.get_by_role('heading',name='Public TLS',exact=True)).get_by_role('button',name='Browse packages').click();page.get_by_text('Registry packages loaded',exact=True).wait_for();assert any(auth is None for _,auth in requests) and any(auth=='Bearer private-ui-fixture-secret' for _,auth in requests) and any(auth=='Bearer rotated-ui-fixture-secret' for _,auth in requests)
                def reachable(control):
                    control.scroll_into_view_if_needed();control.focus();expect(control).to_be_focused()
                    geometry=control.evaluate('el=>{const r=el.getBoundingClientRect(),b=document.querySelector(".manager-back").getBoundingClientRect();return {top:r.top,bottom:r.bottom,headerBottom:b.bottom,uncovered:[[r.left+4,r.top+4],[r.right-4,r.bottom-4],[r.left+r.width/2,r.top+r.height/2]].every(([x,y])=>{const hit=document.elementFromPoint(x,y);return hit===el||el.contains(hit)})}}')
                    assert geometry['uncovered'] and geometry['top']>=geometry['headerBottom'],geometry
                    return geometry
                axe=Path(__file__).resolve().parents[1]/'desktop/workspace/node_modules/axe-core/axe.min.js'
                for theme,width in [('dark',1440),('light',1440),('dark',720),('light',720)]:
                    page.set_viewport_size({'width':width,'height':1000 if width==1440 else 500});page.get_by_role('button',name='Appearance',exact=True).click();page.get_by_role('radio',name=theme.capitalize(),exact=True).click();page.get_by_role('button',name='Close',exact=True).click();page.get_by_role('button',name='Plugins & skills',exact=True).click();page.get_by_role('heading',name='Plugins & skills',level=1,exact=True).wait_for();page.locator('article').filter(has_text='project · file-import ·').get_by_role('button',name='Edit source',exact=True).click();expect(page.get_by_label('Skill instructions',exact=True)).to_have_value(TEXT+' Uploaded draft');expect(page.get_by_role('button',name='Review skill publication',exact=True)).to_be_enabled();skill_geometry=reachable(page.get_by_role('button',name='Review skill publication',exact=True));page.add_script_tag(path=str(axe));result=page.evaluate('async()=>await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}})');violations=[{'id':v['id'],'targets':[n['target'] for n in v['nodes']]} for v in result['violations']];assert not violations,violations;page.screenshot(path=str(destination/f'extensions-{theme}-{width}.png'));report['states'].append({'theme':theme,'width':width,'axe_violations':violations,'publication_geometry':skill_geometry})
                    if width==720:
                        page.get_by_role('button',name='Memory',exact=True).click();page.get_by_role('button',name='Edit memory',exact=True).click();memory_form=page.get_by_role('form',name='Edit memory',exact=True);memory_geometry=reachable(memory_form.get_by_role('button',name='Save memory changes',exact=True));page.screenshot(path=str(destination/f'manager-header-memory-{theme}-200.png'));page.get_by_role('button',name='Agents',exact=True).click();preset_form=page.get_by_role('form',name='Create agent preset',exact=True);preset_form.get_by_label('Name',exact=True).fill('Geometry proof draft');preset_geometry=reachable(preset_form.get_by_role('button',name='Save preset',exact=True));page.screenshot(path=str(destination/f'manager-header-preset-{theme}-200.png'));report.setdefault('manager_header_geometry',[]).append({'theme':theme,'zoom':200,'memory':memory_geometry,'preset':preset_geometry});page.get_by_role('button',name='Plugins & skills',exact=True).click();page.get_by_role('heading',name='Plugins & skills',level=1,exact=True).wait_for()
                assert not report['errors'];assert adapter.turns==0;assert (global_skill/'SKILL.md').read_text()==TEXT+' Global';report['TLS_requests']=[{'path':path,'authenticated':auth is not None} for path,auth in requests];report['credentials_backend_only']=True;report['status']='passed';context.close();browser.close()
        except BaseException:
            report['status']='failed';
            if 'page' in locals():
                try:page.screenshot(path=str(destination/'failure.png'));report['visible_text']=page.locator('body').inner_text()
                except Exception:pass
            raise
        finally:
            server.should_exit=True;worker.join(10)
            try:next(fixture)
            except StopIteration:pass
            (destination/'report.json').write_text(json.dumps(report,indent=2))
if __name__=='__main__':run(sys.argv[1])
