"""Real scoped MCP Manager + stdio server UI proof; isolated host/no model queries."""
import asyncio,json,os,socket,sys,tempfile,threading
from pathlib import Path
from time import monotonic,sleep
import uvicorn
from playwright.sync_api import sync_playwright,expect
from termx.agent.secrets import CredentialStore
from termx.agent.providers import ProviderCall,ProviderTurn

class Adapter:
 def __init__(self):self.turns=0
 async def plan(self,prompt,cwd,manifest):return {"summary":"Inspect scoped tools and calculate 2 + 3","steps":["Inspect tools","Call reviewed add"],"tools":["mcp_catalog","mcp_call"],"risks":[]},"fixture-plan"
 async def turn(self,**kwargs):
  self.turns+=1
  if self.turns==1:return ProviderTurn(response_id="catalog",text="",calls=[ProviderCall("function","catalog","mcp_catalog",{})],usage={})
  if self.turns==2:return ProviderTurn(response_id="add",text="",calls=[ProviderCall("function","add","mcp_call",{"connection":"connection.ui-scoped","tool":"add","arguments":{"a":2,"b":3}})],usage={})
  return ProviderTurn(response_id="done",text="Verified scoped MCP result: 5",calls=[],usage={})

def run(destination):
 destination=Path(destination);destination.mkdir(parents=True,exist_ok=True);report={'proof':'actual-project-scoped-mcp-manager','paid_queries':0,'external_navigation':0,'errors':[],'states':[]}
 with tempfile.TemporaryDirectory(prefix='termx-mcp-ui-') as temporary:
  root=Path(temporary);os.environ.update(TERMX_CONFIG_DIR=str(root/'config'),TERMX_AGENTS_DIR=str(root/'agents'),TERMX_ENGINE_STARTUP_REFRESH='0')
  from termx.app import AppState,create_app
  from workspace_ui_snapshot import snapshot_ui
  adapter=Adapter();state=AppState(passcode=None,credentials=CredentialStore(memory={}),adapter_factory=lambda *_:adapter);owner=state.identity.setup_owner('mcp-owner','mcp-fixture-password-123');one=root/'one';two=root/'two';one.mkdir();two.mkdir();project=state.projects.register(str(one),name='Allowed MCP project');foreign=state.projects.register(str(two),name='Different project')
  state.agent.save_provider(provider_id='mcp-fixture',kind='openai',name='No-network MCP fixture',base_url='https://fixture.invalid',model='fixture',capabilities=['functions'],api_key='fixture-no-network')
  app=create_app(state,web_dir=snapshot_ui(root,Path(os.environ.get('TERMX_UI_PROOF_DIST',str(Path(__file__).resolve().parents[1]/'desktop/workspace/dist')))));session=state.workspace.create_session(owner,provider_id='mcp-fixture',model='fixture',mode='agent',title='MCP scope proof',project_id=project['id'],cwd=str(one));report['UI_asset_snapshot']=json.loads((root/'fixture-ui-snapshot.json').read_text())
  listener=socket.socket();listener.bind(('127.0.0.1',0));listener.listen();port=listener.getsockname()[1];host=uvicorn.Server(uvicorn.Config(app,log_level='error',lifespan='on'));worker=threading.Thread(target=lambda:asyncio.run(host.serve(sockets=[listener])),daemon=True);worker.start();deadline=monotonic()+30
  while not host.started:
   if monotonic()>deadline:raise RuntimeError('MCP fixture host failed to start')
   sleep(.05)
  try:
   with sync_playwright() as playwright:
    browser=playwright.chromium.launch(headless=True);context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce');page=context.new_page();page.on('pageerror',lambda error:report['errors'].append(str(error)));page.goto(f'http://127.0.0.1:{port}/?session={session["id"]}');page.get_by_label('Username',exact=True).fill('mcp-owner');page.get_by_label('Password',exact=True).fill('mcp-fixture-password-123');page.get_by_role('button',name='Continue with password').click();page.wait_for_function('document.querySelector(".breadcrumb strong")?.textContent==="MCP scope proof"',timeout=60000)
    page.get_by_role('button',name='Managers',exact=True).click();page.get_by_role('button',name='Tools & connections',exact=True).click();page.get_by_text('Add a tool connection',exact=True).click();form=page.get_by_role('form',name='Add tool connection');form.get_by_label('Connection ID',exact=True).fill('ui-scoped');form.get_by_label('Connection name',exact=True).fill('Scoped fixture tools');form.get_by_label('Connection transport',exact=True).select_option('stdio');form.get_by_label('Executable and arguments',exact=True).fill(json.dumps([sys.executable,str(Path(__file__).parent.resolve()/'fixtures/fake_mcp_server.py')]));form.get_by_role('radio',name='Only selected projects').check();form.get_by_role('checkbox',name='Allowed MCP project',exact=True).check();form.get_by_label('Approved tool names',exact=True).fill('add');form.get_by_label('Connection authentication',exact=True).select_option('env');form.get_by_role('button',name='Save untrusted connection').click();page.get_by_role('heading',name='Scoped fixture tools',exact=True).wait_for();assert state.mcp_registry().get('ui-scoped').allowed_projects==[project['id']];assert state.mcp_pool.status()=={}
    page.get_by_role('button',name='Edit connection',exact=True).click();credential=page.get_by_role('form',name='Managed connection credential');credential.get_by_label('Binding name',exact=True).fill('TOKEN');credential.get_by_label('New secret value',exact=True).fill('fixture-write-only');credential.get_by_role('button',name='Save credential binding').click();page.get_by_text('Credential configured',exact=False).first.wait_for();assert 'fixture-write-only' not in page.locator('body').inner_text();conn=state.mcp_registry().get('ui-scoped');assert any(state.credentials.get(ref)=='fixture-write-only' for ref in conn.secret_refs)
    page.get_by_role('button',name='Trust reviewed connection',exact=True).click();connect=page.get_by_role('button',name='Connect in current project',exact=True);expect(connect).to_be_enabled();connect.click();page.get_by_role('button',name='Disconnect',exact=True).wait_for(timeout=60000);page.get_by_role('button',name='Inspect tools and permissions',exact=True).click();inspection=page.get_by_role('region',name='Connection permission inspection');inspection.get_by_label('Tool to inspect',exact=True).select_option('add');inspection.get_by_label('Tool arguments',exact=True).fill('{"a":7,"b":5}');inspection.get_by_role('button',name='Call selected tool',exact=True).click();output=inspection.get_by_role('region',name='Tool result');expect(output).to_contain_text('12');report['actual_stdio_tool_result']=json.loads(output.inner_text())
    page.get_by_role('button',name='Agents',exact=True).click();preset_form=page.get_by_role('form',name='Create agent preset');preset_form.get_by_label('Name',exact=True).fill('Scoped MCP workflow');preset_form.get_by_label('Default engine for future sessions',exact=True).fill('internal');preset_form.get_by_role('checkbox',name='Scoped fixture tools',exact=True).check();preset_form.get_by_role('checkbox',name='add',exact=True).check();expect(preset_form.get_by_label('Allowed tool IDs (one per line)',exact=True)).to_have_value('mcp_catalog\nmcp_call');preset_form.get_by_role('button',name='Save preset',exact=True).click();page.get_by_role('heading',name='Scoped MCP workflow',exact=True).wait_for();preset=next(item for item in state.agent_store.list_custom_agents() if item['name']=='Scoped MCP workflow');assert preset['mcp_connections']==[{'connection':'connection.ui-scoped','tools':['add']}],preset;report['typed_preset_binding']=preset['mcp_connections']
    page.get_by_role('button',name='Back to workspace',exact=True).click();page.get_by_text('Agent preset · Default agent',exact=True).click();page.get_by_label('Session agent preset',exact=True).select_option(preset['id']);deadline=monotonic()+20
    while state.workspace.session(owner,session['id'],turns=False).get('custom_agent_id')!=preset['id']:
     if monotonic()>deadline:raise AssertionError('UI preset did not bind to canonical conversation')
     sleep(.05)
    page.get_by_label('Message',exact=True).fill('Calculate through the explicitly selected MCP preset');page.get_by_role('button',name='Send message',exact=True).click();deadline=monotonic()+60;approved=0
    while not page.get_by_text('Verified scoped MCP result: 5',exact=True).count():
     if monotonic()>deadline:raise AssertionError('Actual preset agent loop failed: '+page.locator('body').inner_text())
     allow=page.get_by_role('button',name='Allow once',exact=True)
     if allow.count():allow.first.click();approved+=1
     sleep(.1)
    task=state.agent_store.active_conversation_tasks(session['id']);assert not task;turn=state.agent_store.get_conversation(session['id'],include_turns=True)['turns'][-1];task_id=turn['task_id'];events=state.agent_store.events(task_id);outputs=[e['payload'].get('result',{}) for e in events if e['type']=='tool.finished'];assert any('5' in str(output.get('result','')) and output.get('tool')=='add' for output in outputs),outputs;assert any(a['kind']=='tool' and a['status']=='approved' for a in state.agent_store.approvals(task_id));assert approved>0;report['actual_agent_tool_result']=outputs;report['explicit_approval_clicks']=approved;print('Verified scoped MCP preset and actual agent effect',flush=True)
    # A real project selector change may not move the selected conversation.
    # Switch to a canonical second conversation to exercise exact execution scope.
    second=state.workspace.create_session(owner,title='Different MCP scope',project_id=foreign['id'],cwd=str(two));page.goto(f'http://127.0.0.1:{port}/?session={second["id"]}');page.wait_for_function('document.querySelector(".breadcrumb strong")?.textContent==="Different MCP scope"');page.get_by_role('button',name='Managers',exact=True).click();page.get_by_role('button',name='Tools & connections',exact=True).click();page.get_by_role('heading',name='Scoped fixture tools',exact=True).wait_for();page.get_by_text('Unavailable for the selected execution project.',exact=True).wait_for();page.get_by_role('button',name='Disconnect',exact=True).click();expect(page.get_by_role('button',name='Connect in current project',exact=True)).to_be_disabled();assert state.mcp_pool.status()=={}
    page.get_by_role('button',name='Edit connection',exact=True).click();form=page.get_by_role('form',name='Edit tool connection');form.get_by_label('Approved tool names',exact=True).fill('');form.get_by_role('button',name='Save connection changes',exact=True).click();page.get_by_role('button',name='Inspect tools and permissions',exact=True).click();page.get_by_text('Configured allowed tools: None.',exact=False).wait_for();assert state.mcp_registry().get('ui-scoped').approved_tools==[]
    for theme,width in [('dark',1440),('light',1440),('dark',720),('light',720)]:
     page.set_viewport_size({'width':width,'height':1000 if width==1440 else 500});page.get_by_role('button',name='Appearance',exact=True).click();page.get_by_role('radio',name=theme.title(),exact=True).check();page.get_by_role('button',name='Close',exact=True).click();page.get_by_role('button',name='Edit connection',exact=True).click();form=page.get_by_role('form',name='Edit tool connection');form.get_by_label('Approved tool names',exact=True).focus();expect(form.get_by_label('Approved tool names',exact=True)).to_be_focused();page.add_script_tag(path=str(Path(__file__).resolve().parents[1]/'desktop/workspace/node_modules/axe-core/axe.min.js'));result=page.evaluate('async()=>await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}})');violations=[{'id':v['id'],'targets':[n['target'] for n in v['nodes']]} for v in result['violations']];assert not violations,violations;assert not page.evaluate('document.documentElement.scrollWidth>innerWidth');page.screenshot(path=str(destination/f'mcp-{theme}-{width}.png'));report['states'].append({'theme':theme,'width':width,'axe_violations':violations});form.get_by_role('button',name='Cancel connection edit',exact=True).click()
    assert not report['errors'];report['status']='passed';context.close();browser.close()
  except BaseException:report['status']='failed';raise
  finally:host.should_exit=True;worker.join(15);(destination/'report.json').write_text(json.dumps(report,indent=2))
if __name__=='__main__':run(sys.argv[1])
