"""Engine adapter interface (tech-specs §1).

Native sessions are authoritative: adapters translate TermX calls into the
engine's own protocol and stream the engine's own events back. They never
re-implement an agent loop.
"""

from __future__ import annotations

from typing import Any, Protocol

from .types import (
    EffectiveRunConfiguration,
    EngineCapabilities,
    EngineDescriptor,
    EngineSessionBinding,
)


class EngineAdapter(Protocol):
    def descriptor(self) -> EngineDescriptor: ...
    async def probe(self) -> EngineDescriptor: ...
    def capabilities(self) -> EngineCapabilities: ...
    async def create_session(self, cfg: EffectiveRunConfiguration) -> EngineSessionBinding: ...
    async def attach(self, binding: EngineSessionBinding) -> EngineSessionBinding: ...
    async def send(self, binding: EngineSessionBinding, prompt: str,
                   attachments: list[dict[str, Any]] | None = None) -> str | None: ...
    async def cancel(self, binding: EngineSessionBinding) -> None: ...
    async def respond_approval(self, binding: EngineSessionBinding,
                               request_id: str, decision: str,
                               remember: bool = False) -> None: ...
    async def close(self, binding: EngineSessionBinding) -> None: ...
    async def steer(self, binding: EngineSessionBinding, text: str) -> bool: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def shutdown(self) -> None: ...
