import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest';
import {request,unlockWorkspace} from './api';
vi.mock('./native',()=>({nativeWorkspace:()=>false}));
beforeEach(()=>{document.cookie='termx_csrf=csrf-fixture';localStorage.clear()});
afterEach(()=>vi.unstubAllGlobals());
describe('managed cookie API boundary',()=>{
 it('coordinates parallel refresh once and includes CSRF without exposing a bearer',async()=>{let calls=0,refreshes=0;const fetch=vi.fn(async(path:string)=>{if(path==='/auth/me')return new Response('{}',{status:401});if(path==='/auth/refresh'){refreshes++;return new Response('{}',{status:200})}calls++;return new Response(calls<=2?'{}':'{"ok":true}',{status:calls<=2?401:200})});vi.stubGlobal('fetch',fetch);Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_name:string,run:()=>unknown)=>run()}});const result=await Promise.all([request('/api/fixture',{method:'POST',body:'{}'}),request('/api/fixture',{method:'POST',body:'{}'})]);expect(result).toEqual([{ok:true},{ok:true}]);expect(refreshes).toBe(1);for(const [,init] of fetch.mock.calls.filter(([path])=>path==='/api/fixture') as unknown as [string,RequestInit][]){expect(init.credentials).toBe('same-origin');expect(new Headers(init.headers).get('X-Termx-CSRF')).toBe('csrf-fixture');expect(new Headers(init.headers).has('Authorization')).toBe(false)}expect(localStorage.length).toBe(0)});
 it('retains the family on locked refresh and signals lock without signout',async()=>{const locked=vi.fn(),signedOut=vi.fn();window.addEventListener('termx-session-locked',locked);window.addEventListener('termx-signed-out',signedOut);try{vi.stubGlobal('fetch',vi.fn(async(path:string)=>new Response('{"detail":"Session locked; unlock required"}',{status:path==='/auth/refresh'?423:401})));Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_name:string,run:()=>unknown)=>run()}});await expect(request('/api/fixture')).rejects.toMatchObject({status:423});expect(locked).toHaveBeenCalledOnce();expect(signedOut).not.toHaveBeenCalled();expect(localStorage.length).toBe(0)}finally{window.removeEventListener('termx-session-locked',locked);window.removeEventListener('termx-signed-out',signedOut)}});
 it('signals direct423 and reauthenticates through explicit unlock',async()=>{const event=vi.fn();window.addEventListener('termx-session-locked',event);const fetch=vi.fn(async(path:string)=>new Response(path==='/auth/me'?'{"session_id":"same"}':'{}',{status:path==='/api/locked'?423:200}));vi.stubGlobal('fetch',fetch);try{await expect(request('/api/locked',{},false)).rejects.toMatchObject({status:423});expect(event).toHaveBeenCalledOnce();expect(await unlockWorkspace({method:'local-password',username:'owner',password:'fixture'})).toEqual({session_id:'same'});const [,init]=fetch.mock.calls.find(([path])=>path==='/auth/unlock')! as unknown as [string,RequestInit];expect(JSON.parse(String(init.body))).toEqual({method:'local-password',username:'owner',password:'fixture'});expect(new Headers(init.headers).get('X-Termx-CSRF')).toBe('csrf-fixture')}finally{window.removeEventListener('termx-session-locked',event)}});
 it('rejects another origin before reading session credentials',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(request('//other.example/private')).rejects.toThrow('workspace origin');expect(fetch).not.toHaveBeenCalled()});
 it('preserves explicit backend authorization failures',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('{"error":"This origin is not granted"}',{status:403})));await expect(request('/api/fixture')).rejects.toThrow('This origin is not granted')});
});
