import {windowSlot} from './window-state';
export type ArtifactDraft={key:string;artifact_id:string;project_id:string|null;title:string;kind:string;version:number;content:unknown};
const active=new Map<string,ArtifactDraft[]>();let database:Promise<IDBDatabase>|undefined;let frozen=false;const writes=new Set<Promise<void>>();
export function validateArtifactDrafts(value:unknown):ArtifactDraft[]{if(!Array.isArray(value)||value.length>30||JSON.stringify(value).length>8*1024*1024)throw Error('Invalid artifact draft handoff');return value.map(item=>{if(!item||typeof item.key!=='string'||item.key.length>256||typeof item.artifact_id!=='string'||item.artifact_id.length>128||!(item.key===item.artifact_id||item.key.startsWith(item.artifact_id+':handoff:'))||!(item.project_id===null||typeof item.project_id==='string')||typeof item.title!=='string'||item.title.length>512||!['document','code','table','chart','deck'].includes(item.kind)||!artifactContent(item.kind,item.content)||!Number.isSafeInteger(item.version)||item.version<1||JSON.stringify(item.content)?.length>2*1024*1024)throw Error('Invalid artifact draft handoff');return structuredClone({key:item.key,artifact_id:item.artifact_id,project_id:item.project_id,title:item.title,kind:item.kind,version:item.version,content:item.content})})}
function db(){return database??=new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('termx-workspace-artifact-drafts',1);request.onupgradeneeded=()=>request.result.createObjectStore('slots');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export function snapshotArtifactDrafts(owner:string){return structuredClone(active.get(owner)||[])}
export async function restoreArtifactDrafts(owner:string,slot=windowSlot()){const database=await db();return new Promise<ArtifactDraft[]>((resolve,reject)=>{const read=database.transaction('slots','readonly').objectStore('slots').get(JSON.stringify([owner,slot]));read.onsuccess=()=>{try{resolve(read.result===undefined?[]:validateArtifactDrafts(read.result))}catch(error){reject(error)}};read.onerror=()=>reject(read.error)})}
export async function persistArtifactDrafts(owner:string,rows:ArtifactDraft[],slot=windowSlot()){if(frozen&&slot===windowSlot())throw Error('Artifact handoff is in progress.');const safe=validateArtifactDrafts(rows);if(slot===windowSlot())active.set(owner,safe);const write=(async()=>{const database=await db();await new Promise<void>((resolve,reject)=>{const tx=database.transaction('slots','readwrite');tx.objectStore('slots').put(safe,JSON.stringify([owner,slot]));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})})();writes.add(write);try{await write}finally{writes.delete(write)}}
export async function freezeArtifactDrafts(){frozen=true;await Promise.all(writes)}
export function unfreezeArtifactDrafts(){frozen=false}
export async function dropArtifactDrafts(owner:string){active.delete(owner);const database=await db();await new Promise<void>((resolve,reject)=>{const tx=database.transaction('slots','readwrite');tx.objectStore('slots').delete(JSON.stringify([owner,windowSlot()]));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export function mergeArtifactDrafts(existing:ArtifactDraft[],incoming:ArtifactDraft[],handoff:string){const rows=structuredClone(existing);for(const item of incoming){const old=rows.find(row=>row.key===item.key);if(!old)rows.push(item);else if(JSON.stringify(old.content)!==JSON.stringify(item.content)||old.version!==item.version){const key=item.key+':handoff:'+handoff;if(!rows.some(row=>row.key===key))rows.push({...item,key,title:item.title+' (returned copy)'})}}return validateArtifactDrafts(rows)}
export async function receiveArtifactDrafts(owner:string,incoming:ArtifactDraft[],handoff:string){const rows=mergeArtifactDrafts(await restoreArtifactDrafts(owner),incoming,handoff);await persistArtifactDrafts(owner,rows);window.dispatchEvent(new CustomEvent('termx-artifact-handoff',{detail:{owner,rows}}))}
if(typeof window!=='undefined')window.addEventListener('termx-signed-out',()=>active.clear());
export function artifactContent(kind:string,value:unknown){if(['document','code'].includes(kind))return typeof value==='string';if(kind==='table'){const row=value as {columns:unknown[];rows:unknown[][]};return !!row&&Array.isArray(row.columns)&&row.columns.length<=500&&row.columns.every(item=>typeof item==='string')&&Array.isArray(row.rows)&&row.rows.length<=10000&&row.rows.every(cells=>Array.isArray(cells)&&cells.length<=500&&cells.every(item=>typeof item==='string'||typeof item==='number'||item===null))}if(kind==='chart'){const row=value as {points:{label:string;value:number}[]};return !!row&&Array.isArray(row.points)&&row.points.length<=10000&&row.points.every(item=>item&&typeof item.label==='string'&&typeof item.value==='number'&&Number.isFinite(item.value))}return kind==='deck'&&Array.isArray(value)&&value.length<=500&&value.every(item=>item&&typeof item.title==='string'&&typeof item.body==='string'&&(item.notes===undefined||typeof item.notes==='string'))}
