import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {listenBrowserRedock,expectedBrowserSource,openBrowserWindow} from './browser-windows';
import {request} from './api';
import {windowSlot} from './window-state';
import {windowRecord,registerBrowserWindow,type WindowRecord} from './window-journal';
vi.mock('./api',()=>({request:vi.fn(async()=>({principal:{id:'owner'}}))}));
vi.mock('./window-journal',()=>({windowRecord:vi.fn(),registerBrowserWindow:vi.fn(),dropWindowJournal:vi.fn()}));
let release:(()=>void)|undefined;
beforeEach(()=>{vi.clearAllMocks();window.name='termx-workspace-main'});
afterEach(()=>{release?.();release=undefined;vi.restoreAllMocks()});
const message={type:'termx-window-return' as const,id:'receipt',slot:'termx-workspace-child',token:'known-token',ownerId:'owner',sessionId:'session',panel:'workbench' as const,payload:{version:1 as const,sessionId:'session',draft:null,buffers:[]}};
function source(){return {opener:window,name:message.slot,location:{origin:location.origin,pathname:location.pathname},postMessage:vi.fn(),focus:vi.fn(),close:vi.fn()} as unknown as Window}
function record():WindowRecord{return {slot:message.slot,ownerId:'owner',sessionId:'session',panel:'workbench',parent:windowSlot(),token:message.token,updated:Date.now()}}
function event(sender:Window,row:unknown=message,origin=location.origin){window.dispatchEvent(new MessageEvent('message',{origin,source:sender,data:row}))}
it('requires exact same-origin opener, owner, conversation, nonce and source slot',()=>{const child=source(),entry=record();const base={origin:location.origin,source:child} as MessageEvent;expect(expectedBrowserSource(base,message,entry,'owner')).toBe(true);for(const changed of [{origin:'https://foreign.invalid',source:child},{origin:location.origin,source:window},{origin:location.origin,source:{...child,opener:null}}])expect(expectedBrowserSource(changed as MessageEvent,message,entry,'owner')).toBe(false);for(const changed of [{...entry,ownerId:'foreign'},{...entry,token:'wrong'},{...entry,sessionId:'foreign'},{...entry,parent:'other-main'}])expect(expectedBrowserSource(base,message,changed,'owner')).toBe(false)});
it('acknowledges only after durable main application and suppresses a cancelled late acknowledgement',async()=>{
 const child=source();vi.mocked(windowRecord).mockResolvedValue(record());let complete!:()=>void;const applied=vi.fn(()=>new Promise<void>(resolve=>{complete=resolve}));release=listenBrowserRedock('owner',applied);event(child);await vi.waitFor(()=>expect(applied).toHaveBeenCalledOnce());expect(child.postMessage).not.toHaveBeenCalled();event(child,{...message,type:'termx-window-cancel'});await new Promise(resolve=>setTimeout(resolve,0));complete();await new Promise(resolve=>setTimeout(resolve,0));expect(child.postMessage).not.toHaveBeenCalled();
});
it('refuses foreign source and escaped buffer payload without applying state',async()=>{const child=source();vi.mocked(windowRecord).mockResolvedValue(record());const applied=vi.fn();release=listenBrowserRedock('owner',applied);event(child,message,'https://foreign.invalid');event(child,{...message,ownerId:'foreign'});event(child,{...message,payload:{...message.payload,buffers:[{key:'bad',project_id:'project',path:'../escape',content:'text',revision:'r',dirty:true,editable:true}]}});await vi.waitFor(()=>expect(child.postMessage).toHaveBeenCalled());expect(applied).not.toHaveBeenCalled();expect(vi.mocked(child.postMessage).mock.calls[0][0]).toMatchObject({type:'termx-window-rejected'})});
it('keeps state when popups are denied and focuses an already open named window without navigating it',async()=>{vi.spyOn(window,'open').mockReturnValueOnce(null);await expect(openBrowserWindow('owner','session','workbench')).rejects.toThrow('blocked');expect(registerBrowserWindow).not.toHaveBeenCalled();const child=source();vi.mocked(window.open).mockReturnValue(child);await openBrowserWindow('owner','session','workbench',record());expect(child.focus).toHaveBeenCalledOnce();expect(registerBrowserWindow).not.toHaveBeenCalled();expect(window.open).toHaveBeenLastCalledWith('',message.slot,expect.any(String))});

it('keeps an existing named dirty window open if live authority validation fails',async()=>{const child=source();vi.spyOn(window,'open').mockReturnValue(child);vi.mocked(request).mockRejectedValueOnce(new Error('Revoked session'));await expect(openBrowserWindow('owner','session','workbench',record())).rejects.toThrow('Revoked');expect(child.close).not.toHaveBeenCalled();expect(registerBrowserWindow).not.toHaveBeenCalled()});
