import {persistArtifactDrafts,snapshotArtifactDrafts,dropArtifactDrafts} from './artifact-drafts';
import {request} from './api';
import {windowSlot,validateWindowState,type WindowState} from './window-state';
import {registerBrowserWindow,windowRecord,dropWindowJournal,type WindowPanel,type WindowRecord} from './window-journal';
type Envelope={type:'termx-window-return'|'termx-window-accepted'|'termx-window-rejected'|'termx-window-cancel';id:string;slot:string;token:string;ownerId:string;sessionId:string;panel:WindowPanel;payload?:WindowState;error?:string};
export type BrowserRedockEvent={id:string;ownerId:string;sessionId:string;panel:WindowPanel;payload:WindowState};
const pending=new Map<string,{source:Window;message:Envelope;cancelled:boolean;deadline:number}>();
const accepted=new Map<string,Envelope>();
function envelope(value:unknown):value is Envelope{if(!value||typeof value!=='object')return false;const row=value as Envelope;return ['termx-window-return','termx-window-accepted','termx-window-rejected','termx-window-cancel'].includes(row.type)&&typeof row.id==='string'&&row.id.length<=128&&typeof row.slot==='string'&&row.slot.startsWith('termx-workspace-')&&row.slot.length<=128&&typeof row.token==='string'&&row.token.length<=128&&typeof row.ownerId==='string'&&typeof row.sessionId==='string'&&(row.error===undefined||(typeof row.error==='string'&&row.error.length<=1000))&&['chat','workbench','browser','computer','artifacts'].includes(row.panel)}
export function expectedBrowserSource(event:MessageEvent,row:Envelope,record:WindowRecord|undefined,ownerId:string){if(event.origin!==location.origin||!event.source||row.ownerId!==ownerId||!record||record.ownerId!==ownerId||record.slot!==row.slot||record.token!==row.token||record.parent!==windowSlot()||record.sessionId!==row.sessionId)return false;try{const source=event.source as Window;return source!==window&&source.opener===window&&source.name===row.slot&&source.location.origin===location.origin}catch{return false}}
export async function openBrowserWindow(ownerId:string,sessionId:string|null,panel:WindowPanel,recovery?:WindowRecord){const slot=recovery?.slot||'termx-workspace-'+crypto.randomUUID();const popup=window.open('',slot,'popup,width=1100,height=800');if(!popup)throw new Error('Your browser blocked the detached window. Allow popups for this workspace and try again.');let existing=false;try{existing=popup.location.origin===location.origin&&popup.location.pathname===location.pathname;const auth=await request<{principal:{id:string}}>('/auth/me');if(auth.principal.id!==ownerId)throw new Error('Workspace principal changed');if(sessionId)await request('/api/workspace/sessions/'+sessionId+'?turns=false');if(existing){popup.focus();return popup}const row:WindowRecord={slot,ownerId,sessionId,panel,parent:windowSlot(),token:crypto.randomUUID(),updated:Date.now()};await registerBrowserWindow(row);if(panel==='artifacts'&&!recovery)await persistArtifactDrafts(ownerId,snapshotArtifactDrafts(ownerId),slot);const url=new URL(location.origin+(sessionId?'/session/'+encodeURIComponent(sessionId):'/'));url.searchParams.set('layout',panel);url.searchParams.set('detached','true');url.searchParams.set('parent-window',row.parent!);url.searchParams.set('handoff-token',row.token!);popup.location.replace(url.href);return popup}catch(error){if(!existing)popup.close();throw error}}
export function listenBrowserRedock(ownerId:string,handler:(event:BrowserRedockEvent)=>Promise<void>){const listener=(event:MessageEvent)=>{void(async()=>{const row=event.data;if(!envelope(row)||event.origin!==location.origin||row.ownerId!==ownerId)return;const record=await windowRecord(ownerId,row.slot);if(!expectedBrowserSource(event,row,record,ownerId))return;if(row.type==='termx-window-cancel'){const live=pending.get(row.id);if(live&&live.source===event.source)live.cancelled=true;return}if(row.type!=='termx-window-return'||pending.has(row.id))return;pending.set(row.id,{source:event.source as Window,message:row,cancelled:false,deadline:Date.now()+45000});try{const payload=validateWindowState(row.payload);if(payload.sessionId!==row.sessionId)throw new Error('Workspace handoff conversation changed');await handler({id:row.id,ownerId,sessionId:row.sessionId,panel:row.panel,payload});const live=pending.get(row.id);if(!live||live.cancelled||Date.now()>live.deadline)return;live.source.postMessage({...row,type:'termx-window-accepted',payload:undefined},location.origin)}catch(error){const live=pending.get(row.id);if(live&&!live.cancelled)live.source.postMessage({...row,type:'termx-window-rejected',payload:undefined,error:error instanceof Error?error.message.slice(0,1000):'The main workspace could not accept this state.'},location.origin)}finally{pending.delete(row.id)}})()};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener)}
export async function requestBrowserRedock(ownerId:string,sessionId:string,panel:WindowPanel,payload:WindowState){const opener=window.opener as Window|null,record=await windowRecord(ownerId,windowSlot());if(!opener||opener.closed||!record?.token||!record.parent)throw new Error('The main workspace is unavailable. Your unsaved state remains in this window.');const message:Envelope={type:'termx-window-return',id:crypto.randomUUID(),slot:windowSlot(),token:record.token,ownerId,sessionId,panel,payload};return await new Promise<string>((resolve,reject)=>{const timeout=setTimeout(()=>finish(new Error('The main workspace did not acknowledge the handoff. This window remains open.')),45000);const listener=(event:MessageEvent)=>{const row=event.data;if(event.origin!==location.origin||event.source!==opener||!envelope(row)||row.id!==message.id||row.token!==message.token||row.slot!==message.slot||row.ownerId!==ownerId||row.sessionId!==sessionId)return;if(row.type==='termx-window-accepted'){accepted.set(message.id,message);finish()}else if(row.type==='termx-window-rejected')finish(new Error((row.error||'The main workspace could not accept this state.')+' Review both windows; this window remains open.'))};function finish(error?:Error){clearTimeout(timeout);window.removeEventListener('message',listener);if(error){opener!.postMessage({...message,type:'termx-window-cancel',payload:undefined},location.origin);reject(error)}else resolve(message.id)}window.addEventListener('message',listener);opener.postMessage(message,location.origin)})}
export function cancelBrowserRedock(id:string){const row=accepted.get(id);if(row&&window.opener)window.opener.postMessage({...row,type:'termx-window-cancel',payload:undefined},location.origin);accepted.delete(id)}
export async function commitBrowserRedock(id:string){const row=accepted.get(id);if(!row)throw new Error('Workspace handoff was not acknowledged');const auth=await request<{principal:{id:string}}>('/auth/me');if(auth.principal.id!==row.ownerId)throw new Error('Workspace handoff principal changed');await request('/api/workspace/sessions/'+row.sessionId+'?turns=false');await dropArtifactDrafts(row.ownerId);await dropWindowJournal(row.ownerId);accepted.delete(id);window.close()}
