export const defaults={chat:'Mod+1',workbench:'Mod+2',browser:'Mod+3',review:'Mod+4',computer:'Mod+5',left:'Mod+B',right:'Mod+Alt+B',bottom:'Mod+J',palette:'Mod+K',newConversation:'Mod+Shift+N',focus:'Mod+K Z',undoLayout:'Mod+Alt+Z',resetLayout:'Mod+Alt+R',focusConversation:'Mod+Alt+1',focusEditor:'Mod+Alt+2',focusBrowser:'Mod+Alt+3'};
export type CommandId=keyof typeof defaults;
export type Bindings=Record<CommandId,string>;
export const labels:Record<CommandId,string>={chat:'Chat',workbench:'Workbench',browser:'Browser',review:'Review layout',computer:'Computer',left:'Toggle left panel',right:'Toggle right panel',bottom:'Toggle bottom panel',palette:'Workspace commands',newConversation:'New conversation',focus:'Focus mode / restore layout',undoLayout:'Undo layout',resetLayout:'Reset layout',focusConversation:'Focus conversation',focusEditor:'Focus editor',focusBrowser:'Focus browser'};
export function strokeMatches(stroke:string,event:KeyboardEvent){const pieces=stroke.toLowerCase().split('+').map(part=>part.trim()),key=pieces.pop();const mod=pieces.includes('mod');return event.key.toLowerCase()===key&&event.shiftKey===pieces.includes('shift')&&event.altKey===pieces.includes('alt')&&(mod?(event.ctrlKey||event.metaKey):event.ctrlKey===pieces.includes('ctrl')&&event.metaKey===pieces.includes('meta'));}
export function validateBindings(value:unknown):Bindings{const result={...defaults};if(value&&typeof value==='object')for(const id of Object.keys(defaults) as CommandId[]){const text=(value as Record<string,unknown>)[id];if(typeof text==='string'&&text.length<=80&&text.trim().split(/\s+/).every(stroke=>/^(?:(?:Mod|Ctrl|Meta|Alt|Shift)\+)*(?:[A-Za-z0-9]|Escape|F\d{1,2})$/i.test(stroke)))result[id]=text.trim();}return result;}
export function bindingWarnings(bindings:Bindings){const seen=new Map<string,string>();const warnings:string[]=[];for(const [id,binding] of Object.entries(bindings)){const normalized=binding.toLowerCase();if(seen.has(normalized))warnings.push(labels[id as CommandId]+' conflicts with '+seen.get(normalized));seen.set(normalized,labels[id as CommandId]);if(/^(mod|ctrl|meta)\+(w|t|l|r|n|q|[+-])$/i.test(binding))warnings.push(labels[id as CommandId]+': browsers may reserve '+binding+'. Use the Commands menu when the shortcut is unavailable.');}return warnings;}
export function protectedSurface(target:EventTarget|null){return target instanceof Element&&!!target.closest('.xterm,.computer-surface,.browser-frame,[data-agent-input="true"]');}

export function loadBindings(serialized:string|null){try{return validateBindings(JSON.parse(serialized||'null'))}catch{return {...defaults}}}
