import {act,renderHook} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {resolveTheme,useTheme} from './theme';
beforeEach(()=>localStorage.clear());afterEach(()=>vi.restoreAllMocks());
it('tracks live device appearance only in System mode and removes the listener on unmount',()=>{
 let listener:(()=>void)|undefined;const media={matches:false,addEventListener:vi.fn((_type:string,callback:()=>void)=>{listener=callback}),removeEventListener:vi.fn()};vi.spyOn(window,'matchMedia').mockReturnValue(media as unknown as MediaQueryList);
 const hook=renderHook(()=>useTheme());expect(document.documentElement.dataset.theme).toBe('dark');
 act(()=>hook.result.current[1]('system'));expect(document.documentElement.dataset.theme).toBe('light');expect(document.documentElement.dataset.themePreference).toBe('system');
 act(()=>{media.matches=true;listener?.()});expect(document.documentElement.dataset.theme).toBe('dark');
 act(()=>hook.result.current[1]('light'));act(()=>{media.matches=true;listener?.()});expect(document.documentElement.dataset.theme).toBe('light');
 hook.unmount();expect(media.removeEventListener).toHaveBeenCalledWith('change',expect.any(Function));expect(resolveTheme('system',false)).toBe('light');
});
it('restores the nonsecret shell appearance before any authenticated owner loads',()=>{const media={matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()};vi.spyOn(window,'matchMedia').mockReturnValue(media as unknown as MediaQueryList);const first=renderHook(()=>useTheme());act(()=>first.result.current[1]('light'));first.unmount();const lockedReload=renderHook(()=>useTheme());expect(lockedReload.result.current[0]).toBe('light');expect(document.documentElement.dataset.theme).toBe('light');expect(localStorage.getItem('termx-shell-theme')).toBe('light');act(()=>lockedReload.result.current[1]('dark'));expect(document.documentElement.dataset.theme).toBe('dark');lockedReload.unmount()});
it('restores System preference and resolves it against the current device after reload',()=>{let listener:(()=>void)|undefined;const media={matches:false,addEventListener:vi.fn((_type:string,callback:()=>void)=>listener=callback),removeEventListener:vi.fn()};vi.spyOn(window,'matchMedia').mockReturnValue(media as unknown as MediaQueryList);localStorage.setItem('termx-shell-theme','system');const hook=renderHook(()=>useTheme());expect(hook.result.current[0]).toBe('system');expect(document.documentElement.dataset.theme).toBe('light');act(()=>{media.matches=true;listener?.()});expect(document.documentElement.dataset.theme).toBe('dark');expect(localStorage.getItem('termx-shell-theme')).toBe('system');hook.unmount()});
it('ignores malformed presentation preferences without requiring or storing account credentials',()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()} as unknown as MediaQueryList);localStorage.setItem('termx-shell-theme','unexpected');const hook=renderHook(()=>useTheme());expect(hook.result.current[0]).toBe('dark');expect([...Array(localStorage.length)].map((_,index)=>localStorage.key(index))).toEqual(['termx-shell-theme']);expect(localStorage.getItem('termx-shell-theme')).toBe('dark');hook.unmount()});
