import {windowSlot} from './window-state';
import {sessionDrafts,type Draft} from './drafts';
export type WindowPanel='chat'|'workbench'|'browser'|'computer';
export type WindowRecord={slot:string;ownerId:string;sessionId:string|null;panel:WindowPanel;parent:string|null;token:string|null;updated:number};
const initial=new URLSearchParams(location.search);
export const detachedBrowser=initial.get('detached')==='true';
let database:Promise<IDBDatabase>|undefined;
function db(){return database??=new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('termx-workspace-window-journal',1);request.onupgradeneeded=()=>{request.result.createObjectStore('windows');request.result.createObjectStore('drafts')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function put(store:string,key:string,value:unknown){const database=await db();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function values<T>(store:string){const database=await db();return new Promise<T[]>((resolve,reject)=>{const request=database.transaction(store,'readonly').objectStore(store).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function windowRecord(ownerId:string,slot:string){return (await values<WindowRecord>('windows')).find(row=>row.ownerId===ownerId&&row.slot===slot)}
export async function persistWindowRecord(ownerId:string,sessionId:string|null,panel:WindowPanel){const slot=windowSlot(),old=await windowRecord(ownerId,slot);const row:WindowRecord={slot,ownerId,sessionId,panel,parent:old?.parent||initial.get('parent-window'),token:old?.token||initial.get('handoff-token'),updated:Date.now()};await put('windows',JSON.stringify([ownerId,slot]),row);return row}
export async function registerBrowserWindow(row:WindowRecord){await put('windows',JSON.stringify([row.ownerId,row.slot]),row)}
export async function persistWindowDraft(ownerId:string,sessionId:string,draft:Draft){await put('drafts',JSON.stringify([ownerId,windowSlot(),sessionId]),{ownerId,slot:windowSlot(),sessionId,draft:structuredClone(draft)})}
export async function restoreWindowDrafts(ownerId:string){for(const row of await values<{ownerId:string;slot:string;sessionId:string;draft:Draft}>('drafts'))if(row.ownerId===ownerId&&row.slot===windowSlot()&&!sessionDrafts.has(row.sessionId))sessionDrafts.set(row.sessionId,row.draft)}
export function hasUnsentDraft(draft:Draft){return !!draft.text.trim()||!!draft.context?.length||!!draft.attachments?.length}
export async function recoverableWindows(ownerId:string){const drafts=await values<{ownerId:string;slot:string;draft:Draft}>('drafts');const records=(await values<WindowRecord>('windows')).filter(row=>row.ownerId===ownerId&&row.slot!==windowSlot());return records.map(row=>({...row,drafts:drafts.filter(draft=>draft.ownerId===ownerId&&draft.slot===row.slot&&hasUnsentDraft(draft.draft)).length}))}
export async function dropWindowJournal(ownerId:string){const database=await db(),slot=windowSlot();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(['windows','drafts'],'readwrite');tx.objectStore('windows').delete(JSON.stringify([ownerId,slot]));const cursor=tx.objectStore('drafts').openCursor();cursor.onsuccess=()=>{const row=cursor.result;if(row){if(row.value.ownerId===ownerId&&row.value.slot===slot)row.delete();row.continue()}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function bufferCount(ownerId:string,slot:string){const database=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('termx-workspace-buffer-state',2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('slots'))request.result.createObjectStore('slots')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});try{return await new Promise<number>((resolve,reject)=>{const request=database.transaction('slots','readonly').objectStore('slots').get(JSON.stringify([ownerId,slot]));request.onsuccess=()=>resolve(Array.isArray(request.result)?request.result.length:0);request.onerror=()=>reject(request.error)})}finally{database.close()}}
