import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {json,request} from '../lib/api';
import {useAccessLifecycle} from './useAccessLifecycle';
type Policy={retention_days:number;max_bytes:number;max_events:number};
type Result={removed_events:number;retained_events:number;retained_bytes:number;policy:Policy};
export default function AuditRetentionManager({onError}:{onError:(error:unknown)=>void}){
 const [policy,setPolicy]=useState<Policy|null>(null),[busy,setBusy]=useState(false),[result,setResult]=useState<Result|null>(null),[confirmed,setConfirmed]=useState(false);
 const dirty=useRef(false),lifecycle=useAccessLifecycle(()=>{setBusy(false);setConfirmed(false);setResult(null)});
 useEffect(()=>{if(!lifecycle.current())return;let alive=true;const current=lifecycle.capture();const controller=new AbortController();request<Policy>('/auth/admin/audit/retention',{signal:controller.signal}).then(value=>{if(alive&&current()&&!dirty.current)setPolicy(value)}).catch(error=>{if(alive&&current())onError(error)});return()=>{alive=false;controller.abort()}},[onError,lifecycle.refresh]);
 async function apply(save:boolean){if(!policy||busy||!confirmed||!lifecycle.current())return;const current=lifecycle.capture();setBusy(true);try{const value=await request<Result>(save?'/auth/admin/audit/retention':'/auth/admin/audit/prune',json(save?'PUT':'POST',save?policy:{}));if(!current())return;setResult(value);if(save||!dirty.current){setPolicy(value.policy);dirty.current=false}setConfirmed(false)}catch(error){if(current())onError(error)}finally{if(current())setBusy(false)}}
 return <section className="manager-form" aria-label="Audit retention"><h2>Audit retention</h2><p>Audit records contain session and action metadata. Passwords, cookies, tokens and captured output are excluded. Saving these limits immediately removes older or excess records; removal is permanent.</p>{policy?<><label className="manager-field">Keep records for days<Input type="number" min={1} max={3650} value={policy.retention_days} disabled={busy||lifecycle.locked} onChange={e=>{dirty.current=true;setConfirmed(false);setPolicy({...policy,retention_days:Number(e.target.value)})}}/></label><label className="manager-field">Maximum audit bytes<Input type="number" min={65536} max={67108864} value={policy.max_bytes} disabled={busy||lifecycle.locked} onChange={e=>{dirty.current=true;setConfirmed(false);setPolicy({...policy,max_bytes:Number(e.target.value)})}}/></label><label className="manager-field">Maximum audit records<Input type="number" min={100} max={100000} value={policy.max_events} disabled={busy||lifecycle.locked} onChange={e=>{dirty.current=true;setConfirmed(false);setPolicy({...policy,max_events:Number(e.target.value)})}}/></label><label className="manager-choice"><input type="checkbox" checked={confirmed} disabled={busy||lifecycle.locked} onChange={e=>setConfirmed(e.target.checked)}/>I understand that applying retention removes older records.</label><div><Button disabled={busy||lifecycle.locked||!confirmed||Object.values(policy).some(v=>!Number.isInteger(v))} onClick={()=>void apply(true)}>Save limits and prune</Button><Button variant="outline" disabled={busy||lifecycle.locked||!confirmed} onClick={()=>void apply(false)}>Prune with saved limits</Button></div></>:<p role="status">Loading saved audit limits…</p>}{result&&<p role="status">Removed {result.removed_events} records; retained {result.retained_events} records ({result.retained_bytes} bytes). The retention operation is recorded in the audit.</p>}</section>
}
