import {describe,it,expect,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {BrowserAnnotationEditor} from './BrowserContextControls';
const element={index:0,tag:'input',name:'Visible field',type:'text',selector:'html > input:nth-of-type(1)',context_hash:'exact-target',box:{x:1,y:2,width:3,height:4}};
describe('exact browser context comments',()=>{
 it('keeps the original target visible while comparing and resolving with explicit image consent',()=>{const resolve=vi.fn().mockResolvedValue(undefined),compare=vi.fn().mockResolvedValue(undefined);render(<BrowserAnnotationEditor elements={[element]} annotations={[{id:'note',comment:'Before field',stale:false,element,comparisons:[{id:'comparison',same_page:false,target_available:false,changed:true,before:{element,url:'https://before.test'},after:{url:'https://after.test',element:null}}]}]} onSave={vi.fn()} onResolve={resolve} onCompare={compare} busy={false}/>);fireEvent.click(screen.getByRole('button',{name:'Compare current target'}));expect(compare).toHaveBeenCalledWith('note',false);fireEvent.click(screen.getByRole('button',{name:'Capture masked after image'}));expect(compare).toHaveBeenCalledWith('note',true);fireEvent.click(screen.getByRole('button',{name:'Resolve annotation'}));expect(resolve).toHaveBeenCalledWith('note',true);expect(screen.getByText('Before / after · different page')).toBeInTheDocument();expect(screen.getByRole('region',{name:'Exact annotation frame and target'})).toHaveTextContent('exact-target');cleanup()});
 it('requires an explicit element, omits image consent by default, and binds the displayed fingerprint',async()=>{const save=vi.fn().mockResolvedValue(undefined);render(<BrowserAnnotationEditor elements={[element]} annotations={[]} onSave={save} busy={false}/>);fireEvent.change(screen.getByLabelText('Page annotation'),{target:{value:'Inspect this field'}});expect(screen.getByRole('button',{name:'Annotate'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Element to annotate'),{target:{value:element.selector}});fireEvent.click(screen.getByRole('button',{name:'Annotate'}));await waitFor(()=>expect(save).toHaveBeenCalledWith({comment:'Inspect this field',selector:element.selector,context_hash:'exact-target',include_screenshot:false}));cleanup()});
 it('sends a region independently, preserves screenshot opt-in, and displays frozen stale frame references',async()=>{const save=vi.fn().mockResolvedValue(undefined);render(<BrowserAnnotationEditor elements={[element]} annotations={[{id:'old',comment:'Older target',stale:true,document_revision:4,element,frame:{kind:'main'},screenshot:{url:'/owned-masked-frame',redaction:'Masked form fields'}}]} onSave={save} busy={false}/>);fireEvent.change(screen.getByLabelText('Comment target'),{target:{value:'region'}});fireEvent.change(screen.getByLabelText('Annotation region x'),{target:{value:'12'}});fireEvent.change(screen.getByLabelText('Page annotation'),{target:{value:'Inspect this area'}});fireEvent.click(screen.getByRole('checkbox',{name:'Include a masked screenshot reference'}));fireEvent.click(screen.getByRole('button',{name:'Annotate'}));await waitFor(()=>expect(save).toHaveBeenCalledWith({comment:'Inspect this area',region:{x:12,y:0,width:240,height:120},include_screenshot:true}));expect(screen.getByText(/Stale after navigation/)).toBeInTheDocument();expect(screen.getByAltText('Masked snapshot for annotation: Older target')).toHaveAttribute('src','/owned-masked-frame');cleanup()});
});
