import {useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request,json} from '../lib/api';
export interface BrowserDraft{id:string;content:string;parameters:string[];steps:unknown[];test?:{steps_executed:number}}
export default function BrowserSkillEditor({initial,tabs,onError,onClose}:{initial:BrowserDraft;tabs:{id:string;title:string;state:string}[];onError:(e:unknown)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(initial),[content,setContent]=useState(initial.content),[target,setTarget]=useState(''),[params,setParams]=useState<Record<string,string>>({}),[safe,setSafe]=useState(false),[version,setVersion]=useState('1.0.0'),[busy,setBusy]=useState(false),[published,setPublished]=useState(false);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);try{await work()}catch(error){onError(error)}finally{setBusy(false)}};
 return <section className="browser-context" aria-label="Recorded browser skill editor"><div className="browser-actions"><h3>Review recorded skill</h3><Button variant="ghost" onClick={onClose}>Close editor</Button></div><p>These recorded steps convey no current browser authority. Edit instructions, run them against a separate safe tab, then approve the tested version.</p><textarea aria-label="Browser skill instructions" value={content} onChange={event=>{setContent(event.target.value);setSafe(false)}} rows={14}/><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>setDraft(await request<BrowserDraft>('/api/browser/skill-drafts/'+draft.id,json('PATCH',{content}))))}>Save instructions</Button><label>Safe test tab<select value={target} onChange={event=>{setTarget(event.target.value);setSafe(false)}}><option value="">Choose a separate tab</option>{tabs.filter(tab=>tab.state==='human').map(tab=><option key={tab.id} value={tab.id}>{tab.title||tab.id}</option>)}</select></label>{draft.parameters.map(parameter=><Input type="password" key={parameter} aria-label={'Browser test parameter '+parameter} placeholder={'Test value for '+parameter} value={params[parameter]||''} onChange={event=>setParams({...params,[parameter]:event.target.value})}/>)}<label><input type="checkbox" checked={safe} onChange={event=>setSafe(event.target.checked)}/>I own this safe test page and approve replaying the displayed steps.</label><div className="browser-actions"><Button disabled={busy||!target||!safe||content!==draft.content} onClick={()=>void run(async()=>{setDraft(await request<BrowserDraft>('/api/browser/skill-drafts/'+draft.id+'/test',json('POST',{target_tab_id:target,parameters:params,safe_target:true})));setParams({})})}>Test recorded steps</Button><Input aria-label="Browser skill version" value={version} onChange={event=>setVersion(event.target.value)}/><Button disabled={busy||!draft.test||content!==draft.content} onClick={()=>void run(async()=>{await request('/api/browser/skill-drafts/'+draft.id+'/publish',json('POST',{version}));setPublished(true)})}>Approve & activate skill</Button></div>{draft.test&&<p role="status">Executed {draft.test.steps_executed} recorded steps. Changes require another test.</p>}{published&&<p role="status">Activated version {version}.</p>}</section>
}
