import {useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
export type BrowserElement={index:number;tag:string;name:string;type:string|null;selector?:string;context_hash?:string;box:{x:number;y:number;width:number;height:number}};
type AnnotationSnapshot={url?:string;document_revision?:number;element?:BrowserElement|null;screenshot?:{url:string;redaction:string}|null};
export type BrowserAnnotation={id:string;comment:string;stale:boolean;resolved?:boolean;url?:string;document_revision?:number;frame?:unknown;element?:BrowserElement|null;region?:Record<string,number>|null;screenshot?:{url:string;redaction:string}|null;comparisons?:{id:string;same_page:boolean;target_available:boolean;changed:boolean;before:AnnotationSnapshot;after:AnnotationSnapshot}[]};
export function BrowserAnnotationEditor({elements,annotations,onSave,onResolve,onCompare,busy}:{elements:BrowserElement[];annotations:BrowserAnnotation[];onSave:(body:Record<string,unknown>)=>Promise<void>;onResolve?:(id:string,resolved:boolean)=>Promise<void>;onCompare?:(id:string,includeScreenshot:boolean)=>Promise<void>;busy:boolean}){
 const [kind,setKind]=useState('element'),[selector,setSelector]=useState(''),[comment,setComment]=useState(''),[capture,setCapture]=useState(false),[region,setRegion]=useState({x:'0',y:'0',width:'240',height:'120'});
 const [saving,setSaving]=useState(false);
 const element=elements.find(e=>e.selector===selector);
 return <><form className="browser-annotation-editor" onSubmit={e=>{e.preventDefault();setSaving(true);void onSave({comment,include_screenshot:capture,...(kind==='region'?{region:Object.fromEntries(Object.entries(region).map(([key,value])=>[key,Number(value)]))}:{selector,context_hash:element?.context_hash})}).then(()=>setComment('')).catch(()=>{}).finally(()=>setSaving(false))}}>
 <label>Comment target<select aria-label="Comment target" value={kind} onChange={e=>setKind(e.target.value)}><option value="element">Page element</option><option value="region">Viewport region</option></select></label>
 {kind==='element'?<label>Element to annotate<select aria-label="Element to annotate" value={selector} onChange={e=>setSelector(e.target.value)}><option value="">Choose a visible element</option>{elements.filter(e=>e.selector).map(e=><option key={e.index} value={e.selector}>{e.tag} · {e.name||'Unnamed element'} · {e.index+1}</option>)}</select></label>:<fieldset><legend>Region in page pixels · 1440 × 900 viewport</legend>{Object.entries(region).map(([key,value])=><label key={key}>{key}<Input type="number" aria-label={'Annotation region '+key} min={key==='width'||key==='height'?1:0} max={key==='x'||key==='width'?1440:900} value={value} onChange={e=>setRegion(previous=>({...previous,[key]:e.target.value}))}/></label>)}</fieldset>}
 <label>Page annotation<Input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Comment on this exact target" maxLength={2000}/></label>
 <label className="browser-check"><input type="checkbox" checked={capture} onChange={e=>setCapture(e.target.checked)}/> Include a masked screenshot reference</label><p>Form fields, editable content and marked private regions are masked across frames. Review the image before attaching; other page content may still be personal.</p>
 <Button type="submit" disabled={busy||saving||!comment.trim()||(kind==='element'&&!element)}>Annotate</Button></form>
 <div role="group" aria-label="Saved page annotations">{annotations.map(a=><article className="browser-card" key={a.id}><strong>{a.comment}</strong><p>{a.resolved?'Resolved':'Open'} · {a.element?'Element: '+(a.element.name||a.element.tag):a.region?'Region: '+JSON.stringify(a.region):'Page comment'} · Document {a.document_revision}{a.stale?' · Stale after navigation':''}</p><p>{a.url}</p>{a.screenshot&&<details><summary>Review masked screenshot</summary><img className="browser-annotation-image" src={a.screenshot.url} alt={'Masked snapshot for annotation: '+a.comment}/><p>{a.screenshot.redaction}</p></details>}<details><summary>Exact frame and target reference</summary><pre role="region" tabIndex={0} aria-label="Exact annotation frame and target">{JSON.stringify({frame:a.frame,element:a.element,region:a.region},null,2)}</pre></details><div className="browser-actions">{onResolve&&<Button disabled={busy} onClick={()=>void onResolve(a.id,!a.resolved)}>{a.resolved?'Reopen annotation':'Resolve annotation'}</Button>}{onCompare&&<><Button disabled={busy} onClick={()=>void onCompare(a.id,false)}>Compare current target</Button><Button disabled={busy} onClick={()=>void onCompare(a.id,true)}>Capture masked after image</Button></>}</div>{a.comparisons?.map(c=><details key={c.id}><summary>Before / after · {c.same_page?(c.target_available?(c.changed?'target changed':'target unchanged'):'target unavailable'):'different page'}</summary><p>The original reference stays frozen. A matching selector does not prove the same page element after navigation.</p><div className="browser-comparison">{(['before','after'] as const).map(side=><section key={side} aria-label={side+' annotation snapshot'}><h4>{side==='before'?'Before':'After'}</h4><p>{c[side].url} · Document {c[side].document_revision}</p>{c[side].screenshot&&<img className="browser-annotation-image" src={c[side].screenshot!.url} alt={side+' masked snapshot for '+a.comment}/>}<pre role="region" tabIndex={0} aria-label={side+' target reference'}>{JSON.stringify(c[side].element,null,2)}</pre></section>)}</div></details>)}</article>)}</div></>;
}
