import {BrowserAnnotationEditor,type BrowserAnnotation,type BrowserElement} from './BrowserContextControls';
import BrowserSkillEditor,{type BrowserDraft} from './BrowserSkillEditor';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request} from '../lib/api';
import './browser.css';

type Profile={id:string;name:string;project_id:string;ephemeral:boolean};
type Tab={id:string;title:string;url:string;state:string;profile_id:string;project_id:string;document_revision:number;lease_revision:number;recording:boolean;grant_id:string|null;recovered_tab_id?:string;closed_at?:number;created_at?:number};
type Element=BrowserElement;
type Context={tab_id:string;url:string;title:string;elements:Element[];annotations?:Annotation[];frame?:unknown;document_revision:number;lease_revision:number};
type Review={id:string;status:string;decision:string;reason:string;target:string;effect:string;tool_id:string;run_id:string;grant_id?:string;expires_at:number};
type Annotation=BrowserAnnotation;
type Download={id:string;filename:string;size:number;approved:boolean};
export type BrowserSurfaceProps={locked?:boolean;projectId?:string|null;taskId?:string|null;onContext?:(context:unknown)=>void};
const post=(body:unknown):RequestInit=>({method:'POST',body:JSON.stringify(body)});

export function BrowserSurface({projectId,taskId,onContext,locked=false}:BrowserSurfaceProps){
 const [profiles,setProfiles]=useState<Profile[]>([]),[tabs,setTabs]=useState<Tab[]>([]),[selected,setSelected]=useState('');
 const [url,setUrl]=useState(''),[profileId,setProfileId]=useState(''),[profileName,setProfileName]=useState(''),[showProfile,setShowProfile]=useState(false),[profileEphemeral,setProfileEphemeral]=useState(false);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[frame,setFrame]=useState(''),[connected,setConnected]=useState(false);
 const [context,setContext]=useState<Context|null>(null),[showContext,setShowContext]=useState(false),[grantOpen,setGrantOpen]=useState(false);
 const [sites,setSites]=useState(''),[expires,setExpires]=useState('600'),[editAllowed,setEditAllowed]=useState(true),[uploadsAllowed,setUploadsAllowed]=useState(false),[diagnosticsAllowed,setDiagnosticsAllowed]=useState(false),[lifecycleAllowed,setLifecycleAllowed]=useState(false);
 const [reviews,setReviews]=useState<Review[]>([]),[annotations,setAnnotations]=useState<Annotation[]>([]),[downloads,setDownloads]=useState<Download[]>([]),[find,setFind]=useState('');
 const root=useRef<HTMLElement|null>(null);
 const [showHistory,setShowHistory]=useState(false),[history,setHistory]=useState<{id:string;profile_id:string;url:string;title:string;visited_at:number}[]>([]),[showInspector,setShowInspector]=useState(false),[diagnosticEnabled,setDiagnosticEnabled]=useState(false),[diagnosticView,setDiagnosticView]=useState('performance'),[diagnostic,setDiagnostic]=useState<unknown>(null);
 const [skillDraft,setSkillDraft]=useState<BrowserDraft|null>(null);
 const socket=useRef<WebSocket|null>(null),frameURL=useRef(''),surface=useRef<HTMLImageElement|null>(null),input=useRef<HTMLTextAreaElement|null>(null),remoteReturn=useRef<HTMLElement|null>(null);
 const selection=useRef(selected);selection.current=selected;const diagnosticEpoch=useRef(0);
 const activeProject=useRef(projectId||'');activeProject.current=projectId||'';
 const [observationPaused,setObservationPaused]=useState(()=>locked||sessionStorage.getItem('termx-browser-view-paused')==='true');const observationBlocked=useRef(locked||sessionStorage.getItem('termx-browser-view-paused')==='true');
 const [connectionAttempt,setConnectionAttempt]=useState(0),[controlAllowed,setControlAllowed]=useState(true),[viewConnecting,setViewConnecting]=useState(false);
 const tab=tabs.find(t=>t.id===selected),profile=profiles.find(p=>p.id===tab?.profile_id);
 const activeTabs=tabs.filter(t=>t.project_id===(projectId||'') && !['closed','crashed'].includes(t.state));
 const load=useCallback(async()=>{
  const scope=projectId||'';
  const [p,t,r,d]=await Promise.all([request<Profile[]>('/api/browser/profiles'),request<Tab[]>('/api/browser/tabs'),request<Review[]>('/api/browser/reviews'),request<Download[]>('/api/browser/downloads')]);
  if(activeProject.current!==scope)return;
  setProfiles(p);setTabs(t);setReviews(r);setDownloads(d);setProfileId(current=>p.some(x=>x.id===current&&x.project_id===(projectId||''))?current:p.find(x=>x.project_id===(projectId||''))?.id||'');
  setSelected(current=>t.some(x=>x.id===current&&x.project_id===(projectId||'')&&!['closed','crashed'].includes(x.state))?current:t.find(x=>x.project_id===(projectId||'')&&!['closed','crashed'].includes(x.state))?.id||'');
 },[projectId]);
 const run=useCallback(async(job:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await job()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}},[]);
 useEffect(()=>{void run(load);const timer=setInterval(()=>{void load().catch(()=>{})},2500);return()=>clearInterval(timer)},[load,run]);
 useEffect(()=>{setUrl(tab?.state==='private'?'':tab?.url||'');setContext(null);setAnnotations([]);diagnosticEpoch.current++;setDiagnostic(null);setDiagnosticEnabled(false)},[selected,tab?.url,tab?.state,tab?.document_revision]);
 useEffect(()=>{const pause=()=>{sessionStorage.setItem('termx-browser-view-paused','true');observationBlocked.current=true;setObservationPaused(true);setControlAllowed(false);setContext(null);setAnnotations([]);diagnosticEpoch.current++;setDiagnostic(null);setShowContext(false);setGrantOpen(false);socket.current?.close();setFrame('');if(frameURL.current){URL.revokeObjectURL(frameURL.current);frameURL.current=''}};window.addEventListener('termx-locked',pause);if(locked)pause();return()=>window.removeEventListener('termx-locked',pause)},[locked]);
 useEffect(()=>{
  setConnected(false);setFrame('');if(!selected||observationPaused)return;
  let live=true,attempts=0;let timer:ReturnType<typeof setTimeout>|undefined;
  const connect=()=>{if(!live||observationBlocked.current)return;
  setViewConnecting(true);const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/browser/tabs/${encodeURIComponent(selected)}/view`);socket.current=ws;ws.binaryType='blob';
  ws.onopen=()=>{if(live){setConnected(true);setViewConnecting(false)}};
  ws.onmessage=(event)=>{if(!live||observationBlocked.current)return;if(event.data instanceof Blob){const next=URL.createObjectURL(event.data);if(frameURL.current)URL.revokeObjectURL(frameURL.current);frameURL.current=next;setFrame(next)}else{try{const payload=JSON.parse(event.data);if(payload.type==='state'){setTabs(items=>items.map(t=>t.id===payload.tab.id?payload.tab:t));if(typeof payload.can_control==='boolean')setControlAllowed(payload.can_control)}else if(payload.type==='error'||payload.type==='denied'){setError(payload.message||'Browser request failed');if(payload.type==='denied')setControlAllowed(false)}}catch{}}};
  ws.onerror=()=>{if(live)setError('Browser view could not connect. Check the host connection and session.')};
  ws.onclose=event=>{if(!live)return;setConnected(false);setViewConnecting(false);setFrame('');if([4401,4403,4404].includes(event.code))setError(event.reason|| (event.code===4401?'Sign in to resume the browser view.':event.code===4403?'Browser view permission is denied or revoked.':'The built-in tab closed or crashed.'));if(attempts>=5||![1006,1011,4401].includes(event.code))return;const delay=Math.min(5000,250*2**attempts++);timer=setTimeout(()=>{if(event.code===4401)void request('/auth/me').then(()=>connect()).catch(()=>{});else connect()},delay)};
  };connect();
  return()=>{live=false;if(timer)clearTimeout(timer);socket.current?.close();socket.current=null;if(frameURL.current){URL.revokeObjectURL(frameURL.current);frameURL.current=''}};
 },[selected,connectionAttempt,observationPaused]);
 const human=(action:string,args:Record<string,unknown>={})=>{if(observationBlocked.current)return;if(!controlAllowed){setError('Browser control permission is required. You can still view and share permitted context.');return}if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({action,args}));else void run(async()=>{await request(`/api/browser/tabs/${selected}/human`,post({action,args}));await load()})};
 const observe=async()=>{const [value,notes]=await Promise.all([request<Context>(`/api/browser/tabs/${selected}/context`),request<Annotation[]>(`/api/browser/tabs/${selected}/annotations`)]);if(observationBlocked.current||selection.current!==selected)throw new Error('The selected tab changed. Open Page controls again.');setContext(value);setAnnotations(notes);setShowContext(true);return value};
 const createTab=(address?:string)=>run(async()=>{if(!profileId)throw new Error('Create or select a browser profile first.');const value=await request<Tab>('/api/browser/tabs',post({profile_id:profileId,url:address??(url.trim()||'about:blank')}));await load();setSelected(value.id)});
 const closeSelected=()=>run(async()=>{if(!selected)return;await request(`/api/browser/tabs/${selected}`,{method:'DELETE'});await load()});
 const reopen=()=>run(async()=>{const previous=[...tabs].filter(t=>t.project_id===(projectId||'')&&['closed','crashed'].includes(t.state)&&!t.recovered_tab_id).sort((a,b)=>(b.closed_at||b.created_at||0)-(a.closed_at||a.created_at||0))[0];if(!previous)throw new Error('There is no closed built-in tab to reopen.');const value=await request<Tab>(`/api/browser/tabs/${previous.id}/recover`,post({}));await load();setSelected(value.id)});
 useEffect(()=>{const command=(event:Event)=>{const detail=(event as CustomEvent<{command:string;targetSurface?:string}>).detail;if(!root.current||root.current.getBoundingClientRect().width===0||(!root.current.contains(document.activeElement)&&detail?.targetSurface!=='browser'))return;const value=detail?.command;if(value==='browserNew')void createTab('about:blank');else if(value==='browserClose')void closeSelected();else if(value==='browserReopen')void reopen()};window.addEventListener('termx-browser-command',command);window.dispatchEvent(new CustomEvent('termx-browser-ready'));return()=>window.removeEventListener('termx-browser-command',command)});
 const handoff=()=>run(async()=>{if(!taskId)throw new Error('Start a chat task before handing over this tab.');await request(`/api/browser/tabs/${selected}/handoff`,post({run_id:taskId,origins:sites.split(/[\n,]/).map(s=>s.trim()).filter(Boolean),actions:['navigate','observe','capture','click','scroll','wait','find','zoom','history',...(editAllowed?['type']:[]),...(uploadsAllowed?['upload','download']:[]),...(diagnosticsAllowed?['diagnostics']:[]),...(lifecycleAllowed?['open_tab','close_tab']:[])],expires_in:Number(expires)}));setGrantOpen(false);await load()});
 const pending=reviews.filter(r=>r.run_id===taskId&&r.status==='needs_user'&&r.expires_at>Date.now()/1000);
 const inFlight=reviews.some(r=>r.run_id===taskId&&r.status==='executing'&&r.grant_id===tab?.grant_id);
 const allowed=reviews.filter(r=>r.run_id===taskId&&r.status==='completed').length;
 const decision=(id:string,approve:boolean)=>run(async()=>{await request(`/api/browser/reviews/${id}/decision`,post({approve}));await load()});
 const uploadFile=(file:File)=>run(async()=>{if(file.size>10*1024*1024)throw new Error('Choose a file smaller than 10 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));const ref=await request(`/api/browser/tabs/${selected}/uploads`,post({filename:file.name,mime_type:file.type||'application/octet-stream',data_base64:btoa(text)}));onContext?.({type:'approved-browser-upload',file:ref,tab_id:selected})});
 return <section ref={root} className="browser-workspace" aria-label="Built-in browser workspace">{observationPaused&&<div role="status" className="browser-error">Browser view was paused when the workspace locked. <Button onClick={()=>{sessionStorage.removeItem('termx-browser-view-paused');observationBlocked.current=false;setObservationPaused(false);setConnectionAttempt(value=>value+1)}}>Resume browser view</Button></div>}
  <div className="browser-tabstrip">
   <div className="browser-tabs" role="tablist" aria-label="Built-in browser tabs">{activeTabs.map((t,index)=><Button key={t.id} id={'browser-tab-'+t.id} role="tab" aria-controls="managed-browser-page" aria-selected={selected===t.id} tabIndex={selected===t.id?0:-1} variant={selected===t.id?'secondary':'ghost'} onClick={()=>setSelected(t.id)} onKeyDown={event=>{const next=event.key==='ArrowRight'?(index+1)%activeTabs.length:event.key==='ArrowLeft'?(index+activeTabs.length-1)%activeTabs.length:event.key==='Home'?0:event.key==='End'?activeTabs.length-1:-1;if(next<0)return;event.preventDefault();setSelected(activeTabs[next].id);document.getElementById('browser-tab-'+activeTabs[next].id)?.focus()}}>{t.title||'New tab'}</Button>)}</div>
   <Button variant="ghost" aria-label="Open built-in tab" onClick={()=>void createTab('about:blank')} disabled={busy||!profileId}>+</Button>
   <select aria-label="Browser profile" value={profileId} onChange={e=>setProfileId(e.target.value)}>{!profileId&&<option value="">Choose profile</option>}{profiles.filter(p=>p.project_id===(projectId||'')).map(p=><option key={p.id} value={p.id}>{p.name}{p.ephemeral?' · Temporary':''}</option>)}</select>
   <Button variant="ghost" onClick={()=>setShowProfile(!showProfile)}>Profiles</Button><Button variant="ghost" disabled={busy||!tabs.some(t=>t.project_id===(projectId||'')&&['closed','crashed'].includes(t.state)&&!t.recovered_tab_id)} onClick={()=>void reopen()}>Reopen closed tab</Button><Button variant="ghost" onClick={()=>void run(async()=>{setHistory(await request('/api/browser/history'));setShowHistory(value=>!value)})}>History</Button>
  </div>
  {tabs.filter(t=>t.project_id===(projectId||'')&&t.state==='crashed'&&!t.recovered_tab_id).map(t=><div role="alert" className="browser-card" key={t.id}><strong>Browser tab crashed</strong><p>{t.title||'Your tab'} stopped. Reopening creates a new tab in human control; an agent needs a fresh handoff.</p><Button disabled={busy} onClick={()=>void run(async()=>{const value=await request<Tab>(`/api/browser/tabs/${t.id}/recover`,post({}));await load();setSelected(value.id)})}>Reopen crashed tab</Button></div>)}
  {showProfile&&<form className="browser-profile-editor" onSubmit={e=>{e.preventDefault();void run(async()=>{const value=await request<Profile>('/api/browser/profiles',post({project_id:projectId||'',name:profileName,ephemeral:profileEphemeral}));await load();setProfileId(value.id);setProfileName('');setProfileEphemeral(false)})}}>
    <Input aria-label="New profile name" placeholder="New project browser profile" value={profileName} onChange={e=>setProfileName(e.target.value)}/><label className="browser-check"><input type="checkbox" checked={profileEphemeral} onChange={event=>setProfileEphemeral(event.target.checked)}/>Temporary profile · deleted when the host stops or restarts</label><Button type="submit" disabled={busy||!profileName.trim()}>Create profile</Button>
    <Button type="button" variant="ghost" disabled={!profileId||busy} onClick={()=>void run(async()=>{await request(`/api/browser/profiles/${profileId}/clear`,post({}));await load()})}>Clear profile & history</Button>
  </form>}
  <form className="browser-address" onSubmit={e=>{e.preventDefault();if(tab)human('navigate',{url});else void createTab()}}>
   <Button type="button" variant="ghost" aria-label="Go back" disabled={!tab} onClick={()=>human('history',{direction:'back'})}>←</Button><Button type="button" variant="ghost" aria-label="Go forward" disabled={!tab} onClick={()=>human('history',{direction:'forward'})}>→</Button><Button type="button" variant="ghost" aria-label="Reload page" disabled={!tab} onClick={()=>human('history',{direction:'reload'})}>↻</Button>
   <img src="/assets/browser/lock.svg" alt=""/>
   <Input aria-label="Page address" placeholder={tab?.state==='private'?'Private login · address capture paused':'Enter a URL to open in TermX'} value={url} onChange={e=>setUrl(e.target.value)}/><Button type="submit" variant="ghost" disabled={busy}>Go</Button>
   <span className="browser-profile-label">{profile?.name}</span>
  </form>
  {tab&&<div className={`browser-control ${tab.state==='agent'?'active':tab.state==='private'?'private':''}`}>
   <img src="/assets/browser/shield.svg" alt=""/><span>{!controlAllowed?'Watching · browser control unavailable':tab.state==='private'?'Private login · you are in control':pending.length?'Agent paused · approval required':tab.state==='agent'?(inFlight?'Agent is using this tab':'Control granted · waiting for agent'):'You are in control'}</span>
   {tab.state==='agent'?<Button variant="secondary" onClick={()=>void run(async()=>{await request(`/api/browser/tabs/${selected}/takeover`,post({private:false}));await load()})}>Take over</Button>:<Button variant="secondary" disabled={!taskId||!controlAllowed} onClick={()=>{setSites(tab.url==='about:blank'?'':new URL(tab.url).origin);setGrantOpen(true)}}>{tab.state==='private'?'Resume agent':'Let agent use'}</Button>}
   {tab.state!=='private'&&<Button disabled={!controlAllowed} variant="ghost" onClick={()=>void run(async()=>{await request(`/api/browser/tabs/${selected}/takeover`,post({private:true}));setContext(null);await load()})}>Private login</Button>}
   {tab.state==='private'&&<Button disabled={!controlAllowed||busy} variant="ghost" onClick={()=>void run(async()=>{await request(`/api/browser/tabs/${selected}/takeover`,post({private:false}));setContext(null);await load()})}>Finish private login</Button>}
   <Button variant="ghost" disabled={busy||tab.state==='private'} onClick={()=>void run(async()=>{await observe()})}>Ask about page</Button>
   <Button variant="ghost" disabled={!controlAllowed} aria-label="Close selected tab" onClick={()=>void closeSelected()}>Close tab</Button>
   {!taskId&&<span>Start a chat task to hand over this tab.</span>}
  </div>}
  {error&&<div className="browser-error" role="alert">{error}<Button variant="ghost" onClick={()=>void run(load)}>Retry</Button></div>}
  {grantOpen&&<div className="browser-grant" role="dialog" aria-label="Task browser handoff">
    <h3>Let this task use the tab</h3><p>{profile?.name} · Task {taskId?.slice(0,8)}. A handoff allows routine actions inside these exact sites. Consequential actions still require you.</p>
    <label>Approved origins<textarea value={sites} onChange={e=>setSites(e.target.value)} placeholder="https://example.com"/></label>
    <label>Duration<select value={expires} onChange={e=>setExpires(e.target.value)}><option value="300">5 minutes</option><option value="600">10 minutes</option><option value="1800">30 minutes</option><option value="3600">1 hour</option></select></label>
    <label><input type="checkbox" checked={editAllowed} onChange={e=>setEditAllowed(e.target.checked)}/> Edit non-sensitive fields</label><label><input type="checkbox" checked={uploadsAllowed} onChange={e=>setUploadsAllowed(e.target.checked)}/> Approved uploads and downloads</label><label><input type="checkbox" checked={diagnosticsAllowed} onChange={e=>setDiagnosticsAllowed(e.target.checked)}/> Read-only developer diagnostics</label>
    <label><input type="checkbox" checked={lifecycleAllowed} onChange={e=>setLifecycleAllowed(e.target.checked)}/> Open and close tabs inside this grant · closing requires exact review</label><div className="browser-actions"><Button disabled={busy||!sites.trim()||!taskId} onClick={()=>void handoff()}>Hand over & observe</Button><Button variant="ghost" onClick={()=>setGrantOpen(false)}>Cancel</Button></div>
  </div>}
  <div className="browser-main">
   <div className="browser-page" id="managed-browser-page" role={tab?'tabpanel':undefined} aria-labelledby={tab?'browser-tab-'+tab.id:undefined}>
    {frame?<><img ref={surface} src={frame} className="browser-live-view" alt="Live rendered browser page. Use Page controls below for keyboard accessible page content." onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();input.current?.focus();human('click',{x:(e.clientX-r.left)*1440/r.width,y:(e.clientY-r.top)*900/r.height})}} onWheel={e=>human('scroll',{x:e.deltaX,y:e.deltaY})}/><textarea ref={input} disabled={!controlAllowed} data-agent-input="true" tabIndex={-1} className="browser-remote-input" placeholder="Type into page · Escape returns to workspace" aria-label="Type into the focused browser page field. Press Escape to return to page controls." autoComplete="off" onPaste={e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text.length>16000){setError('Paste up to 16,000 characters at a time.');return}if(controlAllowed&&text)human('type',{text});e.currentTarget.value=''}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v')return;if(e.key.length>1||e.metaKey||e.ctrlKey){if(e.key==='Escape'){e.preventDefault();remoteReturn.current?.focus();if(!remoteReturn.current)e.currentTarget.blur();return}e.preventDefault();const modifiers=[e.metaKey?'Meta':'',e.ctrlKey?'Control':'',e.altKey?'Alt':'',e.shiftKey?'Shift':''].filter(Boolean);human('key',{key:[...modifiers,e.key===' '?'Space':e.key].join('+')})}}} onInput={e=>{if(!(e.nativeEvent as InputEvent).isComposing){human('type',{text:e.currentTarget.value});e.currentTarget.value=''}}} onCompositionEnd={e=>{human('type',{text:e.currentTarget.value});e.currentTarget.value=''}}/></>:<div className="browser-empty"><h2>{tab?(viewConnecting?'Connecting browser…':'Browser view stopped'):'Your built-in browser'}</h2><p>{tab?(viewConnecting?'The host is preparing the live page.':'Reconnect the view when you want to watch this tab again.'):'Choose a project profile and open a site to browse here.'}</p><p>Signed-in profiles belong to this workspace. Share page context or hand over a tab when you need the agent.</p>{!profiles.length&&<Button onClick={()=>setShowProfile(true)}>Create a browser profile</Button>}</div>}
    {tab&&<div className="browser-diagnostics"><span>{connected?'Live browser connected':'View disconnected'}</span><Button variant="ghost" disabled={!controlAllowed} onClick={event=>{remoteReturn.current=event.currentTarget;input.current?.focus();human('key',{key:'Tab'})}}>Control page with keyboard</Button>{!connected&&<Button variant="ghost" onClick={()=>setConnectionAttempt(value=>value+1)}>Reconnect view</Button>}<form onSubmit={e=>{e.preventDefault();human('find',{text:find})}}><Input aria-label="Find on page" value={find} onChange={e=>setFind(e.target.value)} placeholder="Find on page"/><Button type="submit" variant="ghost">Find</Button></form><label>Zoom<select aria-label="Page zoom" defaultValue="1" onChange={e=>human('zoom',{zoom:Number(e.target.value)})}><option value="0.75">75%</option><option value="1">100%</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select></label></div>}
   </div>
   <aside className="browser-activity" aria-label="Browser control and review activity">
    {tab?.state==='private'?<><span className="browser-badge attention">Private login</span><h3>I’m paused while you sign in.</h3><p>The agent and Auto Review cannot inspect this page or your inputs during private login.</p><div className="browser-card"><strong>Capture paused</strong><p>Pending permits are revoked. Resume checks the current page again.</p></div></>:<><span className="browser-badge">{tab?.state==='agent'?'Auto Review active':'Human control'}</span><p>{tab?.state==='agent'?'Routine work stays inside this task, tab and site grant.':'Browse here, then choose exactly what to share with your chat.'}</p><div className="browser-card"><strong>{allowed} completed actions</strong><p>Within this task’s approved scope.</p></div></>}
    {pending.map(r=><article className="browser-card browser-approval" key={r.id}><span className="browser-badge attention">Needs your approval</span><h3>{r.effect} · {r.target}</h3><p>{r.reason.replaceAll('_',' ')}</p><code>{r.tool_id}</code><p>This decision applies to this exact current action.</p><Button disabled={busy} onClick={()=>void decision(r.id,true)}>Approve once</Button><Button variant="ghost" disabled={busy} onClick={()=>void decision(r.id,false)}>Deny</Button></article>)}
    <details><summary>Review activity</summary>{reviews.filter(r=>!taskId||r.run_id===taskId).slice(-20).reverse().map(r=><div className="browser-review-row" key={r.id}><span>{r.decision}</span><span>{r.tool_id}<small>{r.reason.replaceAll('_',' ')}</small></span></div>)}{!reviews.length&&<p>No browser decisions yet.</p>}</details>
    {tab&&<><Button variant="ghost" disabled={busy||tab.state==='private'} onClick={()=>void run(async()=>{await observe()})}>Page controls</Button><Button variant="ghost" disabled={tab.state==='private'} onClick={()=>setShowInspector(value=>!value)}>Developer inspector</Button><label className="browser-upload">Approve a file for this tab<input type="file" disabled={tab.state==='private'} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadFile(file);e.target.value=''}}/></label><Button variant="ghost" disabled={tab.state==='private'} onClick={()=>void run(async()=>{await request(`/api/browser/tabs/${selected}/recording`,post({enabled:!tab.recording}));await load()})}>{tab.recording?'Stop recording':'Record safe task steps'}</Button>{<Button variant="ghost" disabled={tab.state==='private'} onClick={()=>void run(async()=>{const draft=await request<BrowserDraft>(`/api/browser/tabs/${selected}/skill-draft`,post({name:'Browser task draft'}));setSkillDraft(draft)})}>Review recorded skill</Button>}</>}
    <details><summary>Downloads</summary>{downloads.map(d=><div key={d.id}>{d.approved?<a href={`/api/browser/downloads/${d.id}`} download>{d.filename}</a>:<span>{d.filename} · awaiting exact export approval</span>}<small>{Math.ceil(d.size/1024)} KiB</small></div>)}{!downloads.length&&<p>No downloads.</p>}</details>
   </aside>
  </div>
  {showHistory&&<section className="browser-context" aria-label="Browser history"><div className="browser-actions"><h3>History · {profiles.find(p=>p.id===profileId)?.name}</h3><Button variant="ghost" disabled={!profileId||busy} onClick={()=>void run(async()=>{await request(`/api/browser/profiles/${profileId}/history`,{method:'DELETE'});setHistory(await request('/api/browser/history'))})}>Clear this profile history</Button><Button variant="ghost" onClick={()=>setShowHistory(false)}>Close history</Button></div>{history.filter(h=>h.profile_id===profileId).sort((a,b)=>b.visited_at-a.visited_at).slice(0,100).map(h=><p key={h.id}><Button variant="ghost" onClick={()=>void createTab(h.url)}>{h.title||h.url}</Button> {h.url} · {new Date(h.visited_at*1000).toLocaleString()}</p>)}</section>}
  {showInspector&&tab&&tab.state!=='private'&&<section className="browser-context" aria-label="Developer browser inspector"><h3>Developer inspector</h3><p>Enable ten minutes of read-only developer observation for this tab. Private login, takeover and policy changes clear the consent. It grants no agent control.</p><div className="browser-inspector-controls"><Button disabled={busy} onClick={()=>void run(async()=>{await request(`/api/browser/tabs/${selected}/diagnostics`,post({enabled:!diagnosticEnabled}));setDiagnosticEnabled(value=>!value);setDiagnostic(null)})}>{diagnosticEnabled?'Stop developer observation':'Enable developer observation'}</Button><label>Inspector view<select aria-label="Inspector view" value={diagnosticView} onChange={e=>{diagnosticEpoch.current++;setDiagnostic(null);setDiagnosticView(e.target.value)}}><option value="dom">DOM</option><option value="console">Console</option><option value="network">Network</option><option value="performance">Performance</option></select></label><Button disabled={!diagnosticEnabled||busy} onClick={()=>void run(async()=>{const epoch=diagnosticEpoch.current;const value=await request(`/api/browser/tabs/${selected}/diagnostics/${diagnosticView}`);if(epoch===diagnosticEpoch.current&&selection.current===selected)setDiagnostic(value)})}>Refresh inspector</Button><Button variant="ghost" onClick={()=>setShowInspector(false)}>Close inspector</Button></div>{diagnostic!==null&&<pre role="region" tabIndex={0} aria-label="Developer diagnostic data">{JSON.stringify(diagnostic,null,2)}</pre>}</section>}
  {skillDraft&&<BrowserSkillEditor initial={skillDraft} tabs={activeTabs.filter(t=>t.id!==selected)} onError={e=>setError(e instanceof Error?e.message:String(e))} onClose={()=>setSkillDraft(null)}/>}
  {showContext&&context&&context.tab_id===selected&&tab?.state!=='private'&&<section className="browser-context" aria-label="Page context preview"><div className="browser-actions"><h3>{context.title}</h3><Button onClick={()=>{onContext?.({type:'browser-context',context:{...context,elements:context.elements.filter(e=>e.name&&e.box.width>0&&e.box.height>0).slice(0,100),annotations:annotations.filter(a=>!a.stale&&!a.resolved)}});setShowContext(false)}}>Attach this context</Button><Button variant="ghost" onClick={()=>setShowContext(false)}>Close</Button></div><p>{context.url} · Document {context.document_revision}. Sharing this snapshot grants no ongoing browser control.</p><div className="browser-elements">{context.elements.filter(e=>e.name&&e.box.width>0&&e.box.height>0).slice(0,100).map(e=><div key={e.index}><span>{e.name}</span>{['a','button','input','select','textarea'].includes(e.tag)&&<Button disabled={!controlAllowed} variant="ghost" onClick={event=>{human('click',e.selector?{selector:e.selector}:{x:e.box.x+e.box.width/2,y:e.box.y+e.box.height/2});if(['input','textarea'].includes(e.tag)){remoteReturn.current=event.currentTarget;input.current?.focus()}}}>Focus {e.tag}</Button>}</div>)}</div><BrowserAnnotationEditor key={selected+':'+context.document_revision} elements={context.elements} annotations={annotations} busy={busy||!controlAllowed} onResolve={async(id,resolved)=>{await run(async()=>{await request(`/api/browser/tabs/${selected}/annotations/${id}/resolve`,post({revision:context.document_revision,resolved}));setAnnotations(await request(`/api/browser/tabs/${selected}/annotations`))})}} onCompare={async(id,include_screenshot)=>{await run(async()=>{await request(`/api/browser/tabs/${selected}/annotations/${id}/compare`,post({revision:context.document_revision,include_screenshot}));setAnnotations(await request(`/api/browser/tabs/${selected}/annotations`))})}} onSave={async body=>{try{await request(`/api/browser/tabs/${selected}/annotations`,post({revision:context.document_revision,...body}));setAnnotations(await request(`/api/browser/tabs/${selected}/annotations`))}catch(error){setError(error instanceof Error?error.message:String(error));throw error}}}/></section>}
 </section>
}
export default BrowserSurface;
