import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {BrowserSurface} from './BrowserSurface';
import {SafetyManager} from './SafetyManager';
import {request} from '../lib/api';
vi.mock('../lib/api',()=>({request:vi.fn()}));
const api=vi.mocked(request);
class Socket {static OPEN=1;static instances:Socket[]=[];readyState=1;onopen?:()=>void;onmessage?:(event:{data:string})=>void;onerror?:()=>void;onclose?:(event:CloseEvent)=>void;binaryType='';constructor(){Socket.instances.push(this);setTimeout(()=>this.onopen?.(),0)}send=vi.fn();close=vi.fn()}
const profile={id:'profile',name:'Project account',project_id:'project',ephemeral:false};
const baseTab={id:'tab',title:'Site fixture',url:'https://site.test/page',state:'human',profile_id:'profile',project_id:'project',document_revision:1,lease_revision:1,recording:false,grant_id:null};
let tab={...baseTab};
beforeEach(()=>{sessionStorage.clear();Socket.instances=[];tab={...baseTab};vi.stubGlobal('WebSocket',Socket);api.mockImplementation(async(path:string,init?:RequestInit)=>{
 if(path==='/api/browser/profiles')return [profile];if(path==='/api/browser/tabs')return [tab];if(path==='/api/browser/reviews'||path==='/api/browser/downloads'||path==='/api/browser/rules')return [];
 if(path==='/api/browser/tabs/tab/takeover'){const body=JSON.parse(String(init?.body));tab={...tab,state:body.private?'private':'human'};return tab;}
 if(path==='/api/browser/tabs/tab/annotations')return [];
 if(path==='/api/browser/tabs/tab/context')return {tab_id:'tab',title:'Site fixture',url:'https://site.test/page',document_revision:1,lease_revision:1,elements:[{index:1,tag:'p',name:'Visible selected context',type:null,box:{x:1,y:1,width:100,height:20}}]};
 if(path==='/api/browser/tabs/tab/recover'){tab={...baseTab,id:'recovered'};return tab;}
 if(path==='/api/browser/tabs/tab/handoff'){tab={...tab,state:'agent'};return {tab};}
 if(path==='/api/browser/reviewer')return {configuration:null,evaluations:[],active:false};if(path==='/auth/me')return {principal:{scopes:[]}};
 throw new Error('Unexpected API '+path)
 })});
afterEach(()=>{cleanup();vi.clearAllMocks();vi.unstubAllGlobals()});
describe('Browser workspace',()=>{
 it('names the retained network pause and releases it only through explicit takeover',async()=>{const original=api.getMockImplementation()!;let restricted=true;api.mockImplementation((path,init)=>path==='/api/browser/tabs'?Promise.resolve([{...baseTab,transport_restricted:restricted}]):path==='/api/browser/tabs/tab/takeover'?(restricted=false,Promise.resolve(baseTab)):original(path,init));render(<BrowserSurface projectId="project" taskId="task"/>);await screen.findByText('Page requests paused · take over to continue');expect(api.mock.calls.some(([path])=>path.endsWith('/takeover'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Take over'}));await screen.findByRole('button',{name:'Let agent use'});expect(api).toHaveBeenCalledWith('/api/browser/tabs/tab/takeover',expect.objectContaining({method:'POST',body:JSON.stringify({private:false})}));expect(api.mock.calls.some(([path])=>path.endsWith('/handoff'))).toBe(false)});
 it('offers only explicit takeover for a blocked manual transaction',async()=>{const original=api.getMockImplementation()!;api.mockImplementation((path,init)=>path==='/api/browser/tabs'?Promise.resolve([{...baseTab,state:'agent',grant_id:'grant'}]):path==='/api/browser/reviews'?Promise.resolve([{id:'manual',status:'blocked',decision:'DENY',reason:'incomplete transaction',target:'https://site.test',effect:'unknown',tool_id:'browser.click',run_id:'task',grant_id:'grant',expires_at:Date.now()/1000+600,human_preview:{source:'host-rendered-target/v1',document_hash:'hash',origin:'https://site.test',profile_id:'profile',profile_name:'Project account',operation:'click',target_label:'Unknown operation',consequence:'The exact effect is unknown.',reason:'Take over manually.',manual_required:true}}]):original(path,init));render(<BrowserSurface projectId="project" taskId="task"/>);await screen.findByRole('region',{name:'Host-observed browser operation'});expect(screen.queryByRole('button',{name:'Approve once'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Take over this operation'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/api/browser/tabs/tab/takeover',expect.objectContaining({method:'POST',body:JSON.stringify({private:false})})));expect(api.mock.calls.some(([path])=>path.endsWith('/handoff')||path.endsWith('/decide'))).toBe(false)});
 it('ends private browsing explicitly without starting a task or granting an agent',async()=>{render(<BrowserSurface projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:'Private login'}));await screen.findByText('I’m paused while you sign in.');expect(screen.getByRole('button',{name:'Resume agent'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Finish private login'}));await screen.findByRole('button',{name:'Let agent use'});expect(api).toHaveBeenCalledWith('/api/browser/tabs/tab/takeover',expect.objectContaining({body:JSON.stringify({private:false})}));expect(api).not.toHaveBeenCalledWith('/api/browser/tabs/tab/handoff',expect.anything())});
 it('keeps toolbar controls outside its tabs and moves focus and selection with arrow keys',async()=>{const original=api.getMockImplementation()!;api.mockImplementation((path,init)=>path==='/api/browser/tabs'?Promise.resolve([tab,{...tab,id:'second',title:'Second page'}]):original(path,init));render(<BrowserSurface projectId="project" taskId="task"/>);const first=await screen.findByRole('tab',{name:'Site fixture'});expect(screen.getByRole('tablist')).not.toContainElement(screen.getByRole('button',{name:'Open built-in tab'}));expect(first).toHaveAttribute('tabindex','0');first.focus();fireEvent.keyDown(first,{key:'ArrowRight'});const second=screen.getByRole('tab',{name:'Second page'});await waitFor(()=>expect(second).toHaveAttribute('aria-selected','true'));expect(second).toHaveFocus();expect(first).toHaveAttribute('tabindex','-1');expect(screen.getByRole('tabpanel')).toHaveAttribute('aria-labelledby',second.id);fireEvent.keyDown(second,{key:'Home'});await waitFor(()=>expect(first).toHaveAttribute('aria-selected','true'));expect(first).toHaveFocus()});
 it('reconnects a transient stream close and stops on permission rejection',async()=>{render(<BrowserSurface projectId="project" taskId="task"/>);await screen.findByRole('button',{name:'Ask about page'});await waitFor(()=>expect(Socket.instances).toHaveLength(1));Socket.instances[0].onclose?.({code:1006} as CloseEvent);await waitFor(()=>expect(Socket.instances).toHaveLength(2));Socket.instances[1].onclose?.({code:4403} as CloseEvent);await new Promise(resolve=>setTimeout(resolve,350));expect(Socket.instances).toHaveLength(2)});
 it('reopens a crashed tab without silently handing it to the task',async()=>{tab={...baseTab,state:'crashed'};render(<BrowserSurface projectId="project" taskId="task"/>);fireEvent.click(await screen.findByRole('button',{name:'Reopen crashed tab'}));await screen.findByRole('button',{name:'Let agent use'});expect(api).toHaveBeenCalledWith('/api/browser/tabs/tab/recover',expect.objectContaining({method:'POST'}));expect(api).not.toHaveBeenCalledWith('/api/browser/tabs/tab/handoff',expect.anything())});

 it('shares only the explicit preview and grants no ongoing control',async()=>{const share=vi.fn();render(<BrowserSurface projectId="project" taskId="task" onContext={share}/>);await screen.findByRole('button',{name:'Ask about page'});fireEvent.click(screen.getByRole('button',{name:'Ask about page'}));await screen.findByText('Visible selected context');expect(share).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Attach this context'}));expect(share).toHaveBeenCalledWith(expect.objectContaining({type:'browser-context'}));expect(api).not.toHaveBeenCalledWith('/api/browser/tabs/tab/handoff',expect.anything())});
 it('private mode removes context and disables page observations',async()=>{render(<BrowserSurface projectId="project" taskId="task"/>);fireEvent.click(await screen.findByRole('button',{name:'Private login'}));await screen.findByText('I’m paused while you sign in.');expect(screen.getByRole('button',{name:'Ask about page'})).toBeDisabled();expect(screen.getByRole('button',{name:'Page controls'})).toBeDisabled();expect(screen.queryByText('Visible selected context')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Resume agent'})).toBeEnabled()});
 it('requires an exact site and explicit task handoff',async()=>{render(<BrowserSurface projectId="project" taskId="task"/>);fireEvent.click(await screen.findByRole('button',{name:'Let agent use'}));expect(screen.getByRole('dialog',{name:'Task browser handoff'})).toBeInTheDocument();expect(screen.getByLabelText('Approved origins')).toHaveValue('https://site.test');expect(api).not.toHaveBeenCalledWith('/api/browser/tabs/tab/handoff',expect.anything());fireEvent.click(screen.getByRole('button',{name:'Hand over & observe'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/api/browser/tabs/tab/handoff',expect.objectContaining({body:expect.stringContaining('"origins":["https://site.test"]')})))});
 it('discards a late context response after the user selects another tab',async()=>{const original=api.getMockImplementation()!;let release!:()=>void;api.mockImplementation((path,init)=>path==='/api/browser/tabs'?Promise.resolve([tab,{...tab,id:'second',title:'Second page'}]):path==='/api/browser/tabs/tab/context'?new Promise(resolve=>{release=()=>resolve({tab_id:'tab',title:'Late old page',url:tab.url,document_revision:1,lease_revision:1,elements:[]})}):original(path,init));render(<BrowserSurface projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:'Ask about page'}));fireEvent.click(screen.getByRole('tab',{name:'Second page'}));release();await screen.findByText('The selected tab changed. Open Page controls again.');expect(screen.queryByRole('region',{name:'Page context preview'})).not.toBeInTheDocument();expect(screen.queryByText('Late old page')).not.toBeInTheDocument()});
 it('clears the old inspector view and ignores an in-flight response after choosing another view',async()=>{const original=api.getMockImplementation()!;let release!:()=>void;api.mockImplementation((path,init)=>path==='/api/browser/tabs/tab/diagnostics'?Promise.resolve({enabled:true}):path==='/api/browser/tabs/tab/diagnostics/performance'?new Promise(resolve=>{release=()=>resolve({performance:'stale-perf'})}):path==='/api/browser/tabs/tab/diagnostics/dom'?Promise.resolve({dom:'actual selected DOM'}):original(path,init));render(<BrowserSurface projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:'Developer inspector'}));fireEvent.click(screen.getByRole('button',{name:'Enable developer observation'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Refresh inspector'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Refresh inspector'}));fireEvent.change(screen.getByLabelText('Inspector view'),{target:{value:'dom'}});release();await waitFor(()=>expect(screen.getByRole('button',{name:'Refresh inspector'})).toBeEnabled());expect(screen.queryByText(/stale-perf/)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Refresh inspector'}));await screen.findByText(/actual selected DOM/);expect(screen.queryByText(/stale-perf/)).not.toBeInTheDocument()});
 it('safety manager shows real empty state and hides administrator configuration',async()=>{render(<SafetyManager/>);await screen.findByText('No actions have been reviewed yet.');expect(screen.queryByRole('button',{name:'Configure'})).not.toBeInTheDocument();expect(screen.getByText('No model evaluations recorded.')).toBeInTheDocument()});
});
it('pastes only explicit clipboard event text into the current human-controlled page and never forwards a host paste shortcut',async()=>{vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn(()=>'/frame.jpg'),revokeObjectURL:vi.fn()}));render(<BrowserSurface projectId="project"/>);await screen.findByRole('button',{name:'Ask about page'});await waitFor(()=>expect(Socket.instances).toHaveLength(1));Socket.instances[0].onmessage?.({data:new Blob(['jpeg'])} as never);const input=await screen.findByRole('textbox',{name:'Type into the focused browser page field. Press Escape to return to page controls.'});fireEvent.keyDown(input,{key:'v',metaKey:true});expect(Socket.instances[0].send).not.toHaveBeenCalled();fireEvent.paste(input,{clipboardData:{getData:(type:string)=>type==='text/plain'?'Explicit user paste':''}});expect(Socket.instances[0].send).toHaveBeenLastCalledWith(JSON.stringify({action:'type',args:{text:'Explicit user paste'}}));fireEvent.paste(input,{clipboardData:{getData:()=> 'x'.repeat(16001)}});await screen.findByText('Paste up to 16,000 characters at a time.');expect(Socket.instances[0].send).toHaveBeenCalledTimes(1);Socket.instances[0].onmessage?.({data:JSON.stringify({type:'state',tab,can_control:false})});await waitFor(()=>expect(input).toBeDisabled());fireEvent.paste(input,{clipboardData:{getData:()=> 'Forbidden paste'}});expect(Socket.instances[0].send).toHaveBeenCalledTimes(1)});

it('clears stream observation on lock and requires an explicit view resume with no automatic handoff',async()=>{vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn(()=>'/frame.jpg'),revokeObjectURL:vi.fn()}));render(<BrowserSurface projectId="project" taskId="task"/>);await screen.findByRole('button',{name:'Ask about page'});await waitFor(()=>expect(Socket.instances).toHaveLength(1));Socket.instances[0].onmessage?.({data:new Blob(['jpeg'])} as never);await screen.findByRole('img',{name:/Live rendered browser page/});fireEvent(window,new Event('termx-locked'));await screen.findByRole('button',{name:'Resume browser view'});expect(screen.queryByRole('img',{name:/Live rendered browser page/})).toBeNull();Socket.instances[0].onmessage?.({data:new Blob(['late'])} as never);await new Promise(resolve=>setTimeout(resolve,50));expect(screen.queryByRole('img',{name:/Live rendered browser page/})).toBeNull();expect(Socket.instances).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Resume browser view'}));await waitFor(()=>expect(Socket.instances).toHaveLength(2));expect(api.mock.calls.some(([path])=>path.endsWith('/handoff'))).toBe(false)});

it('restores a locked-window browser pause after reload without creating a stream or task grant',async()=>{sessionStorage.setItem('termx-browser-view-paused','true');render(<BrowserSurface projectId="project"/>);await screen.findByRole('button',{name:'Resume browser view'});await screen.findByRole('button',{name:'Ask about page'});expect(Socket.instances).toHaveLength(0);fireEvent.click(screen.getByRole('button',{name:'Resume browser view'}));await waitFor(()=>expect(Socket.instances).toHaveLength(1));expect(sessionStorage.getItem('termx-browser-view-paused')).toBeNull();expect(api.mock.calls.some(([path])=>path.endsWith('/handoff'))).toBe(false)});
