import {useCallback,useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {request,json} from '../lib/api';

type Capture={id:string;kind:'window'|'tab'|'computer';state:'private'|'recording'|'preview'|'agent'|'watching'|'control'|'paused'|'developer';stop_allowed:boolean;expired?:boolean};
export default function CaptureStatus({onOpen,onError,enabled=true}:{onOpen:(surface:'browser'|'computer')=>void;onError:(error:unknown)=>void;enabled?:boolean}){
 const [captures,setCaptures]=useState<Capture[]>([]),[unavailable,setUnavailable]=useState(false),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const value=await request<{captures:Capture[]}>('/api/desktop/recording/status');setCaptures(value.captures);setUnavailable(false)},[]);
 useEffect(()=>{if(!enabled){setCaptures([]);return}let live=true,pending=false;const update=async()=>{if(pending)return;pending=true;try{const value=await request<{captures:Capture[]}>('/api/desktop/recording/status');if(live){setCaptures(value.captures);setUnavailable(false)}}catch{if(live)setUnavailable(true)}finally{pending=false}};void update();const timer=setInterval(()=>void update(),2000);window.addEventListener('termx-capture-changed',update);return()=>{live=false;clearInterval(timer);window.removeEventListener('termx-capture-changed',update)}},[enabled]);
 if(!enabled||(!captures.length&&!unavailable))return null;
 const count=(state:Capture['state'])=>captures.filter(row=>row.state===state).length;
 const labels=[count('private')?`${count('private')} private · models paused`:'',captures.some(row=>row.state==='private'&&row.expired)?'Private consent ended · Stop capture to resume models':'',count('agent')?`${count('agent')} agent tab`:'',count('control')?`${count('control')} computer control`:'',count('recording')?`${count('recording')} recording`:'',count('paused')?`${count('paused')} paused capture`:'',count('developer')?`${count('developer')} developer observation`:'',captures.filter(row=>['watching','preview'].includes(row.state)).length?`${captures.filter(row=>['watching','preview'].includes(row.state)).length} watching`:''].filter(Boolean);
 const stop=async()=>{setBusy(true);const stopped:string[]=[];try{for(const row of captures.filter(row=>row.stop_allowed)){if(row.kind==='window')await request(`/api/desktop/recording/captures/${row.id}`,{method:'DELETE'});else if(row.kind==='computer')await request(`/api/desktop/recording/viewers/${row.id}`,{method:'DELETE'});else await request(`/api/browser/tabs/${row.id}/capture/stop`,json('POST',{}));stopped.push(row.id)}}catch(error){onError(error)}finally{if(stopped.length)window.dispatchEvent(new CustomEvent('termx-capture-changed',{detail:{stopped}}));try{await refresh()}catch(error){onError(error)}setBusy(false)}};
 const takeover=async()=>{setBusy(true);try{for(const row of captures.filter(row=>row.state==='agent'&&row.stop_allowed))await request(`/api/browser/tabs/${row.id}/takeover`,json('POST',{private:false}));await refresh()}catch(error){onError(error)}finally{setBusy(false)}};
 return <div className="capture-status" role="group" aria-label="Active capture controls"><span role="status" aria-live="polite">{unavailable?'Capture status unavailable':labels.join(' · ')}</span>{captures.length>0&&<><Button variant="ghost" size="sm" aria-label="Open capture controls" onClick={()=>onOpen(captures.some(row=>row.kind==='computer'||row.kind==='window')?'computer':'browser')}>Open</Button>{count('agent')>0&&<Button variant="ghost" size="sm" disabled={busy||!captures.some(row=>row.state==='agent'&&row.stop_allowed)} onClick={()=>void takeover()}>Take over browser</Button>}<Button variant="ghost" size="sm" disabled={busy||!captures.some(row=>row.stop_allowed)} onClick={()=>void stop()}>Stop capture</Button></>}</div>
}
