import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import Chat from './Chat';
import {sessionDrafts} from '../lib/drafts';
import {request,type Session} from '../lib/api';
vi.mock('../lib/api',()=>({gql:vi.fn(async()=>({engine_models:[]})),request:vi.fn(),json:(method:string,value:unknown)=>({method,body:JSON.stringify(value)})}));
afterEach(()=>{cleanup();sessionDrafts.clear();vi.clearAllMocks()});
const row=(id:string):Session=>({id,title:id,engine:'internal',mode:'ask',pinned:false,archived:false,draft_text:'',revision:1,updated_at:1,scroll:0,turns:[]});
it('preserves and flushes a draft when switching faster than the autosave delay',async()=>{const a=row('a'),b=row('b');vi.mocked(request).mockImplementation(async(path,init)=>{if(path.includes('available-extensions'))return {extensions:[]} as any;const current=path.includes('/a')?a:b;if(init?.method==='PATCH'){Object.assign(current,JSON.parse(init.body as string).changes);current.revision++}return {...current} as any});const props={engines:[],providers:[],onSelect:()=>{},onRefresh:()=>{},onError:()=>{}};const {rerender}=render(<Chat session={{...a}} {...props}/>);fireEvent.change(screen.getByLabelText('Message'),{target:{value:'Unsent work'}});rerender(<Chat session={{...b}} {...props}/>);rerender(<Chat session={{...a}} {...props}/>);expect(screen.getByLabelText('Message')).toHaveValue('Unsent work');await waitFor(()=>expect(a.draft_text).toBe('Unsent work'))});

it('retains unsent text through a real panel unmount and stale metadata remount',async()=>{const a=row('unmount');vi.mocked(request).mockImplementation(async(path,init)=>path.includes('available-extensions')?{extensions:[]} as any:{...a} as any);const props={session:{...a},engines:[],providers:[],onSelect:()=>{},onRefresh:()=>{},onError:()=>{}};const panel=render(<Chat {...props}/>);fireEvent.change(screen.getByLabelText('Message'),{target:{value:'Draft while loading Workbench'}});panel.unmount();render(<Chat {...props}/>);expect(screen.getByLabelText('Message')).toHaveValue('Draft while loading Workbench')});

it('never discards a saved local draft because unrelated metadata advanced the revision',()=>{const a={...row('advanced'),revision:99};sessionDrafts.set(a.id,{text:'Preserve through zoom and layout',saved:'Preserve through zoom and layout',dirty:false,revision:2});render(<Chat session={a} engines={[]} providers={[]} onSelect={()=>{}} onRefresh={()=>{}} onError={()=>{}}/>);expect(screen.getByLabelText('Message')).toHaveValue('Preserve through zoom and layout')});

it('shows reviewable browser refs without metadata in the text and persists/removes them after reload',async()=>{const a=row('context-draft');const item={type:'approved-browser-upload' as const,tab_id:'tab-exact',file:{id:'upload-exact',filename:'notes.txt',sha256:'digest-exact'}};vi.mocked(request).mockImplementation(async(path,init)=>{if(path.includes('available-extensions'))return {extensions:[]} as any;if(path==='/api/runners')return {runners:[]} as any;if(path.includes('runner-agents'))return {accounts:[]} as any;if(init?.method==='PATCH'){Object.assign(a,JSON.parse(init.body as string).changes);a.revision++}return {...a} as any});const props={engines:[],providers:[],onSelect:()=>{},onRefresh:()=>{},onError:()=>{}};const incoming={id:'reference-context-test',sessionId:a.id,text:'',attachments:[],context:[item]};const panel=render(<Chat session={{...a}} incoming={incoming} {...props}/>);expect(screen.getByLabelText('Message')).toHaveValue('');expect(screen.getByText('notes.txt')).toBeVisible();fireEvent.change(screen.getByLabelText('Message'),{target:{value:'Read these notes'}});await waitFor(()=>expect(a.draft_context).toEqual([item]));panel.unmount();sessionDrafts.clear();render(<Chat session={{...a}} incoming={incoming} {...props}/>);expect(screen.getByLabelText('Message')).toHaveValue('Read these notes');expect(screen.getAllByText('notes.txt')).toHaveLength(1);fireEvent.click(screen.getByLabelText('Remove context notes.txt'));await waitFor(()=>expect(a.draft_context).toEqual([]));expect(screen.queryByText('notes.txt')).toBeNull()});

it('submits the exact inspected context refs with the turn',async()=>{const item={type:'browser-context' as const,context:{tab_id:'tab-public',document_revision:3,title:'Docs',url:'https://fixture.invalid'}};const a={...row('context-send'),draft_text:'Read this page',draft_context:[item]};vi.mocked(request).mockImplementation(async(path)=>path.includes('available-extensions')?{extensions:[]} as any:{...a} as any);render(<Chat session={a} engines={[]} providers={[]} onSelect={()=>{}} onRefresh={()=>{}} onError={()=>{}}/>);fireEvent.click(screen.getByLabelText('Send message'));await waitFor(()=>expect(vi.mocked(request).mock.calls.find(([path])=>path.endsWith('/turns'))).toBeDefined());const body=JSON.parse(vi.mocked(request).mock.calls.find(([path])=>path.endsWith('/turns'))![1]!.body as string);expect(body.prompt).toBe('Read this page');expect(body.context).toEqual([item])});

it('preserves a new unsent instruction typed before the previous send response arrives',async()=>{const a={...row('slow-send'),draft_text:'Submitted instruction'};let release:(value:unknown)=>void=()=>{};vi.mocked(request).mockImplementation(async(path)=>path.includes('available-extensions')?{extensions:[]} as any:path.endsWith('/turns')?await new Promise(resolve=>{release=resolve}):{...a} as any);render(<Chat session={a} engines={[]} providers={[]} onSelect={()=>{}} onRefresh={()=>{}} onError={()=>{}}/>);fireEvent.click(screen.getByLabelText('Send message'));fireEvent.change(screen.getByLabelText('Message'),{target:{value:'Next unsent instruction'}});release({id:'submitted-task'});await waitFor(()=>expect(screen.getByLabelText('Message')).toHaveValue('Next unsent instruction'))});
