import {useEffect,useRef,useState} from 'react';
import {Cloud,HardDrive,Network,Server,Trash2} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {json,request,type Project} from '../lib/api';
import {useObservationActive} from '../lib/use-observation-active';
import type {CloudAccount} from './CloudAccounts';
import './cloud-machines.css';

type Choice={id:string;label:string;network?:string;zone?:string};
type Catalog={regions?:Choice[];zones?:Choice[];sizes?:Choice[];images?:Choice[];networks?:Choice[];subnets?:Choice[];volume_types?:Choice[]};
type Volume={size_gb:number;type:string};
type Plan={account_id:string;project_id:string;name:string;region:string;zone:string;size:string;image:string;network_mode:'managed'|'existing';network:string;subnet:string;network_cidr:string;subnet_cidr:string;ssh_cidr:string;public_ip:boolean;allow_sudo:boolean;boot:Volume;volumes:Volume[];cleanup:'manual'|'lifetime'|'after-task';lifetime_hours:number;accept_cost:boolean;trust_machine:boolean};
type Deployment={id:string;provider:string;plan:Plan;status:string;error?:string;cleanup_error?:string;runner_id?:string;expires?:number;resources:{kind:string;name:string;id?:string;state:string}[]};
type Review={id:string;expires:number;plan:Plan;billing:string;cleanup_resources:string[];identity:{account:string}};
const initial:Plan={account_id:'',project_id:'',name:'',region:'',zone:'',size:'',image:'',network_mode:'managed',network:'',subnet:'',network_cidr:'10.42.0.0/16',subnet_cidr:'10.42.1.0/24',ssh_cidr:'',public_ip:true,allow_sudo:false,boot:{size_gb:32,type:''},volumes:[],cleanup:'lifetime',lifetime_hours:1,accept_cost:false,trust_machine:false};
export default function CloudMachines({projectId,projects,onChange}:{projectId:string|null;projects:Project[];onChange:()=>Promise<void>}){
 const [accounts,setAccounts]=useState<CloudAccount[]>([]),[rows,setRows]=useState<Deployment[]>([]),[open,setOpen]=useState(false),[plan,setPlan]=useState<Plan>({...initial,project_id:projectId||''}),[catalog,setCatalog]=useState<Catalog>({}),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<Review|null>(null),[cleanup,setCleanup]=useState<string|null>(null);
 const active=useObservationActive(),requestId=useRef(crypto.randomUUID()),generation=useRef(0);
 const change=<K extends keyof Plan>(key:K,value:Plan[K])=>{setPlan(old=>({...old,[key]:value}));setReview(null);requestId.current=crypto.randomUUID()};
 async function load(){const [next,credentials]=await Promise.all([request<Deployment[]>('/api/cloud/deployments'),request<{accounts:CloudAccount[]}>('/api/cloud/accounts')]);return {next,credentials}}
 useEffect(()=>{if(!active)return;let live=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const value=await load();if(live){setRows(value.next);setAccounts(value.credentials.accounts)}}catch(reason){if(live)setError(String(reason))}finally{pending=false}};void poll();const timer=setInterval(()=>void poll(),3000);return()=>{live=false;clearInterval(timer)}},[active]);
 useEffect(()=>{setPlan(old=>({...old,project_id:projectId||old.project_id}));setReview(null)},[projectId]);
 useEffect(()=>{const epoch=++generation.current;if(!plan.account_id){setCatalog({});return}setLoading(true);setError('');const query=new URLSearchParams({region:plan.region,zone:plan.zone});request<Catalog>('/api/cloud/accounts/'+plan.account_id+'/catalog?'+query).then(value=>{if(epoch!==generation.current)return;setCatalog(value)}).catch(reason=>{if(epoch===generation.current){setCatalog({});setError(String(reason))}}).finally(()=>{if(epoch===generation.current)setLoading(false)});return()=>{generation.current++}},[plan.account_id,plan.region,plan.zone]);
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();const value=await load();setRows(value.next);setAccounts(value.credentials.accounts);await onChange()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
 const choose=(key:'region'|'zone'|'size'|'image'|'network'|'subnet',label:string,options:Choice[]=[],required=true)=><label>{label}<Select aria-label={label} required={required} value={plan[key]} disabled={loading||busy} onChange={event=>{const value=event.target.value;setReview(null);requestId.current=crypto.randomUUID();setPlan(old=>({...old,[key]:value,...(key==='region'?{zone:'',size:'',image:'',network:'',subnet:''}:key==='zone'?{size:'',subnet:''}:key==='network'?{subnet:''}:{})}))}}>{!options.some(option=>option.id==='')&&<option value="">Choose {label.toLowerCase()}</option>}{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</Select></label>;
 const volume=(value:Volume,onChange:(volume:Volume)=>void,label:string)=><div className="cloud-volume"><label>{label} size (GiB)<Input required type="number" min={8} max={16384} value={value.size_gb} onChange={event=>onChange({...value,size_gb:Number(event.target.value)})}/></label><label>{label} type<Select aria-label={label+' type'} required value={value.type} onChange={event=>onChange({...value,type:event.target.value})}><option value="">Choose disk type</option>{catalog.volume_types?.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</Select></label></div>;
 return <section className="cloud-machines" aria-label="Cloud deployments"><div className="creation-heading"><div><span className="machine-eyebrow"><Cloud size={15}/> ON-DEMAND MACHINES</span><h2>Launch a cloud runner</h2><p>Choose its compute, disks and network. TermX provisions the machine, installs its runtime, and tracks cleanup.</p></div><Button onClick={()=>setOpen(!open)}>Create cloud machine</Button></div>
  {error&&<p className="inline-error" role="alert">{error}</p>}
  {open&&<form className="creation-form cloud-launch-form" onSubmit={event=>{event.preventDefault();void act(async()=>setReview(await request<Review>('/api/cloud/preview',json('POST',{...plan,request_id:requestId.current}))))}}>
   <h3><Server size={17}/> Machine configuration</h3>
   {!accounts.length&&<p>Add valid provider authentication in Workspace settings → Cloud accounts, then return here. This list refreshes automatically.</p>}
   <div className="creation-fields"><label>Provider account<Select aria-label="Provider account" required value={plan.account_id} onChange={event=>{setPlan({...initial,project_id:projectId||'',account_id:event.target.value});setReview(null);requestId.current=crypto.randomUUID()}}><option value="">Choose an account</option>{accounts.map(account=><option key={account.id} value={account.id} disabled={!account.authenticated}>{account.name} · {account.provider.toUpperCase()}</option>)}</Select></label><label>Cloud runner name<Input required maxLength={80} value={plan.name} onChange={event=>change('name',event.target.value)} placeholder="Build and test runner"/></label><label>Execution project<Select aria-label="Execution project" required disabled={!!projectId} value={plan.project_id} onChange={event=>change('project_id',event.target.value)}><option value="">Choose a project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</Select></label></div>
   {loading&&<p role="status">Loading available infrastructure from your account…</p>}
   <div className="creation-fields">{choose('region','Region',catalog.regions)}{choose('zone','Availability zone',catalog.zones,accounts.find(account=>account.id===plan.account_id)?.provider!=='azure')}{choose('size','Machine size',catalog.sizes)}{choose('image','Operating system',catalog.images)}</div>
   <h3><HardDrive size={17}/> Volumes</h3>{volume(plan.boot,value=>change('boot',value),'Boot volume')}
   {plan.volumes.map((item,index)=><div key={index} className="cloud-data-volume">{volume(item,value=>change('volumes',plan.volumes.map((old,i)=>i===index?value:old)),'Data volume '+(index+1))}<Button type="button" variant="ghost" aria-label={'Remove data volume '+(index+1)} onClick={()=>change('volumes',plan.volumes.filter((_,i)=>i!==index))}><Trash2 size={16}/></Button></div>)}
   <Button type="button" variant="secondary" disabled={plan.volumes.length>=4} onClick={()=>change('volumes',[...plan.volumes,{size_gb:32,type:plan.boot.type}])}>Add data volume</Button><p>Data volumes are attached as blank disks. Cleanup deletes the boot disk and every data volume created here. Save any results you need before cleanup.</p>
   <h3><Network size={17}/> Network & access</h3><label>Network configuration<Select aria-label="Network configuration" value={plan.network_mode} onChange={event=>change('network_mode',event.target.value as Plan['network_mode'])}><option value="managed">Create a dedicated network and subnet</option><option value="existing">Use an existing network and subnet</option></Select></label>
   {plan.network_mode==='managed'?<div className="creation-fields"><label>Network CIDR<Input required value={plan.network_cidr} onChange={event=>change('network_cidr',event.target.value)}/></label><label>Subnet CIDR<Input required value={plan.subnet_cidr} onChange={event=>change('subnet_cidr',event.target.value)}/></label></div>:<div className="creation-fields">{choose('network','Existing network',catalog.networks)}{choose('subnet','Existing subnet',catalog.subnets?.filter(item=>item.network===plan.network&&(!item.zone||item.zone===plan.zone)))}</div>}
   <label>Allowed SSH source CIDR<Input required value={plan.ssh_cidr} onChange={event=>change('ssh_cidr',event.target.value)} placeholder="Control plane public IP/32, or a trusted network range"/></label><p>Use the egress address of the TermX host. Existing subnets need an outbound route for runtime installation.</p>
   <label className="cloud-check"><input type="checkbox" checked={plan.public_ip} onChange={event=>change('public_ip',event.target.checked)}/><span>Assign a public IP. Private-only machines require an existing subnet with outbound internet access and a route from the control plane.</span></label>
   <label className="cloud-check"><input type="checkbox" checked={plan.allow_sudo} onChange={event=>change('allow_sudo',event.target.checked)}/><span>Allow passwordless sudo for the agent’s SSH account.</span></label>
   <h3>Lifetime & cleanup</h3><div className="creation-fields"><label>Cleanup policy<Select aria-label="Cleanup policy" value={plan.cleanup} onChange={event=>change('cleanup',event.target.value as Plan['cleanup'])}><option value="lifetime">Delete after a time limit</option><option value="after-task">Delete after the first task ends</option><option value="manual">Keep until I clean up</option></Select></label>{plan.cleanup!=='manual'&&<label>{plan.cleanup==='after-task'?'Maximum lifetime':'Lifetime'} (hours)<Input required type="number" min={.25} max={168} step={.25} value={plan.lifetime_hours} onChange={event=>change('lifetime_hours',Number(event.target.value))}/></label>}</div><p>Automatic cleanup runs while the TermX control plane is online. Interrupted operations are reconciled after restart.</p>
   <label className="cloud-check"><input required type="checkbox" checked={plan.trust_machine} onChange={event=>change('trust_machine',event.target.checked)}/><span>Allow agents to use this machine’s SSH account, filesystem, network and the permissions selected above.</span></label>
   <label className="cloud-check"><input required type="checkbox" checked={plan.accept_cost} onChange={event=>change('accept_cost',event.target.checked)}/><span>I authorize provider usage charges for this configuration until cleanup deletes its resources.</span></label>
   <Button type="submit" disabled={busy||loading||!plan.account_id}>Review provisioning</Button>
  </form>}
  {review&&<section className="cloud-review creation-form" aria-label="Review cloud provisioning"><h3>Ready to provision {review.plan.name}</h3><dl className="runner-facts"><div><dt>Cloud account</dt><dd>{review.identity.account}</dd></div><div><dt>Compute</dt><dd>{review.plan.region} · {review.plan.zone||'Regional'} · {review.plan.size}</dd></div><div><dt>Storage</dt><dd>{review.plan.boot.size_gb} GiB boot + {review.plan.volumes.reduce((total,v)=>total+v.size_gb,0)} GiB data</dd></div><div><dt>SSH access</dt><dd>{review.plan.ssh_cidr} · {review.plan.public_ip?'Public IP':'Private IP'} · {review.plan.allow_sudo?'sudo enabled':'Standard user'}</dd></div></dl><p>{review.billing}</p><p>Cleanup: {review.plan.cleanup}{review.plan.cleanup!=='manual'?' · maximum '+review.plan.lifetime_hours+' hours':''}. Managed resources: {review.cleanup_resources.join(', ')}.</p><div className="creation-actions"><Button disabled={busy} onClick={()=>void act(async()=>{await request('/api/cloud/deployments',json('POST',{preview_id:review.id}));setReview(null);setOpen(false);requestId.current=crypto.randomUUID()})}>{busy?'Submitting…':'Create reviewed machine'}</Button><Button variant="ghost" disabled={busy} onClick={()=>setReview(null)}>Back to configuration</Button></div></section>}
  {rows.map(row=><article className="runner-record cloud-deployment" key={row.id}><div className="creation-heading"><div><span className="machine-eyebrow">{row.provider.toUpperCase()} · {row.plan.region}</span><h3>{row.plan.name}</h3></div><span className={'status-badge '+row.status}>{row.status}</span></div><p>{row.plan.size} · {row.plan.boot.size_gb} GiB boot · {row.plan.volumes.length} data volumes · {row.expires?'Cleanup by '+new Date(row.expires*1000).toLocaleString():'Manual cleanup'}</p>{row.error&&<p role="status">{row.error}</p>}{row.cleanup_error&&<p role="alert" className="inline-error">{row.cleanup_error} Cloud resources may still incur charges.</p>}{row.status==='ready'&&<p>Ready for agent work. Select “{row.plan.name}” in your session’s Execution settings.</p>}<details><summary>Provisioned resources · {row.resources.length}</summary><ul>{row.resources.map((resource,index)=><li key={index}>{resource.kind} · {resource.id||resource.name} · {resource.state}</li>)}</ul></details>{row.status!=='deleted'&&<Button variant="secondary" disabled={busy||row.status==='cleaning'} onClick={()=>setCleanup(row.id)}>{row.status==='cleanup-failed'?'Retry cleanup':'Clean up machine'}</Button>}
   {cleanup===row.id&&<div className="machine-review" role="group" aria-label="Review cloud cleanup"><h4>Delete {row.plan.name} and its managed resources?</h4><p>This stops its active task and permanently deletes its VM and disks. Existing networks and subnets selected from your account are preserved.</p><div className="creation-actions"><Button disabled={busy} onClick={()=>void act(async()=>{await request('/api/cloud/deployments/'+row.id+'/cleanup',json('POST',{}));setCleanup(null)})}>Delete managed resources</Button><Button variant="ghost" disabled={busy} onClick={()=>setCleanup(null)}>Cancel</Button></div></div>}
  </article>)}
 </section>;
}
