import {useEffect,useRef,useState} from 'react';
import {Monitor,Shield,Hand,Pause,Play,Keyboard} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request} from '../lib/api';
import WindowRecordingPanel from './WindowRecordingPanel';
import './window-recording.css';
export default function ComputerSurface({onError}:{onError:(error:unknown)=>void}){
 const [connected,setConnected]=useState(false),[started,setStarted]=useState(false),[controlling,setControlling]=useState(false),[paused,setPaused]=useState(false),[frame,setFrame]=useState(''),[text,setText]=useState(''),[fps,setFps]=useState(0),[displays,setDisplays]=useState<{id:string;name?:string;width:number;height:number}[]>([]),[display,setDisplay]=useState('');
 const [recordingOpen,setRecordingOpen]=useState(false);
 const socket=useRef<WebSocket|null>(null),url=useRef(''),surface=useRef<HTMLImageElement>(null),ready=useRef(false);
 const send=(payload:unknown)=>{if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify(payload))};
 useEffect(()=>{if(!started)return;let stopped=false;const open=()=>{const endpoint=new URL('/api/desktop/session',location.href);endpoint.protocol=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(endpoint);ws.binaryType='arraybuffer';socket.current=ws;ws.onopen=()=>{setConnected(true);send({type:'control',view_only:true});send({type:'displays'})};ws.onmessage=event=>{if(event.data instanceof ArrayBuffer){if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(new Blob([event.data],{type:'image/jpeg'}));setFrame(url.current)}else{const message=JSON.parse(event.data);if(message.type==='metrics')setFps(message.fps);if(message.type==='error'||message.type==='denied')onError(new Error(message.message));if(message.type==='displays')setDisplays(message.displays||[]);if(message.type==='hello'){setDisplay(message.selected_display||'');setDisplays(message.displays||[]);setControlling(!message.view_only)}}};ws.onclose=event=>{setConnected(false);setControlling(false);if(!stopped&&event.code===4401)request('/auth/me').then(()=>{if(!stopped)open()}).catch(onError)};};open();const visibility=()=>{if(document.hidden)send({type:'pause'});else if(!paused)send({type:'resume'})};document.addEventListener('visibilitychange',visibility);return ()=>{stopped=true;send({type:'release_all'});socket.current?.close();if(url.current)URL.revokeObjectURL(url.current);document.removeEventListener('visibilitychange',visibility)}},[started]);
 function pointer(event:React.PointerEvent<HTMLImageElement>,action:string){if(!controlling)return;const image=surface.current!;const rect=image.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;send({type:'pointer',action,x,y,button:event.button===2?3:1,down:action==='down'||event.buttons!==0})}
 return <section className="computer-surface"><header><Monitor size={17}/><strong>Computer</strong><Button variant="ghost" onClick={()=>setRecordingOpen(!recordingOpen)}>{recordingOpen?'Close window recorder':'Window capture & skills'}</Button><span className="flex-spacer"/><small>{connected?(controlling?'You are in control':'Watching'):'Capture is stopped'}{fps?' · '+fps+' fps':''}</small>{!started?<Button onClick={()=>setStarted(true)}>Watch this machine</Button>:<><Button variant="outline" onClick={()=>{send({type:'control',view_only:controlling});setControlling(!controlling)}}>{controlling?<Shield size={14}/>:<Hand size={14}/>} {controlling?'Return to watch':'Take control'}</Button><Button variant="ghost" size="icon" aria-label={paused?'Resume capture':'Pause capture'} onClick={()=>{send({type:paused?'resume':'pause'});setPaused(!paused)}}>{paused?<Play size={15}/>:<Pause size={15}/>}</Button><Button variant="ghost" onClick={()=>{setStarted(false);setFrame('');setControlling(false)}}>Stop watching</Button></>}</header>{recordingOpen&&<WindowRecordingPanel onError={onError}/>}<div className="computer-canvas" tabIndex={0} aria-label={controlling?'Remote computer, keyboard control enabled':'Remote computer, watch only'} onKeyDown={event=>{if(controlling){event.preventDefault();send({type:'key',key:event.key,action:'down'})}}} onKeyUp={event=>{if(controlling){event.preventDefault();send({type:'key',key:event.key,action:'up'})}}} onBlur={()=>send({type:'release_all'})}>{frame?<img ref={surface} src={frame} alt="Live remote computer" draggable={false} onPointerDown={event=>pointer(event,'down')} onPointerUp={event=>pointer(event,'up')} onPointerMove={event=>pointer(event,'move')} onContextMenu={event=>event.preventDefault()}/>:<div><Monitor size={40}/><h2>Watch or control your machine</h2><p>Start an explicit capture session to see this machine. Control is a separate permission.</p></div>}</div>{connected&&<footer>{displays.length>0&&<select aria-label="Display" value={display} onChange={event=>{send({type:'display',id:event.target.value});setDisplay(event.target.value)}}>{displays.map(item=><option key={item.id} value={item.id}>{item.name||item.id} · {item.width} × {item.height}</option>)}</select>}<Input aria-label="Type on remote computer" placeholder="Type text on this machine" value={text} disabled={!controlling} onChange={event=>setText(event.target.value)}/><Button disabled={!controlling||!text} onClick={()=>{send({type:'text',data:text});setText('')}}><Keyboard size={15}/>Type text</Button></footer>}</section>
}
