import {useEffect,useRef,useState} from 'react';
import {Play,Square,StepForward,ArrowDownToLine} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {request,json,type Project} from '../lib/api';
type Dap={success?:boolean;body?:Record<string,unknown>;message?:string};
export default function Debugger({project,onError}:{project:Project|null;onError:(error:unknown)=>void}){
 const [language,setLanguage]=useState('python'),[program,setProgram]=useState(''),[lines,setLines]=useState(''),[id,setId]=useState(''),[status,setStatus]=useState('Ready'),[thread,setThread]=useState(1),[events,setEvents]=useState<{id:number;event:string;body?:Record<string,unknown>}[]>([]),[stack,setStack]=useState<{id:number;name:string;line:number;source?:{path:string}}[]>([]),[variables,setVariables]=useState<{name:string;value:string;variablesReference:number}[]>([]),[caps,setCaps]=useState<Record<string,{available:boolean;install:string}>>({});
 const cursor=useRef(0);
 useEffect(()=>{request<typeof caps>('/api/development/debug/adapters').then(setCaps).catch(onError)},[]);
 async function command(command:string,args:Record<string,unknown>={},session=id){const response=await request<Dap>('/api/development/debug/'+session+'/command',json('POST',{command,arguments:args}));if(response.success===false)throw new Error(response.message||'Debug adapter rejected the command');return (response.body||response) as Record<string,unknown>;}
 async function launch(){if(!project)return;try{setStatus('Starting');const session=await request<{id:string}>('/api/development/projects/'+project.id+'/debug',json('POST',{language}));setId(session.id);cursor.current=0;setEvents([]);await command('initialize',{},session.id);const launching=command('launch',{program,stopOnEntry:true},session.id);await command('setBreakpoints',{source:{path:program},breakpoints:lines.split(',').map(value=>Number(value.trim())).filter(value=>Number.isInteger(value)&&value>0).map(line=>({line}))},session.id);await command('configurationDone',{},session.id);await launching;setStatus('Running')}catch(error){setStatus('Needs attention');onError(error)}}
 useEffect(()=>{if(!id)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const data=await request<{events:typeof events;cursor:number;status:string}>('/api/development/debug/'+id+'/events?after='+cursor.current);if(stopped)return;cursor.current=data.cursor;setEvents(previous=>[...previous,...data.events].slice(-500));setStatus(data.status);const stop=data.events.find(event=>event.event==='stopped');if(stop){setThread(Number(stop.body?.threadId)||1);setStatus('Paused');const response=await command('stackTrace',{threadId:Number(stop.body?.threadId)||1});setStack((response.stackFrames||[]) as typeof stack)}}catch(error){if(!stopped)onError(error)}if(!stopped)timer=setTimeout(poll,1000)};void poll();return ()=>{stopped=true;clearTimeout(timer)}},[id]);
 async function inspect(frameId:number){try{const scopes=await command('scopes',{frameId});const scope=(scopes.scopes as {variablesReference:number}[]|undefined)?.[0];if(scope){const result=await command('variables',{variablesReference:scope.variablesReference});setVariables(result.variables as typeof variables)}}catch(error){onError(error)}}
 return <section className="debugger"><div className="debug-toolbar"><Select aria-label="Debug language" value={language} onChange={event=>setLanguage(event.target.value)}><option value="python">Python</option><option value="javascript">JavaScript / TypeScript</option></Select><Input aria-label="Debug program" placeholder="Project program, e.g. src/main.py" value={program} onChange={event=>setProgram(event.target.value)}/><Input aria-label="Breakpoint lines" placeholder="Breakpoints: 12, 24" value={lines} onChange={event=>setLines(event.target.value)}/><Button size="icon" aria-label="Start debugging" disabled={!project||!program||!caps[language]?.available} onClick={launch}><Play size={16}/></Button>{id&&<><Button size="icon" variant="ghost" aria-label="Continue" onClick={()=>command('continue',{threadId:thread}).catch(onError)}><Play size={16}/></Button><Button size="icon" variant="ghost" aria-label="Step over" onClick={()=>command('next',{threadId:thread}).catch(onError)}><StepForward size={16}/></Button><Button size="icon" variant="ghost" aria-label="Step into" onClick={()=>command('stepIn',{threadId:thread}).catch(onError)}><ArrowDownToLine size={16}/></Button><Button size="icon" variant="ghost" aria-label="Stop debugging" onClick={()=>request('/api/development/debug/'+id,json('DELETE')).then(()=>{setId('');setStatus('Stopped')}).catch(onError)}><Square size={16}/></Button></>}</div><small>{status}{!caps[language]?.available?' · '+(caps[language]?.install||'Checking host adapter…'):''}</small><div className="debug-content"><div><h4>Call stack</h4>{stack.map(frame=><button key={frame.id} onClick={()=>inspect(frame.id)}>{frame.name} <small>{frame.source?.path}:{frame.line}</small></button>)}</div><div><h4>Variables</h4>{variables.map(variable=><p key={variable.name}><code>{variable.name}</code> {variable.value}</p>)}</div><div><h4>Output</h4><pre>{events.filter(event=>event.event==='output').map(event=>String(event.body?.output||'')).join('')}</pre></div></div></section>
}
