import {useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {json,request,type Project} from '../lib/api';
import './creation.css';
type Worktree={id:string;path:string;branch:string};
type FileChange={path:string;staged:boolean;index:string;worktree:string};
type Prepared={id:string;operation:string;arguments:Record<string,unknown>;head:string;requires_confirmation:boolean};
type ActionRecord={id:string;operation:string;arguments:string;head:string;status:string;created:number;result:string|null};
type Pull={number:number;title:string;body:string;url:string;state:string;mergeable:string;headRefName:string;baseRefName:string;statusCheckRollup:{name?:string;context?:string;state?:string;status?:string;conclusion?:string;detailsUrl?:string;targetUrl?:string}[];comments:{body:string;url?:string}[];reviews:{body:string;state:string}[]};
export default function Delivery({project,onError,initialWorktreeId}:{project:Project|null;onError?:(error:unknown)=>void;initialWorktreeId?:string|null}){
 const [status,setStatus]=useState<{branch?:string;files:FileChange[]}|null>(null),[trees,setTrees]=useState<Worktree[]>([]),[tree,setTree]=useState(''),[diff,setDiff]=useState(''),[path,setPath]=useState(''),[staged,setStaged]=useState(false),[patch,setPatch]=useState(''),[message,setMessage]=useState(''),[branch,setBranch]=useState(''),[base,setBase]=useState('main'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[number,setNumber]=useState(''),[comment,setComment]=useState(''),[pull,setPull]=useState<Pull|null>(null),[prepared,setPrepared]=useState<Prepared|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [actions,setActions]=useState<ActionRecord[]>([]),[remotes,setRemotes]=useState<string[]>([]),[remote,setRemote]=useState('origin');
 const prefix=project?'/api/development/projects/'+project.id+'/delivery':'';
 const suffix=tree?'?worktree_id='+encodeURIComponent(tree):'';
 async function load(){if(!prefix)return;const data=await request<{status:{branch?:string;files:FileChange[]};worktrees:Worktree[];remotes?:string[]}>(prefix+suffix);setStatus(data.status);setTrees(data.worktrees);setRemotes(data.remotes||[]);if(data.remotes?.length&&!data.remotes.includes(remote))setRemote(data.remotes[0]);setActions(await request<ActionRecord[]>(prefix+'/actions'))}
 useEffect(()=>{setTree(initialWorktreeId||'');setPull(null);setDiff('');setPrepared(null)},[project?.id,initialWorktreeId]);
 useEffect(()=>{void load().catch(report)},[project?.id,tree]);
 function report(reason:unknown){setError(reason instanceof Error?reason.message:String(reason));onError?.(reason)}
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await load()}catch(error){report(error)}finally{setBusy(false)}}
 async function execute(action:Prepared,confirmed=false){const outcome=await request<{status:string;result:any}>(prefix+'/actions/'+action.id+'/execute',json('POST',{confirmed}));if(outcome.status!=='completed')throw new Error(outcome.result?.error||'Outcome '+outcome.status+'. Inspect repository state before starting another action.');setPrepared(null);setNotice(action.operation+' completed');return outcome.result}
 async function prepare(operation:string,args:Record<string,unknown>={}){const action=await request<Prepared>(prefix+'/prepare',json('POST',{operation,arguments:{...args,...(tree?{worktree_id:tree}:{})}}));if(action.requires_confirmation){setPrepared(action);return}return execute(action)}
 async function inspect(path:string,staged=false){setPath(path);setStaged(staged);const data=await request<{diff:string}>(prefix+'/diff?path='+encodeURIComponent(path)+'&staged='+staged+(tree?'&worktree_id='+encodeURIComponent(tree):''));setDiff(data.diff);setPatch(data.diff)}
 async function inspectPull(){if(!/^[1-9]\d*$/.test(number))throw new Error('Enter a pull request number');setPull(await request<Pull>(prefix+'/pulls/'+number))}
 if(!project)return <p>Select a project to inspect delivery.</p>;
 return <section className="delivery-page" aria-label="Git delivery"><div className="creation-heading"><h3>Changes & delivery</h3><Button size="sm" variant="ghost" disabled={busy} onClick={()=>act(load)}>Refresh</Button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<label>Execution checkout<Select value={tree} onChange={event=>{setTree(event.target.value);setPrepared(null);setDiff('')}}><option value="">Project checkout · {status?.branch||project.path}</option>{trees.map(item=><option value={item.id} key={item.id}>{item.branch} · {item.path}</option>)}</Select></label>{tree&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>act(()=>prepare('worktree-remove'))}>Review worktree cleanup</Button>}
 <div className="delivery-files">{status?.files.map(file=><div className="git-row" key={file.path}><button onClick={()=>act(()=>inspect(file.path,file.staged))}>{file.path} · {file.index}/{file.worktree}</button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>act(()=>prepare(file.staged?'unstage':'stage',{paths:[file.path]}))}>{file.staged?'Unstage':'Stage'}</Button></div>)}{status&&!status.files.length&&<p>No uncommitted changes.</p>}</div>
 {diff&&<details open><summary>Diff · {path}{staged?' · staged':''}</summary><pre className="delivery-diff">{diff}</pre><label>Selected patch<textarea aria-label="Selected Git patch" value={patch} onChange={event=>setPatch(event.target.value)}/></label><Button size="sm" disabled={busy||!patch.trim()} onClick={()=>act(()=>prepare('hunk',{patch,stage:!staged}))}>{staged?'Unstage selected patch':'Stage selected patch'}</Button></details>}
 <form onSubmit={event=>{event.preventDefault();void act(()=>prepare('commit',{message}))}}><label>Commit message<Input required value={message} onChange={event=>setMessage(event.target.value)}/></label><Button size="sm" type="submit" disabled={busy||!message.trim()}>Commit staged changes</Button></form><label>Publication remote<Select value={remote} onChange={event=>setRemote(event.target.value)}>{(remotes.length?remotes:['origin']).map(name=><option key={name} value={name}>{name}</option>)}</Select></label><div className="creation-actions"><Button size="sm" variant="outline" disabled={busy} onClick={()=>act(()=>prepare('fetch'))}>Fetch</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>act(()=>prepare('pull'))}>Pull fast forward</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>act(()=>prepare('push',{remote,branch:status?.branch}))}>Review push</Button></div>
 <details><summary>Branches & parallel worktrees</summary><label>Branch name<Input value={branch} onChange={event=>setBranch(event.target.value)} placeholder="codex/my-change"/></label><label>Base ref<Input value={base} onChange={event=>setBase(event.target.value)}/></label><div className="creation-actions"><Button size="sm" disabled={busy||!branch} onClick={()=>act(()=>prepare('branch',{name:branch,create:true}))}>Create branch</Button><Button size="sm" variant="outline" disabled={busy||!branch} onClick={()=>act(()=>prepare('branch',{name:branch,create:false}))}>Switch branch</Button><Button size="sm" variant="outline" disabled={busy||!branch} onClick={()=>act(()=>prepare('worktree-create',{branch,base}))}>Create isolated worktree</Button></div></details>
 <details><summary>Pull request & checks</summary><label>Title<Input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Description<textarea value={body} onChange={event=>setBody(event.target.value)}/></label><p>Head {status?.branch||'current branch'} → {base}. New pull requests start as drafts.</p><Button size="sm" disabled={busy||!title||!status?.branch} onClick={()=>act(()=>prepare('pr-create',{title,body,head:status?.branch,base,draft:true}))}>Review draft PR</Button><label>Pull request number<Input inputMode="numeric" value={number} onChange={event=>setNumber(event.target.value)}/></label><div className="creation-actions"><Button size="sm" variant="outline" disabled={busy||!number} onClick={()=>act(inspectPull)}>Inspect PR & checks</Button><Button size="sm" variant="outline" disabled={busy||!number||!title} onClick={()=>act(()=>prepare('pr-update',{number:Number(number),title,body,base}))}>Review PR update</Button></div>{pull&&<article><a href={pull.url} target="_blank" rel="noreferrer">#{pull.number} {pull.title}</a><p>{pull.state} · {pull.mergeable} · {pull.headRefName} → {pull.baseRefName}</p><ul>{pull.statusCheckRollup?.map((check,index)=><li key={index}>{check.name||check.context}: {check.conclusion||check.state||check.status||'pending'} {(check.detailsUrl||check.targetUrl)&&<a href={check.detailsUrl||check.targetUrl} target="_blank" rel="noreferrer">Details</a>}</li>)}</ul>{pull.comments?.map((item,index)=><p key={index}>{item.body}</p>)}{pull.reviews?.map((item,index)=><p key={index}>{item.state}: {item.body}</p>)}</article>}<label>Review feedback<textarea value={comment} onChange={event=>setComment(event.target.value)}/></label><div className="creation-actions"><Button size="sm" disabled={busy||!number||!comment} onClick={()=>act(()=>prepare('pr-comment',{number:Number(number),body:comment}))}>Review comment</Button><Button size="sm" variant="outline" disabled={busy||!number||!comment} onClick={()=>act(()=>prepare('pr-review',{number:Number(number),body:comment,event:'COMMENT'}))}>Review feedback</Button></div></details>
 {actions.length>0&&<details><summary>Recent delivery operations</summary>{actions.map(action=><div className="creation-actions" key={action.id}><span>{action.operation} · {action.status} · {new Date(action.created*1000).toLocaleTimeString()}</span>{action.status==='prepared'&&<Button size="sm" variant="outline" onClick={()=>{setPrepared({id:action.id,operation:action.operation,arguments:JSON.parse(action.arguments),head:action.head,requires_confirmation:true});setError('')}}>Inspect exact operation</Button>}{action.status==='unknown'&&<span>Outcome uncertain. Inspect the repository and remote before starting a new operation.</span>}</div>)}</details>}
 {prepared&&<div className="delivery-confirm" role="region" aria-label="Exact delivery confirmation"><h4>Confirm {prepared.operation}</h4><p>Checkout HEAD {prepared.head}. This decision applies only to the arguments below.</p><pre>{JSON.stringify(prepared.arguments,null,2)}</pre><Button disabled={busy} onClick={()=>act(()=>execute(prepared,true))}>Confirm this operation</Button><Button variant="ghost" disabled={busy} onClick={()=>setPrepared(null)}>Cancel</Button><Button variant="outline" disabled={busy} onClick={()=>act(async()=>{const record=await request<{status:string;result:string|null}>(prefix+'/actions/'+prepared.id);setNotice('Recorded outcome: '+record.status);if(record.status==='completed'){setPrepared(null);await load()}})}>Reconcile outcome</Button></div>}
 </section>
}
