import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {request} from '../lib/api';

type Row=Record<string,any>;
const send=(value:unknown,method='POST'):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
const query=(scope:string,name:string,projectId:string|null)=>new URLSearchParams({scope,name,...(scope==='project'&&projectId?{project_id:projectId}:{})}).toString();
function exportFile(name:string,value:unknown,text=false){const url=URL.createObjectURL(new Blob([text?String(value):JSON.stringify(value,null,2)],{type:text?'text/markdown':'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function Exact({value,label}:{value:unknown;label:string}){return <pre className="manager-json" role="region" aria-label={label} tabIndex={0}>{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre>}
export function matchesExtensionMetadata(row:Row,search:string){
 const terms=search.normalize('NFKC').trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
 // Only inventory metadata is searchable; credentials and instruction drafts
 // never join a search index or leave their existing lifecycle boundary.
 const value=['id','name','folder','scope','source','path','url','kind','format','version','filename','description','permissions']
  .map(key=>typeof row[key]==='string'?row[key]:Array.isArray(row[key])?row[key].filter((item:unknown)=>typeof item==='string').join(' '):'')
  .join(' ').normalize('NFKC').toLocaleLowerCase();
 return terms.every(term=>value.includes(term));
}
export default function ExtensionManager({data,projectId,onChanged,search=''}:{data:Row;projectId:string|null;onChanged:()=>void;search?:string}){
 const [sources,setSources]=useState<Row>({sources:[]}),[compat,setCompat]=useState<Row[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [scope,setScope]=useState(projectId?'project':'user'),[name,setName]=useState(''),[markdown,setMarkdown]=useState(''),[digest,setDigest]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[versions,setVersions]=useState<Row[]>([]),[conflict,setConflict]=useState<Row|null>(null);
 const [preview,setPreview]=useState<Row|null>(null),[packages,setPackages]=useState<Row[]>([]),[registryId,setRegistryId]=useState(''),[registryName,setRegistryName]=useState(''),[kind,setKind]=useState('public_https'),[location,setLocation]=useState(''),[credential,setCredential]=useState(''),[rotating,setRotating]=useState<Row|null>(null),[rotatingCredential,setRotatingCredential]=useState('');
 const [bundle,setBundle]=useState(''),[format,setFormat]=useState('termx-bundle/v1'),[version,setVersion]=useState('1'),[rollback,setRollback]=useState<Row|null>(null),[rollbackDigest,setRollbackDigest]=useState('');
 const epoch=useRef(0);
 async function refresh(){const generation=epoch.current;const q=projectId?'?project_id='+encodeURIComponent(projectId):'';const [source,legacy]=await Promise.all([request<Row>('/api/workspace/skill-sources'+q),request<Row>('/api/workspace/skill-sources/compatibility'+q)]);if(generation===epoch.current){setSources(source);setCompat(legacy.sources)}}
 useEffect(()=>{epoch.current++;setLoaded(false);setName('');setMarkdown('');setDigest(null);setVersions([]);setConflict(null);setPreview(null);setScope(projectId?'project':'user');void refresh().catch(e=>setError(String(e.message||e)));return()=>{epoch.current++}},[projectId]);
 async function act(fn:()=>Promise<unknown>,message:string,refreshAll=false){if(busy)return;const generation=epoch.current;setBusy(true);setError('');try{const result=await fn();if(generation===epoch.current){setNotice(message);if(refreshAll){onChanged();await refresh()}}return result}catch(e:any){if(generation===epoch.current)setError(e.message||String(e));return null}finally{setBusy(false)}}
 async function inspect(row:Row){const params=query(row.scope,row.folder,projectId);const [source,history]=await Promise.all([request<Row>('/api/workspace/skill-sources/source?'+params),request<Row>('/api/workspace/skill-sources/versions?'+params)]);setScope(row.scope);setName(row.folder);setMarkdown(source.markdown);setDigest(source.digest);setLoaded(true);setVersions(history.versions);setConflict(null)}
 const sourceBody=()=>({scope,name,markdown,expected_digest:digest,project_id:scope==='project'?projectId:null});
 const filtered=(rows:Row[])=>rows.filter(row=>matchesExtensionMetadata(row,search));
 const visibleSources=filtered(sources.sources||[]),visibleCompatibility=filtered(compat),visibleBundles=filtered(data.extensions||[]),visibleRegistries=filtered(data.registries||[]),visiblePackages=filtered(packages);
 return <div className="extension-manager">
 <h2>Plugins &amp; skills</h2>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {search.trim()&&<p role="status">Search matches: {visibleSources.length} skill sources, {visibleCompatibility.length} compatibility sources, {visibleBundles.length} bundles, {visibleRegistries.length} registries and {visiblePackages.length} loaded packages. Current drafts and reviews stay open.</p>}
 <details open><summary>Skill sources</summary><p className="manager-help">Edit native SKILL.md files. Publishing creates an immutable permission review; saving a source does not enable a plugin.</p><p>{sources.precedence}</p>
 {(sources.roots||[]).map((root:Row)=><p key={root.scope}><strong>{root.scope==='user'?'Global .agents':'Project .agents'}</strong> <code>{root.path}</code></p>)}
 {visibleSources.map((row:Row)=><article className="manager-item" key={row.scope+row.folder}><div><h3>{row.name||row.folder}</h3><p>{row.scope} · {row.folder} · {row.effective_for_publish?'Effective for publish':`Overridden by ${row.overridden_by?.scope}`} · {row.bytes} bytes</p></div><Button disabled={busy} onClick={()=>void act(()=>inspect(row),'Skill source opened')}>Edit source</Button></article>)}
 {(sources.diagnostics||[]).map((row:Row,i:number)=><p key={i} role="status">{row.scope} {row.folder}: {row.message}</p>)}
 <div className="manager-form"><label className="manager-field"><span>Skill scope</span><Select aria-label="Skill scope" value={scope} onChange={e=>{setScope(e.target.value);setDigest(null);setLoaded(false);setVersions([])}}><option value="user">Global .agents</option>{projectId&&<option value="project">Selected project .agents</option>}</Select></label>
 <label className="manager-field"><span>Skill folder name</span><Input value={name} onChange={e=>{setName(e.target.value);setLoaded(false);setDigest(null);setVersions([])}} placeholder="inspect-source"/></label>
 <label className="manager-field"><span>Skill instructions</span><textarea aria-label="Skill instructions" value={markdown} onChange={e=>{setMarkdown(e.target.value);setLoaded(false)}} rows={10}/></label>
 <label className="manager-field"><span>Import SKILL.md</span><input type="file" disabled={busy} accept=".md,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(!file)return;void act(async()=>{if(file.size>512000)throw new Error('Skill import exceeds 512,000 bytes');setMarkdown(await file.text());setLoaded(false);setNotice('Imported draft; validate and save before publishing')},'Imported draft');e.target.value=''}}/></label>
 <div className="manager-item-actions"><Button disabled={busy||!name||!markdown} onClick={()=>void act(()=>request('/api/workspace/skill-sources/validate',send(sourceBody())),'Skill metadata and instructions validated')}>Validate skill</Button>
 <Button disabled={busy||!name||!markdown} onClick={()=>void act(async()=>{try{const saved=await request<Row>('/api/workspace/skill-sources/source',send(sourceBody(),'PUT'));setDigest(saved.digest);setLoaded(true);const history=await request<Row>('/api/workspace/skill-sources/versions?'+query(scope,name,projectId));setVersions(history.versions);setConflict(null);return saved}catch(e){try{setConflict(await request<Row>('/api/workspace/skill-sources/source?'+query(scope,name,projectId)))}catch{}throw e}},'Skill source saved',true)}>Save source</Button>
 <Button disabled={busy||!loaded} onClick={()=>void act(async()=>{const source=await request<Row>('/api/workspace/skill-sources/source?'+query(scope,name,projectId));exportFile('SKILL.md',source.markdown,true)},'Current native source exported')}>Export source</Button></div>
 {conflict&&<article className="manager-preview"><h3>Source changed on disk</h3><p>Your draft is preserved. Compare the current file before saving.</p><Exact label="Current skill source" value={conflict.markdown}/><Button onClick={()=>{setDigest(conflict.digest);setLoaded(false);setConflict(null);setNotice('Current revision selected; your draft remains for explicit save')}}>Use current revision with my draft</Button><Button onClick={()=>{setMarkdown(conflict.markdown);setDigest(conflict.digest);setConflict(null)}}>Load current file</Button></article>}
 <details><summary>Immutable version history</summary>{versions.map(row=><article className="manager-item" key={row.id}><p>{new Date(row.created_at*1000).toLocaleString()} · {row.digest.slice(0,16)}</p><Button disabled={busy} onClick={()=>void act(async()=>{const saved=await request<Row>('/api/workspace/skill-sources/versions/'+row.id);setMarkdown(saved.markdown);setLoaded(false)},'Earlier version loaded as an unsaved draft')}>Restore as draft</Button></article>)}</details>
 <label className="manager-field"><span>Published skill version</span><Input aria-label="Published skill version" value={version} onChange={e=>setVersion(e.target.value)}/></label><Button disabled={busy||!loaded} onClick={()=>void act(async()=>setPreview(await request('/api/workspace/skill-sources/publish-preview',send({scope,name,version,project_id:scope==='project'?projectId:null}))),'Skill permission review ready')}>Review skill publication</Button>
 </div><details><summary>Compatibility discovery · read-only</summary><p>Compatibility files remain untrusted. Importing copies a draft into the selected managed scope; it does not enable execution.</p>{visibleCompatibility.map(row=><article className="manager-item" key={row.id}><div><h3>{row.name||row.folder}</h3><p>{row.source} · {row.path}</p></div><Button disabled={busy} onClick={()=>void act(async()=>{const source=await request<Row>('/api/workspace/skill-sources/compatibility/'+row.id+(projectId?'?project_id='+encodeURIComponent(projectId):''));setName(source.folder);setMarkdown(source.markdown);setDigest(null);setLoaded(false);setVersions([])},'Compatibility source imported as a draft')}>Import as draft</Button></article>)}</details></details>
 <details><summary>Installed immutable bundles</summary>{visibleBundles.map((row:Row)=><article className="manager-item" key={row.id}><div><h3>{row.id} · {row.version}</h3><p>{row.permissions.join(', ')||'No extra permissions'}</p></div><div className="manager-item-actions"><Button disabled={busy} onClick={()=>void act(async()=>exportFile(row.id+'.json',await request('/api/workspace/extensions/'+row.id+'/export')),'Bundle exported')}>Export bundle</Button><Button onClick={()=>{setRollback(row);setRollbackDigest('')}}>Review rollback</Button><Button disabled={busy} onClick={()=>void act(()=>request('/api/workspace/extensions/'+row.id,{method:'DELETE'}),'Bundle removed',true)}>Remove bundle</Button></div></article>)}
 {rollback&&<div className="manager-form"><label>Earlier bundle digest<Input value={rollbackDigest} onChange={e=>setRollbackDigest(e.target.value)}/></label><Button disabled={busy||!rollbackDigest} onClick={()=>void act(async()=>setPreview(await request('/api/workspace/extensions/'+rollback.id+'/rollback-preview',send({digest:rollbackDigest}))),'Rollback permission review ready')}>Preview rollback</Button></div>}</details>
 <details><summary>Import portable bundle</summary><div className="manager-form"><label>Bundle manifest<textarea value={bundle} onChange={e=>setBundle(e.target.value)} rows={6}/></label><label>Compatibility format<Select aria-label="Compatibility format" value={format} onChange={e=>setFormat(e.target.value)}>{(data.formats||['termx-bundle/v1']).map((f:string)=><option key={f}>{f}</option>)}</Select></label><Button disabled={busy||!bundle} onClick={()=>void act(async()=>setPreview(await request('/api/workspace/extensions/preview',send({data:JSON.parse(bundle),format}))),'Bundle permission review ready')}>Review bundle</Button></div></details>
 <details><summary>Public &amp; private registries</summary><form className="manager-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const secret=credential;setCredential('');return request('/api/workspace/registries',send({name:registryName,kind,...(kind==='private_local'?{path:location}:{url:location}),...(kind==='private_https'?{credential:secret}:{})}))},'Registry registered',true)}}>
 <label>Registry name<Input value={registryName} onChange={e=>setRegistryName(e.target.value)} required/></label><label>Registry adapter<Select aria-label="Registry adapter" value={kind} onChange={e=>{setKind(e.target.value);setCredential('');setLocation('')}}><option value="public_https">Public HTTPS</option><option value="private_https">Private authenticated HTTPS</option><option value="private_local">Private local folder</option></Select></label><label>{kind==='private_local'?'Registry folder':'HTTPS index URL'}<Input value={location} onChange={e=>setLocation(e.target.value)} required type={kind==='private_local'?'text':'url'}/></label>{kind==='private_https'&&<label>Registry credential<Input type="password" autoComplete="off" value={credential} onChange={e=>setCredential(e.target.value)} required/></label>}<Button type="submit" disabled={busy}>Add registry</Button><p>Verified HTTPS, public DNS, same-origin downloads, bounded JSON. Credentials stay in the host credential store.</p></form>
 {visibleRegistries.map((row:Row)=><article className="manager-item" key={row.id}><div><h3>{row.name}</h3><p>{row.kind} · {row.url||row.path}</p></div><Button disabled={busy} onClick={()=>void act(async()=>{const result=await request<Row>('/api/workspace/registries/'+row.id+'/packages');setRegistryId(row.id);setPackages(result.packages)},'Registry packages loaded')}>Browse packages</Button>{row.kind==='private_https'&&<Button onClick={()=>{setRotating(row);setRotatingCredential('')}}>Rotate credential</Button>}</article>)}
 {rotating&&<form className="manager-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const secret=rotatingCredential;setRotatingCredential('');const result=await request('/api/workspace/registries/'+rotating.id+'/credential',send({credential:secret,revision:rotating.revision},'PATCH'));setRotating(null);return result},'Credential rotated; previous package reviews invalidated',true)}}><label>New registry credential<Input type="password" value={rotatingCredential} onChange={e=>setRotatingCredential(e.target.value)} autoComplete="off" required/></label><Button disabled={busy} type="submit">Save registry credential</Button></form>}
 {visiblePackages.map(row=><article className="manager-item" key={row.filename}><div><h3>{row.id} · {row.version}</h3><p>{(row.permissions||[]).join(', ')}</p></div><Button disabled={busy} onClick={()=>void act(async()=>setPreview(await request('/api/workspace/registries/'+registryId+'/preview',send({filename:row.filename}))),'Downloaded package ready for review')}>Review package</Button></article>)}</details>
 {preview&&<article className="manager-preview"><h3>Review {preview.bundle.id} · {preview.bundle.version}</h3><p>Added permissions: {preview.permission_diff.added.join(', ')||'none'}</p><p>Removed permissions: {preview.permission_diff.removed.join(', ')||'none'}</p>{(preview.dependencies||[]).map((dep:Row)=><p key={dep.id}>{dep.id} · {dep.version} · {dep.satisfied?'Exact version installed':'Required version missing'}</p>)}<details><summary>Exact provenance, digests &amp; files</summary><Exact label="Reviewed extension provenance and files" value={{provenance:preview.provenance,digest:preview.digest,bundle:preview.bundle,dependencies:preview.dependencies}}/></details><Button disabled={busy||(preview.dependencies||[]).some((row:Row)=>!row.satisfied)} onClick={()=>void act(async()=>{const installed=await request('/api/workspace/extension-previews/'+preview.id+'/install',send({digest:preview.digest}));setPreview(null);return installed},'Reviewed immutable version installed',true)}>Install reviewed version</Button></article>}
 </div>
}
