import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '../components/ui/dialog';
import {json,request,type Session} from '../lib/api';

type Preview={id:string;digest:string;transfer:unknown};
export default function ForkContextDialog({session,engine,onClose,onCreated,onError,onHistory}:{session:Session;engine:string;onClose:()=>void;onCreated:(id:string)=>void;onError:(error:unknown)=>void;onHistory?:()=>void}){
 const [chosen,setChosen]=useState<string[]>(()=>session.turns?.map(turn=>turn.id)||[]),[files,setFiles]=useState(''),[summary,setSummary]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const epoch=useRef(0),flight=useRef(false);
 useEffect(()=>{const lock=()=>{epoch.current++;flight.current=false;setBusy(false);setLocked(true);setPreview(null)},unlock=()=>setLocked(false);window.addEventListener('termx-locked',lock);window.addEventListener('termx-signed-out',lock);window.addEventListener('termx-session-unlocked',unlock);return()=>{epoch.current++;window.removeEventListener('termx-locked',lock);window.removeEventListener('termx-signed-out',lock);window.removeEventListener('termx-session-unlocked',unlock)}},[]);
 const paths=[...new Set(files.split('\n').map(path=>path.trim()).filter(Boolean))];
 const valid=paths.length<=20&&summary.length<=64000&&chosen.length<=10000;
 async function review(){if(flight.current||locked||!valid)return;const current=epoch.current;flight.current=true;setBusy(true);try{const result=await request<Preview>('/api/workspace/sessions/'+session.id+'/fork-preview',json('POST',{engine,turn_ids:chosen,files:paths,summary}));if(epoch.current===current)setPreview(result)}catch(error){if(epoch.current===current)onError(error)}finally{if(epoch.current===current){flight.current=false;setBusy(false)}}}
 async function commit(){if(!preview||flight.current||locked)return;const current=epoch.current;flight.current=true;setBusy(true);try{const result=await request<Session>('/api/workspace/fork-previews/'+preview.id+'/commit',json('POST',{digest:preview.digest,provider_id:session.provider_id}));if(epoch.current===current)onCreated(result.id)}catch(error){if(epoch.current===current)onError(error)}finally{if(epoch.current===current){flight.current=false;setBusy(false)}}}
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent><DialogTitle>Continue with {engine}</DialogTitle><DialogDescription>Choose messages, project files and a summary, then review the exact context before creating a linked conversation. Native session state and hidden memory do not transfer.</DialogDescription>
 {preview?<><pre role="region" className="context-preview" tabIndex={0} aria-label="Context transfer preview">{JSON.stringify(preview.transfer,null,2)}</pre><Button disabled={busy||locked} onClick={()=>setPreview(null)}>Edit transferred context</Button><Button disabled={busy||locked} onClick={()=>void commit()}>Create linked fork</Button></>:<>
 <fieldset disabled={busy||locked}><legend>Messages to transfer</legend><div className="context-preview">{(session.turns||[]).map(turn=><label key={turn.id} style={{display:'block',minHeight:32}}><input type="checkbox" checked={chosen.includes(turn.id)} onChange={event=>setChosen(value=>event.target.checked?[...value,turn.id]:value.filter(id=>id!==turn.id))}/>{turn.prompt.slice(0,160)||'Empty message'}{turn.task?.result&&' · includes reply'}</label>)}</div>{session.hasEarlier&&<Button variant="outline" onClick={onHistory}>Load earlier messages to choose</Button>}<label style={{display:'block'}}>Project files to transfer<textarea className="input" style={{height:96,resize:"vertical"}} aria-label="Project files to transfer" value={files} onChange={event=>setFiles(event.target.value)} maxLength={20000} placeholder="One relative project path per line" disabled={!session.cwd}/></label><p>Up to 20 UTF-8 files, each at most 256 KB. The host checks project permissions and excludes credentials.</p><label style={{display:'block'}}>Transfer summary<textarea className="input" style={{height:96,resize:"vertical"}} aria-label="Transfer summary" value={summary} onChange={event=>setSummary(event.target.value)} maxLength={64000}/></label></fieldset>
 {!valid&&<p role="alert">Choose at most 20 files and 10,000 messages.</p>}<Button disabled={busy||locked||!valid} onClick={()=>void review()}>Preview transferred context</Button></>}
 </DialogContent></Dialog>
}
