import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request} from '../lib/api';

export type CodingPolicy={id:string;version:number;effect:'allow'|'deny';scope_type:string;scope_id:string;display:string;tool:string;expires_at:number|null;revoked:boolean;editable:boolean;policy_source:string;binding:Record<string,unknown>;[key:string]:unknown};
export function GeneralPolicyManager(){
 const [rows,setRows]=useState<CodingPolicy[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');const epoch=useRef(0),activeWrite=useRef<symbol|null>(null);
 const load=useCallback(async()=>{const generation=++epoch.current;try{const result=await request<{rules:CodingPolicy[]}>('/api/workspace/coding-policies');if(generation===epoch.current){setRows(result.rules);setError('')}}catch(error){if(generation===epoch.current)setError(error instanceof Error?error.message:'Policies unavailable.')}},[]);
 useEffect(()=>{void load();const invalidate=()=>{epoch.current++;activeWrite.current=null;setRows(null);setBusy(false);setError('Workspace observation paused. Unlock and refresh to inspect current policies.')};const resume=()=>{void load()};window.addEventListener('termx-locked',invalidate);window.addEventListener('termx-session-unlocked',resume);return()=>{epoch.current++;window.removeEventListener('termx-locked',invalidate);window.removeEventListener('termx-session-unlocked',resume)}},[load]);
 const run=async(action:()=>Promise<unknown>)=>{if(activeWrite.current)return;const token=Symbol();activeWrite.current=token;const generation=epoch.current;setBusy(true);setError('');try{await action();if(generation===epoch.current)await load()}catch(error){if(generation===epoch.current)setError(error instanceof Error?error.message:'Policy update failed.')}finally{if(activeWrite.current===token){activeWrite.current=null;setBusy(false)}}};
 return <section aria-label="Coding action policies"><h3>Coding action policies</h3><p>Sandbox impossibility and host restrictions apply first. Matching denies override every remembered allow. Your remembered rules keep their principal, policy version, exact operation and target; they never grant broader filesystem, network or budget authority.</p><Input aria-label="Search coding policies" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search operation or policy source"/><Button variant="ghost" disabled={busy} onClick={()=>void load()}>Refresh coding policies</Button>{error&&<p role="alert">{error}</p>}{rows===null?<p>Loading coding policies…</p>:!rows.length?<p>No coding action policies recorded. Scope choices appear on eligible task approvals.</p>:rows.filter(row=>JSON.stringify([row.display,row.tool,row.policy_source,row.scope_type]).toLowerCase().includes(query.toLowerCase())).map(row=><CodingRule key={row.id+':'+row.version} row={row} busy={busy} save={(effect,seconds)=>run(()=>request(`/api/workspace/coding-policies/${encodeURIComponent(row.id)}`,{method:'PATCH',body:JSON.stringify({version:row.version,effect,expires_in:seconds})}))} revoke={()=>run(()=>request(`/api/workspace/coding-policies/${encodeURIComponent(row.id)}`,{method:'DELETE',body:JSON.stringify({version:row.version})}))}/>)}</section>
}
function CodingRule({row,busy,save,revoke}:{row:CodingPolicy;busy:boolean;save:(effect:string,seconds:number)=>Promise<void>;revoke:()=>Promise<void>}){
 const [editing,setEditing]=useState(false),[effect,setEffect]=useState(row.effect),[seconds,setSeconds]=useState('3600');const expired=row.expires_at!==null&&row.expires_at*1000<=Date.now();
 return <article className="safety-rule" aria-label={'Coding policy '+row.id}><strong>{row.effect==='deny'?'Denied':'Allowed'} · {row.tool}</strong><p>{row.display}</p><small>{row.policy_source} · {row.scope_type} · {row.revoked?'Revoked':expired?'Expired':row.expires_at?`Expires ${new Date(row.expires_at*1000).toLocaleString()}`:'Host-managed expiry'}</small><details><summary>Inspect coding policy scope</summary><pre role="region" tabIndex={0} aria-label="Exact coding policy scope">{JSON.stringify(row,null,2)}</pre></details>{!row.editable?<p>This policy is read-only here. Shared host rules require a host administrator; stale or revoked consent requires a fresh approval.</p>:<><Button variant="ghost" disabled={busy} onClick={()=>setEditing(value=>!value)}>{editing?'Cancel coding policy edit':'Edit coding policy'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void revoke()}>Revoke coding policy</Button>{editing&&<form className="browser-actions" onSubmit={event=>{event.preventDefault();void save(effect,Number(seconds))}}><label>Coding decision<select aria-label="Coding decision" value={effect} onChange={event=>setEffect(event.target.value as 'allow'|'deny')}><option value="deny">Deny</option><option value="allow">Allow inside unchanged scope</option></select></label><label>Expires after seconds<Input aria-label="Coding policy expiry seconds" type="number" min={1} max={2592000} required value={seconds} onChange={event=>setSeconds(event.target.value)}/></label><Button type="submit" disabled={busy||!Number.isInteger(Number(seconds))||Number(seconds)<1||Number(seconds)>2592000}>Save coding policy</Button></form>}</>}</article>
}
