import {afterEach,it,expect,vi} from 'vitest';
import {act,cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import IdentityGroupsManager from './IdentityGroupsManager';
import AuditRetentionManager from './AuditRetentionManager';
import {request} from '../lib/api';
vi.mock('../lib/api',()=>({request:vi.fn(),json:(method:string,value:unknown)=>({method,body:JSON.stringify(value)})}));
afterEach(()=>{cleanup();vi.resetAllMocks()});
it('preserves a dirty group editor across current revision refresh and requires explicit conflict review',async()=>{
 let revision=1;
 const group=()=>({id:'group',label:revision===1?'Original':'Other administrator',organization_id:null,role:'viewer',trusted_execution:false,revision,memberships:[],mappings:[],projects:[]});
 vi.mocked(request).mockImplementation(async(path,init)=>init?.method?{} as never:path.endsWith('/principals')?[] as never:{groups:[group()],organizations:[],issuers:[]} as never);
 render(<IdentityGroupsManager onError={vi.fn()}/>);
 await waitFor(()=>expect(screen.getByRole('option',{name:'Original'})).toBeInTheDocument());
 fireEvent.change(screen.getByLabelText('Group'),{target:{value:'group'}});
 fireEvent.change(screen.getByLabelText('Group name'),{target:{value:'My unsaved group name'}});
 revision=2;fireEvent.click(screen.getByRole('button',{name:'Refresh group inventory'}));
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('changed elsewhere'));
 expect(screen.getByLabelText('Group name')).toHaveValue('My unsaved group name');expect(screen.getByRole('button',{name:'Save group'})).toBeDisabled();
 fireEvent.click(screen.getByRole('button',{name:'Keep my draft using the reviewed current revision'}));
 fireEvent.click(screen.getByRole('button',{name:'Save group'}));
 await waitFor(()=>expect(vi.mocked(request).mock.calls.some(([,init])=>init?.method==='POST')).toBe(true));
 const saved=vi.mocked(request).mock.calls.find(([,init])=>init?.method==='POST')!;
 expect(JSON.parse(saved[1]!.body as string)).toMatchObject({identifier:'group',revision:2,label:'My unsaved group name',role:'viewer'});
});
it('shows only configured claim mappings and never adds a membership from displayed provider text',async()=>{
 vi.mocked(request).mockImplementation(async(path)=>path.endsWith('/principals')?[] as never:{groups:[],organizations:[],issuers:[{issuer:'https://trusted.example',label:'Company SSO',groups_claim:null,membership_ttl:300}]} as never);
 render(<IdentityGroupsManager onError={vi.fn()}/>);
 await waitFor(()=>expect(vi.mocked(request)).toHaveBeenCalledTimes(2));
 expect(vi.mocked(request).mock.calls.every(([,init])=>!init?.method)).toBe(true);
});
it('requires explicit retention removal acknowledgement and saves the exact selected limits',async()=>{
 const policy={retention_days:30,max_bytes:65536,max_events:100};
 vi.mocked(request).mockImplementation(async(_,init)=>init?.method?{policy,removed_events:2,retained_events:8,retained_bytes:500} as never:policy as never);
 render(<AuditRetentionManager onError={vi.fn()}/>);
 await waitFor(()=>expect(screen.getByLabelText('Keep records for days')).toHaveValue(30));
 expect(screen.getByRole('button',{name:'Save limits and prune'})).toBeDisabled();
 fireEvent.click(screen.getByLabelText('I understand that applying retention removes older records.'));
 fireEvent.click(screen.getByRole('button',{name:'Save limits and prune'}));
 await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Removed 2'));
 const saved=vi.mocked(request).mock.calls.find(([,init])=>init?.method==='PUT')!;
 expect(saved[0]).toBe('/auth/admin/audit/retention');expect(JSON.parse(saved[1]!.body as string)).toEqual(policy);
 expect(screen.getByRole('button',{name:'Save limits and prune'})).toBeDisabled();
});
it('fences a pending group save across lock/unlock and preserves its editor draft',async()=>{
 const group={id:'group',label:'Original',organization_id:null,role:'viewer',trusted_execution:false,revision:1,memberships:[],mappings:[],projects:[]};
 let resolveSave!:(value:unknown)=>void;
 vi.mocked(request).mockImplementation(async(path,init)=>init?.method?await new Promise<unknown>(resolve=>{resolveSave=resolve}) as never:path.endsWith('/principals')?[] as never:{groups:[group],organizations:[],issuers:[]} as never);
 render(<IdentityGroupsManager onError={vi.fn()}/>);
 await screen.findByRole('option',{name:'Original'});
 fireEvent.change(screen.getByLabelText('Group'),{target:{value:'group'}});
 fireEvent.change(screen.getByLabelText('Group name'),{target:{value:'Pending draft'}});
 fireEvent.click(screen.getByRole('button',{name:'Save group'}));
 await waitFor(()=>expect(resolveSave).toBeDefined());
 act(()=>window.dispatchEvent(new Event('termx-locked')));
 await act(async()=>{resolveSave({});await Promise.resolve()});
 expect(screen.getByLabelText('Group name')).toHaveValue('Pending draft');
 expect(screen.queryByRole('status')).not.toBeInTheDocument();
 act(()=>window.dispatchEvent(new Event('termx-session-unlocked')));
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save group'})).not.toBeDisabled());
 expect(screen.getByLabelText('Group')).toHaveValue('group');
});
it('invalidates prune acknowledgment on lock and ignores late results without losing edited limits',async()=>{
 const policy={retention_days:30,max_bytes:65536,max_events:100};
 let resolveSave!:(value:unknown)=>void;
 vi.mocked(request).mockImplementation(async(_,init)=>init?.method?await new Promise<unknown>(resolve=>{resolveSave=resolve}) as never:policy as never);
 render(<AuditRetentionManager onError={vi.fn()}/>);
 await waitFor(()=>expect(screen.getByLabelText('Keep records for days')).toHaveValue(30));
 fireEvent.change(screen.getByLabelText('Keep records for days'),{target:{value:'45'}});
 fireEvent.click(screen.getByLabelText('I understand that applying retention removes older records.'));
 fireEvent.click(screen.getByRole('button',{name:'Save limits and prune'}));
 await waitFor(()=>expect(resolveSave).toBeDefined());
 act(()=>window.dispatchEvent(new Event('termx-session-locked')));
 await act(async()=>{resolveSave({policy,removed_events:9,retained_events:1,retained_bytes:100});await Promise.resolve()});
 act(()=>window.dispatchEvent(new Event('termx-session-unlocked')));
 await waitFor(()=>expect(screen.getByLabelText('Keep records for days')).not.toBeDisabled());
 expect(screen.getByLabelText('Keep records for days')).toHaveValue(45);
 expect(screen.getByRole('button',{name:'Save limits and prune'})).toBeDisabled();
 expect(screen.queryByRole('status')).not.toBeInTheDocument();
});
it('ignores inventory failures after actual manager unmount',async()=>{
 let rejectLoad!:(error:Error)=>void;
 vi.mocked(request).mockImplementation(async()=>await new Promise((_,reject)=>{rejectLoad=reject}) as never);
 const onError=vi.fn(),view=render(<AuditRetentionManager onError={onError}/>);
 view.unmount();await act(async()=>{rejectLoad(new Error('Late unavailable response'));await Promise.resolve()});
 expect(onError).not.toHaveBeenCalled();
});
it('fences a pending Access response immediately on signout before React unmount',async()=>{
 let resolveLoad!:(value:unknown)=>void;
 vi.mocked(request).mockImplementation(async()=>await new Promise<unknown>(resolve=>{resolveLoad=resolve}) as never);
 const onError=vi.fn();render(<AuditRetentionManager onError={onError}/>);
 act(()=>window.dispatchEvent(new Event('termx-signed-out')));
 await act(async()=>{resolveLoad({retention_days:90,max_bytes:65536,max_events:100});await Promise.resolve()});
 expect(screen.queryByLabelText('Keep records for days')).not.toBeInTheDocument();
 expect(onError).not.toHaveBeenCalled();
});
