import {useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {json,request} from '../lib/api';
import {useAccessLifecycle} from './useAccessLifecycle';
type Member={principal_id:string;source:string;expires:number|null};
type Group={id:string;label:string;organization_id:string|null;role:string;trusted_execution:boolean;revision:number;memberships:Member[];mappings:{issuer:string;claim_value:string}[];projects:{project_id:string;scopes:string[]}[]};
type Inventory={groups:Group[];organizations:{id:string;label:string}[];issuers:{issuer:string;label:string;groups_claim:string|null;membership_ttl:number}[]};
type Principal={id:string;display_name:string;enabled:number};
const fresh={label:'',organization_id:'',role:'viewer',trusted_execution:false};
export default function IdentityGroupsManager({projects=[],onError}:{projects?:{id:string;name:string}[];onError:(error:unknown)=>void}){
 const [inventory,setInventory]=useState<Inventory>({groups:[],organizations:[],issuers:[]}),[principals,setPrincipals]=useState<Principal[]>([]),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[form,setForm]=useState(fresh),[selected,setSelected]=useState<Group|null>(null),[orgName,setOrgName]=useState(''),[principal,setPrincipal]=useState(''),[days,setDays]=useState(7),[issuer,setIssuer]=useState(''),[claim,setClaim]=useState(''),[project,setProject]=useState(''),[scopes,setScopes]=useState('files-read,agent-view');
 const lifecycle=useAccessLifecycle(()=>{setBusy(false);setStatus('')});
 useEffect(()=>{if(!lifecycle.current())return;let cancelled=false;const current=lifecycle.capture();const controller=new AbortController();Promise.all([request<Inventory>('/auth/admin/groups',{signal:controller.signal}),request<Principal[]>('/auth/admin/principals',{signal:controller.signal})]).then(([groups,people])=>{if(!cancelled&&current()){setInventory(groups);setPrincipals(people)}}).catch(error=>{if(!cancelled&&current())onError(error)});return()=>{cancelled=true;controller.abort()}},[version,onError,lifecycle.refresh]);
 async function mutate(path:string,method:string,value:unknown,message:string){if(busy||!lifecycle.current())return false;const current=lifecycle.capture();setBusy(true);setStatus('');try{await request(path,json(method,value));if(!current())return false;setStatus(message);setVersion(v=>v+1);return true}catch(error){if(current())onError(error);return false}finally{if(current())setBusy(false)}}
 function edit(group:Group|null){setConflict(null);setSelected(group);setForm(group?{label:group.label,organization_id:group.organization_id||'',role:group.role,trusted_execution:group.trusted_execution}:fresh);setPrincipal('');setClaim('');setProject('')}
 const currentIssuer=inventory.issuers.find(row=>row.issuer===issuer);
 const [conflict,setConflict]=useState<Group|null>(null);
 useEffect(()=>{if(!selected)return;const latest=inventory.groups.find(row=>row.id===selected.id);if(!latest||latest.revision===selected.revision)return;const before={label:selected.label,organization_id:selected.organization_id||'',role:selected.role,trusted_execution:selected.trusted_execution};if(JSON.stringify(before)!==JSON.stringify(form))setConflict(latest);else setForm({label:latest.label,organization_id:latest.organization_id||'',role:latest.role,trusted_execution:latest.trusted_execution});setSelected(latest)},[inventory,selected,form]);
 return <section className="manager-form" aria-label="Organizations and identity groups"><h2>Organizations & groups</h2><p>Only administrator mappings grant authority. Removing a membership or changing a grant revokes affected device sessions. Provider memberships expire unless freshly verified.</p>{status&&<p role="status">{status}</p>}
  <Button variant="outline" disabled={busy} onClick={()=>setVersion(value=>value+1)}>Refresh group inventory</Button>{conflict&&<div role="alert"><p>This group changed elsewhere. Your draft is preserved. Current role: {conflict.role}; current name: {conflict.label}; trusted execution: {conflict.trusted_execution?'allowed':'denied'}.</p><Button onClick={()=>setConflict(null)}>Keep my draft using the reviewed current revision</Button></div>}
  <fieldset className="manager-form" disabled={busy||lifecycle.locked} style={{border:0,padding:0,minWidth:0}}>
  <details><summary>Add organization</summary><label className="manager-field">Organization name<Input value={orgName} onChange={e=>setOrgName(e.target.value)} maxLength={128}/></label><Button disabled={busy||!orgName.trim()} onClick={()=>void mutate('/auth/admin/organizations','POST',{label:orgName},'Organization created')}>Create organization</Button></details>
  <label className="manager-field">Group<Select aria-label="Group" value={selected?.id||''} onChange={e=>edit(inventory.groups.find(row=>row.id===e.target.value)||null)}><option value="">New group</option>{inventory.groups.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</Select></label>
  <label className="manager-field">Group name<Input value={form.label} onChange={e=>setForm(old=>({...old,label:e.target.value}))} maxLength={128}/></label><label className="manager-field">Organization<Select aria-label="Organization" value={form.organization_id} onChange={e=>setForm(old=>({...old,organization_id:e.target.value}))}><option value="">No organization</option>{inventory.organizations.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</Select></label>
  <label className="manager-field">Group host role<Select aria-label="Group host role" value={form.role} onChange={e=>setForm(old=>({...old,role:e.target.value}))}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Administrator</option></Select></label><label className="manager-choice"><input type="checkbox" checked={form.trusted_execution} onChange={e=>setForm(old=>({...old,trusted_execution:e.target.checked}))}/>Allow execution as the trusted host user</label><p>Administrator groups can manage this host. Other groups require project grants. These roles do not provide OS tenant isolation.</p>
  <Button disabled={busy||!!conflict||!form.label.trim()} onClick={()=>void mutate('/auth/admin/groups','POST',{...form,organization_id:form.organization_id||null,identifier:selected?.id||null,revision:selected?.revision||null},'Group saved; select it to inspect the current revision').then(ok=>{if(ok)edit(null)})}>Save group</Button>
  {selected&&<><h3>Members</h3>{(inventory.groups.find(row=>row.id===selected.id)?.memberships||[]).map(member=><article key={member.principal_id+member.source}><p>{principals.find(p=>p.id===member.principal_id)?.display_name||member.principal_id} · {member.source} · {member.expires?new Date(member.expires*1000).toLocaleString():'Administrator-managed membership'}</p><Button disabled={busy} variant="outline" onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/members','PUT',{principal_id:member.principal_id,present:false},'Membership removed; affected sessions revoked')}>Remove membership</Button></article>)}<label className="manager-field">Principal<Select aria-label="Principal" value={principal} onChange={e=>setPrincipal(e.target.value)}><option value="">Choose principal</option>{principals.filter(row=>row.enabled).map(row=><option key={row.id} value={row.id}>{row.display_name}</option>)}</Select></label><label className="manager-field">Membership expires in days<Input type="number" min={1} max={90} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><Button disabled={busy||!principal||!Number.isFinite(days)||days<1||days>90} onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/members','PUT',{principal_id:principal,present:true,expires:Date.now()/1000+days*86400},'Membership granted; sign in again with current authority')}>Add member</Button>
  <h3>Verified provider mapping</h3>{(inventory.groups.find(row=>row.id===selected.id)?.mappings||[]).map(mapping=><p key={mapping.issuer+mapping.claim_value}>{mapping.issuer} · {mapping.claim_value} <Button disabled={busy} variant="outline" onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/mappings','PUT',{...mapping,present:false},'Mapping removed and memberships revoked')}>Remove mapping</Button></p>)}<label className="manager-field">Trusted provider<Select aria-label="Trusted provider" value={issuer} onChange={e=>setIssuer(e.target.value)}><option value="">Choose configured provider</option>{inventory.issuers.map(row=><option key={row.issuer} value={row.issuer}>{row.label}</option>)}</Select></label>{currentIssuer&&<p>{currentIssuer.groups_claim?'Verified claim '+currentIssuer.groups_claim+' · reverify within '+currentIssuer.membership_ttl+' seconds':'Configure a group claim in this provider’s tested adapter settings before using claim mappings.'}</p>}<label className="manager-field">Exact group claim value<Input value={claim} onChange={e=>setClaim(e.target.value)} maxLength={256}/></label><Button disabled={busy||!issuer||!claim||!currentIssuer?.groups_claim} onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/mappings','PUT',{issuer,claim_value:claim,present:true},'Mapping saved; only fresh verified provider evidence enrolls members')}>Save claim mapping</Button>
  <h3>Project grants</h3>{(inventory.groups.find(row=>row.id===selected.id)?.projects||[]).map(grant=><p key={grant.project_id}>{projects.find(p=>p.id===grant.project_id)?.name||grant.project_id} · {grant.scopes.join(', ')} <Button disabled={busy} variant="outline" onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/projects/'+grant.project_id,'PUT',{scopes:[]},'Project grant revoked')}>Revoke project grant</Button></p>)}<label className="manager-field">Project<Select aria-label="Project" value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose project</option>{projects.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></label><label className="manager-field">Allowed action scopes<Input value={scopes} onChange={e=>setScopes(e.target.value)}/></label><Button disabled={busy||!project} onClick={()=>void mutate('/auth/admin/groups/'+selected.id+'/projects/'+project,'PUT',{scopes:scopes.split(',').map(s=>s.trim()).filter(Boolean)},'Project grant saved; affected sessions revoked')}>Save project grant</Button></>}
 </fieldset></section>
}
