import {useState} from 'react';
import {Server, Cloud, Terminal, CircleCheck, Settings2} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {json,request,type Project} from '../lib/api';
import './machine-runners.css';

export type MachineRunner={id:string;project:string;status:string;configuration:{kind?:string;name?:string;provider?:string;host?:string;user?:string;port?:number;root?:string;region?:string;instance_id?:string;last_error?:string|null}};
const defaults={name:'',provider:'ssh',host:'',user:'ubuntu',port:22,root:'/home/ubuntu/workspace',identity_file:'',known_hosts_file:'',python_bootstrap:'python3.14',region:'',profile:'',instance_id:'',trust_machine:false};

export default function MachineRunners({rows,projects,projectId,refresh}:{rows:MachineRunner[];projects:Project[];projectId:string|null;refresh:()=>Promise<void>}){
 const [form,setForm]=useState(defaults),[project,setProject]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[review,setReview]=useState<{id:string;action:string}|null>(null),[cloudStatus,setCloudStatus]=useState<Record<string,string>>({});
 const targetProject=projectId||project;
 const change=(key:string,value:string|number|boolean)=>setForm(old=>({...old,[key]:value}));
 async function act(id:string,action:()=>Promise<unknown>){setBusy(id);setError('');try{await action();setReview(null);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:String(reason));await refresh().catch(()=>{})}finally{setBusy('')}}
 async function cloud(id:string,action:string){const value=await request<{result:unknown}>('/api/runners/machines/'+id+'/cloud',json('POST',{action}));setCloudStatus(old=>({...old,[id]:JSON.stringify(value.result,null,2)}))}
 return <section className="machine-fleet" aria-label="Runner machines">
  <div className="creation-heading"><div><span className="machine-eyebrow"><Cloud size={15}/> PERSISTENT INFRASTRUCTURE</span><h2>Runner machines</h2><p>Connect a Linux machine from any cloud or your own network. Keep its tools, repository and workspace between tasks.</p></div><Button onClick={()=>setOpen(!open)}><Server size={16}/> Add machine</Button></div>
  {error&&<p role="alert" className="inline-error">{error}</p>}
  {open&&<form className="creation-form machine-enrollment" onSubmit={event=>{event.preventDefault();void act('register',async()=>{await request('/api/runners/machines',json('POST',{...form,project_id:targetProject}));setOpen(false);setForm(defaults)})}}>
   <h3>Connect your infrastructure</h3>
   <div className="machine-provider-options" role="group" aria-label="Machine provider">{[['ssh','Any cloud / SSH'],['ec2','Amazon EC2'],['lightsail','AWS Lightsail']].map(([value,label])=><Button key={value} type="button" variant={form.provider===value?'default':'outline'} aria-pressed={form.provider===value} onClick={()=>change('provider',value)}>{label}</Button>)}</div>
   <div className="creation-fields"><label>Machine name<Input required value={form.name} onChange={event=>change('name',event.target.value)} placeholder="Build machine · production tools"/></label><label>Project<Select aria-label="Machine project" value={targetProject} disabled={!!projectId} onChange={event=>setProject(event.target.value)}><option value="">Choose a project</option>{projects.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></label></div>
   <div className="creation-fields"><label>SSH hostname or IP<Input required value={form.host} onChange={event=>change('host',event.target.value)} placeholder="runner.example.com"/></label><label>SSH user<Input required value={form.user} onChange={event=>change('user',event.target.value)}/></label><label>SSH port<Input required type="number" min={1} max={65535} value={form.port} onChange={event=>change('port',Number(event.target.value))}/></label></div>
   <label>Persistent workspace directory<Input required value={form.root} onChange={event=>change('root',event.target.value)}/></label>
   <label>Setup Python executable<Input value={form.python_bootstrap} onChange={event=>change('python_bootstrap',event.target.value)} placeholder="python3.14 or an absolute path on the machine"/></label>
   <details><summary>SSH authentication on the control plane</summary><label>Private key file path<Input value={form.identity_file} placeholder="Use the control plane’s SSH configuration" onChange={event=>change('identity_file',event.target.value)}/></label><label>Known hosts file path<Input value={form.known_hosts_file} placeholder="Use the control plane’s known_hosts" onChange={event=>change('known_hosts_file',event.target.value)}/></label><p>Paths refer to the desktop host running TermX. Verify the machine’s host key there before connecting.</p></details>
   {form.provider!=='ssh'&&<div className="creation-fields"><label>{form.provider==='ec2'?'Instance ID':'Instance name'}<Input required value={form.instance_id} onChange={event=>change('instance_id',event.target.value)}/></label><label>AWS region<Input required value={form.region} placeholder="us-east-1" onChange={event=>change('region',event.target.value)}/></label><label>AWS profile<Input value={form.profile} placeholder="Default credential chain" onChange={event=>change('profile',event.target.value)}/></label></div>}
   <label className="machine-trust"><input type="checkbox" required checked={form.trust_machine} onChange={event=>change('trust_machine',event.target.checked)}/><span>Allow agents to execute as this SSH user, with its filesystem, network and installed tool access. Use a dedicated account with the permissions you intend to grant.</span></label>
   <Button type="submit" disabled={!!busy||!targetProject}>{busy==='register'?'Saving…':'Register machine'}</Button>
  </form>}
  {!rows.length&&!open&&<div className="machine-empty"><Server size={28}/><h3>A home for your agents</h3><p>Bring an EC2 instance, Lightsail machine, Azure VM, GCP instance, or any reachable Linux host.</p><div className="machine-steps"><span>1 · Register connection</span><span>2 · Set up runtime</span><span>3 · Choose in session settings</span></div></div>}
  <div className="runner-records">{rows.map(row=>{const config=row.configuration;return <article className="runner-record machine-card" key={row.id}><div className="creation-heading"><div><span className="machine-eyebrow">{config.provider==='ssh'?'SSH MACHINE':config.provider?.toUpperCase()}</span><h3><Server size={18}/> {config.name}</h3></div><span className={'status-badge '+row.status}>{row.status}</span></div><p className="machine-address">{config.user}@{config.host}:{config.port}</p><dl className="runner-facts"><div><dt>Workspace</dt><dd>{config.root}</dd></div><div><dt>Project</dt><dd>{projects.find(project=>project.id===row.project)?.name||row.project}</dd></div><div><dt>Execution</dt><dd>SSH account permissions</dd></div><div><dt>Persistence</dt><dd>Files and instance survive tasks</dd></div></dl>
   {config.last_error&&<p role="status" className="inline-error">{config.last_error}</p>}
   {row.status!=='removed'&&<div className="creation-actions"><Button variant="secondary" disabled={!!busy} onClick={()=>void act(row.id,()=>request('/api/runners/machines/'+row.id+'/connect',json('POST',{})))}><CircleCheck size={15}/> Check connection</Button><Button variant="ghost" disabled={!!busy} onClick={()=>setReview({id:row.id,action:'setup'})}><Settings2 size={15}/> Set up runtime</Button><Button variant="ghost" disabled={!!busy} onClick={()=>void act(row.id,()=>request('/api/runners/'+row.id+'/stop',json('POST',{})))}>Disable execution</Button><Button variant="ghost" disabled={!!busy} onClick={()=>setReview({id:row.id,action:'remove'})}>Remove connection</Button></div>}
   {config.provider!=='ssh'&&row.status!=='removed'&&<div className="creation-actions"><Button variant="ghost" disabled={!!busy} onClick={()=>void act(row.id,()=>cloud(row.id,'status'))}>Cloud status</Button>{['start','stop','reboot'].map(action=><Button key={action} variant="ghost" disabled={!!busy} onClick={()=>setReview({id:row.id,action})}>{action[0].toUpperCase()+action.slice(1)} instance</Button>)}</div>}
   {review?.id===row.id&&<div className="machine-review" role="group" aria-label="Review machine action"><h4>{review.action==='setup'?'Install the TermX runtime':review.action==='remove'?'Remove this connection':review.action+' cloud instance'}</h4><p>{review.action==='setup'?'Creates a private Python environment inside the workspace and installs this host’s worker and dependencies. Requires Linux, Python 3.14 with venv, and package network access.':review.action==='remove'?'Revokes TermX execution and keeps the cloud instance and files. Register a new connection to use this machine again.':`Sends ${review.action} to ${config.provider} for ${config.instance_id} in ${config.region}. This affects all workloads on the instance.`}</p><div className="creation-actions"><Button disabled={!!busy} onClick={()=>void act(row.id,()=>review.action==='setup'?request('/api/runners/machines/'+row.id+'/setup',json('POST',{})):review.action==='remove'?request('/api/runners/'+row.id,{method:'DELETE'}):cloud(row.id,review.action))}>{busy===row.id?'Working…':'Confirm '+review.action}</Button><Button variant="ghost" disabled={!!busy} onClick={()=>setReview(null)}>Cancel</Button></div></div>}
   {cloudStatus[row.id]&&<details><summary>Last cloud response</summary><pre>{cloudStatus[row.id]}</pre></details>}
   {row.status==='ready'&&<p className="machine-ready"><Terminal size={15}/> Choose “{config.name}” in a session’s Execution settings to run agents or scheduled tasks here.</p>}
  </article>})}</div>
 </section>;
}
