import {useEffect,useState} from 'react';
import {json,request} from '../lib/api';
export type McpBinding={connection:string;tools:string[]};
type Choice={id:string;label:string;enabled:boolean;trust:string;approved_tools:string[];allowed_projects:string[];catalog?:{tools?:{name:string}[]}};
export default function McpPresetBindings({value,onChange,disabled}:{value:McpBinding[];onChange:(value:McpBinding[])=>void;disabled:boolean}){
 const [choices,setChoices]=useState<Choice[]>([]),[error,setError]=useState('');
 useEffect(()=>{let live=true;request<{data?:{mcp_connections:Choice[]};errors?:{message:string}[]}>('/graphql',json('POST',{query:'{mcp_connections{id label enabled trust approved_tools allowed_projects catalog}}'})).then(result=>{if(!live)return;if(result.errors?.length)throw new Error(result.errors.map(e=>e.message).join('\n'));setChoices(result.data?.mcp_connections||[])}).catch(reason=>{if(live)setError(reason instanceof Error?reason.message:String(reason))});return()=>{live=false}},[]);
 const all=[...choices,...value.filter(binding=>!choices.some(c=>c.id===binding.connection)).map(binding=>({id:binding.connection,label:binding.connection+' (unavailable)',enabled:false,trust:'unavailable',approved_tools:binding.tools,allowed_projects:[],catalog:undefined}))];
 function changeTool(connection:string,tool:string,checked:boolean){onChange(value.map(binding=>binding.connection===connection?{...binding,tools:checked?[...new Set([...binding.tools,tool])]:binding.tools.filter(id=>id!==tool)}:binding))}
 return <fieldset className="provider-capabilities"><legend>Connected service tools for future runs</legend><p className="manager-help">Choose installed connections and exact tool names. Saving selects a preset binding; it does not connect, grant trust, or grant a project. Selecting a connection includes the reviewed Internal broker tools mcp_catalog and mcp_call in an explicit tool list. Project-scoped direct native adapters are refused.</p>{error&&<p role="alert">{error}</p>}{!all.length&&!error&&<p>Configure and inspect a connection in Tools & connections first.</p>}{all.map(choice=>{const selected=value.find(binding=>binding.connection===choice.id),tools=[...new Set([...(choice.catalog?.tools||[]).map(tool=>tool.name),...choice.approved_tools.filter(tool=>tool!=='*'),...(selected?.tools||[])])];return <section key={choice.id} aria-label={'Preset connection '+choice.label}><label><span><input type="checkbox" disabled={disabled||(!selected&&(!choice.enabled||choice.trust!=='trusted'))} checked={!!selected} onChange={event=>onChange(event.target.checked?[...value,{connection:choice.id,tools:[]}]:value.filter(binding=>binding.connection!==choice.id))}/>{choice.label}</span></label><p>{choice.allowed_projects.length?'Allowed project IDs: '+choice.allowed_projects.join(', '):'Administrator-managed host-wide connection'} · {choice.trust}</p>{selected&&<fieldset><legend>Selected tools for {choice.label}</legend>{tools.map(tool=><label key={tool}><span><input type="checkbox" disabled={disabled||(!choice.approved_tools.includes('*')&&!choice.approved_tools.includes(tool)&&!selected.tools.includes(tool))} checked={selected.tools.includes(tool)} onChange={event=>changeTool(choice.id,tool,event.target.checked)}/>{tool}</span></label>)}{!tools.length&&<p>No reviewed catalog is available. Connect and inspect in Tools & connections before selecting tool names.</p>}<p>An empty selection permits no service tools. Existing unavailable bindings remain visible until you explicitly remove them.</p></fieldset>}</section>})}</fieldset>
}
