import {restoreArtifactDrafts,persistArtifactDrafts,snapshotArtifactDrafts,type ArtifactDraft} from '../lib/artifact-drafts';
import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {gql,json,request,type Provider} from '../lib/api';
import {download,transfer} from '../lib/transfers';
import './creation.css';
import {mediaIntent,clearMediaIntent} from '../lib/media-intent';
type Artifact={project:string|null;id:string;title:string;kind:string;version:number;content:any;mime?:string};
type MediaOperation={id:string;status:string;created:number|null;result:Artifact|null};
type Slide={title:string;body:string;notes?:string};
const formats:Record<string,string[]>={document:['docx','txt'],table:['xlsx','csv','json'],deck:['pptx','json'],chart:['svg','json'],code:['txt'],image:['original'],audio:['original'],video:['original'],input:['original']};
export default function Media({projectId,ownerId,visible=true,onContext}:{projectId:string|null;ownerId?:string;visible?:boolean;onContext?:(text:string,attachments:unknown[])=>void}){
 const [rows,setRows]=useState<Artifact[]>([]),[selected,setSelected]=useState<Artifact|null>(null),[content,setContent]=useState<any>(''),[versions,setVersions]=useState<{version:number;created:number}[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[providers,setProviders]=useState<Provider[]>([]),[provider,setProvider]=useState(''),[model,setModel]=useState(''),[prompt,setPrompt]=useState(''),[operation,setOperation]=useState('image-generate'),[billing,setBilling]=useState(false),[title,setTitle]=useState(''),[kind,setKind]=useState('document'),[voice,setVoice]=useState('alloy'),[preview,setPreview]=useState(''),[recording,setRecording]=useState(false);
 const [drafts,setDrafts]=useState<ArtifactDraft[]>([]),[draftKey,setDraftKey]=useState(''),[draftsReady,setDraftsReady]=useState(false);const epoch=useRef(0);
 const [operations,setOperations]=useState<MediaOperation[]>([]);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),previewUrl=useRef('');
 const captureEpoch=useRef(0),capturePending=useRef(false),visibleNow=useRef(visible);visibleNow.current=visible;
 const account=providers.find(row=>row.id===provider);
 async function load(){const generation=epoch.current;const query=projectId?'?project_id='+encodeURIComponent(projectId):'';const items=await request<Artifact[]>('/api/media/artifacts'+query),operations=await request<MediaOperation[]>('/api/media/operations'+query);if(generation===epoch.current){setRows(items);setOperations(operations)}}
 async function choose(row:Artifact,recovered?:ArtifactDraft){const generation=epoch.current;const value=await request<Artifact>('/api/media/artifacts/'+row.id);if(generation!==epoch.current)return;const local=recovered||snapshotArtifactDrafts(ownerId||'').find(item=>item.artifact_id===value.id&&item.project_id===projectId);setSelected(local?{...value,version:local.version}:value);setDraftKey(local?.key||value.id);setContent(structuredClone(local?.content??value.content));setVersions(await request('/api/media/artifacts/'+row.id+'/versions'));setPreview('');if(value.mime){const blob=await transfer('/api/media/artifacts/'+row.id+'/export?format=original');if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);previewUrl.current=URL.createObjectURL(blob);setPreview(previewUrl.current)}}
 useEffect(()=>{epoch.current++;setSelected(null);setPreview('');void load().catch(error=>setError(String(error)));gql<{agent_providers:Provider[]}>('{agent_providers{id name model capabilities secret_configured}}').then(data=>setProviders(data.agent_providers.filter(row=>row.capabilities.some(capability=>['image','audio'].includes(capability))))).catch(error=>setError(String(error)));return()=>{recorder.current?.stop();stream.current?.getTracks().forEach(track=>track.stop());if(previewUrl.current)URL.revokeObjectURL(previewUrl.current)}},[projectId]);
 useEffect(()=>{let stopped=false;setDraftsReady(false);if(ownerId)restoreArtifactDrafts(ownerId).then(rows=>{if(!stopped){setDrafts(rows);void persistArtifactDrafts(ownerId,rows);setDraftsReady(true)}}).catch(error=>setError(String(error)));const handoff=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail.owner===ownerId)setDrafts(detail.rows)};window.addEventListener('termx-artifact-handoff',handoff);return()=>{stopped=true;window.removeEventListener('termx-artifact-handoff',handoff)}},[ownerId]);
 useEffect(()=>{const locked=()=>{captureEpoch.current++;epoch.current++;visibleNow.current=false;capturePending.current=false;document.querySelectorAll<HTMLMediaElement>('.creation-page audio,.creation-page video').forEach(media=>media.pause());if(previewUrl.current){URL.revokeObjectURL(previewUrl.current);previewUrl.current='';setPreview('')}setBilling(false);if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=='inactive')recorder.current.stop()}stream.current?.getTracks().forEach(track=>track.stop());setRecording(false)};window.addEventListener('termx-locked',locked);return()=>window.removeEventListener('termx-locked',locked)},[]);
 useEffect(()=>{if(!visible){captureEpoch.current++;capturePending.current=false;}if(!visible&&recording){recorder.current?.stop();stream.current?.getTracks().forEach(track=>track.stop());setRecording(false)}},[visible,recording]);
 useEffect(()=>{if(!ownerId||!draftsReady||!selected||selected.mime)return;const snapshot=snapshotArtifactDrafts(ownerId),existing=snapshot.find(row=>row.key===(draftKey||selected.id)),rows=snapshot.filter(row=>row.key!==(draftKey||selected.id));if(JSON.stringify(content)!==JSON.stringify(selected.content))rows.push({key:draftKey||selected.id,artifact_id:selected.id,project_id:selected.project??null,title:existing?.title||selected.title,kind:selected.kind,version:selected.version,content:structuredClone(content)});setDrafts(rows);void persistArtifactDrafts(ownerId,rows).catch(error=>setError(String(error)))},[content,selected,draftsReady,draftKey,ownerId,projectId]);
 async function restoreDraft(row:ArtifactDraft){const current=await request<Artifact>('/api/media/artifacts/'+row.artifact_id);if(current.kind!==row.kind||current.project!==row.project_id)throw Error('The artifact kind changed. Your preserved draft remains available.');await choose(current,row);setNotice(row.version!==current.version?'A newer saved version exists. Your local content is preserved; inspect versions before saving.':'Restored unsaved artifact draft.');if(row.version!==current.version)setSelected({...current,version:row.version})}
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await load()}catch(error){setError(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 async function upload(file:Blob,name:string){const generation=captureEpoch.current;const blob=await transfer('/api/media/inputs?name='+encodeURIComponent(name)+(projectId?'&project_id='+encodeURIComponent(projectId):''),{method:'POST',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});const row=JSON.parse(await blob.text()) as Artifact;if(generation!==captureEpoch.current||!visibleNow.current)throw Error('Upload finished while the workspace was hidden. Inspect its saved input after unlocking.');await choose(row);return row}
 async function capture(){if(capturePending.current||!visibleNow.current)return;if(recording){recorder.current?.stop();setRecording(false);return}const generation=++captureEpoch.current;capturePending.current=true;try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(generation!==captureEpoch.current||!visibleNow.current){media.getTracks().forEach(track=>track.stop());return}stream.current=media;const chunks:Blob[]=[];const mime=['audio/webm','audio/mp4','audio/ogg'].find(type=>MediaRecorder.isTypeSupported(type));const instance=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=instance;instance.ondataavailable=event=>{if(generation===captureEpoch.current)chunks.push(event.data)};instance.onstop=()=>{media.getTracks().forEach(track=>track.stop());if(generation!==captureEpoch.current||!visibleNow.current)return;setRecording(false);void act(()=>upload(new Blob(chunks,{type:instance.mimeType||'audio/webm'}),'Voice recording'))};instance.start();setRecording(true)}catch(error){if(generation===captureEpoch.current)setError('Microphone access failed. Allow access or upload an audio file.')}finally{if(generation===captureEpoch.current)capturePending.current=false}}
 async function generate(){const generation=captureEpoch.current;const args={project_id:projectId,operation,provider_id:provider,model,prompt,voice,input_id:selected?.id,acknowledge_billing:billing};const intent=await mediaIntent(ownerId,projectId,args);try{if(generation!==captureEpoch.current||!visibleNow.current)return;const value=await request<Artifact>('/api/media/generate',json('POST',{request_id:intent.id,...args}));clearMediaIntent(intent.key,intent.id);if(generation!==captureEpoch.current||!visibleNow.current)return;await choose(value);setNotice(operation==='transcribe'?'Transcript ready. Inspect it before adding to a conversation.':'Output created using '+account?.name)}finally{await load()}}

 function newContent(){return kind==='table'?{columns:['Column 1'],rows:[['']]}:kind==='chart'?{points:[{label:'Series 1',value:0}]}:kind==='deck'?[{title:'',body:'',notes:''}]:''}
 function tableCell(row:number,column:number,value:string){setContent((previous:any)=>({...previous,rows:previous.rows.map((cells:any[],index:number)=>index===row?cells.map((cell:any,index:number)=>index===column?value:cell):cells)}))}
 const chartMax=selected?.kind==='chart'?Math.max(1,...(content.points||[]).map((point:{value:number})=>Math.abs(point.value))):1;
 return <section className="creation-page" aria-label="Media and artifacts"><div className="creation-heading"><div><h1>Media & artifacts</h1><p>Create, inspect and revise. Every saved version remains available.</p></div><label>Upload input<Input type="file" accept="image/*,audio/*,video/*,.pdf,.docx,.txt,.md,.csv,.json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void act(()=>upload(file,file.name))}}/></label></div>{error&&<p role="alert" className="inline-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{drafts.filter(row=>row.project_id===projectId).length>0&&<details className="creation-form"><summary>Unsaved artifact drafts</summary>{drafts.filter(row=>row.project_id===projectId).map(row=><div className="creation-actions" key={row.key}><span>{row.title} · based on v{row.version}</span><Button onClick={()=>void act(()=>restoreDraft(row))}>Restore draft {row.title}</Button><Button variant="ghost" onClick={()=>{if(!ownerId)return;const rows=snapshotArtifactDrafts(ownerId).filter(item=>item.key!==row.key);setDrafts(rows);void persistArtifactDrafts(ownerId,rows).catch(error=>setError(String(error)));if(draftKey===row.key){setSelected(null);setDraftKey('')}}}>Discard draft {row.title}</Button></div>)}</details>}
 <details className="creation-form"><summary>Create an artifact</summary><form onSubmit={event=>{event.preventDefault();void act(async()=>{const value=await request<Artifact>('/api/media/artifacts',json('POST',{project_id:projectId,kind,title,content:newContent()}));await choose(value)})}}><div className="creation-fields"><label>Title<Input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Kind<Select aria-label="Kind" value={kind} onChange={event=>setKind(event.target.value)}>{['document','table','chart','deck','code'].map(kind=><option key={kind}>{kind}</option>)}</Select></label></div><Button type="submit" disabled={busy}>Create artifact</Button></form></details>
 <div className="artifact-workspace"><nav className="artifact-list" aria-label="Artifact versions">{rows.map(row=><Button key={row.id} variant={selected?.id===row.id?'secondary':'ghost'} onClick={()=>act(()=>choose(row))}><span>{row.title}<small> · {row.kind} · v{row.version}</small></span></Button>)}{!rows.length&&<p>Create an artifact or upload an input to begin.</p>}</nav><div>{selected&&<><div className="creation-heading"><h2>{selected.title}{JSON.stringify(content)!==JSON.stringify(selected.content)&&<small> · Unsaved</small>}</h2><Select aria-label="Inspect version" value={selected.version} onChange={event=>act(async()=>{const item=await request<Artifact>('/api/media/artifacts/'+selected.id+'?version='+event.target.value);setSelected(item);setContent(structuredClone(item.content))})}>{versions.map(version=><option key={version.version} value={version.version}>Version {version.version} · {new Date(version.created*1000).toLocaleString()}</option>)}</Select></div>
 {['document','code'].includes(selected.kind)&&<textarea className="artifact-editor" aria-label="Artifact content" value={content||''} onChange={event=>setContent(event.target.value)}/>}
 {selected.kind==='table'&&<div className="artifact-grid"><table><thead><tr>{content.columns.map((column:string,index:number)=><th key={index}><Input aria-label={'Column '+(index+1)+' heading'} value={column} onChange={event=>setContent({...content,columns:content.columns.map((old:string,position:number)=>position===index?event.target.value:old)})}/></th>)}</tr></thead><tbody>{content.rows.map((row:any[],index:number)=><tr key={index}>{row.map((cell:any,column:number)=><td key={column}><Input aria-label={'Row '+(index+1)+', column '+(column+1)} value={String(cell??'')} onChange={event=>tableCell(index,column,event.target.value)}/></td>)}</tr>)}</tbody></table><div className="creation-actions"><Button variant="ghost" onClick={()=>setContent({...content,rows:[...content.rows,content.columns.map(()=> '')]})}>Add row</Button><Button variant="ghost" onClick={()=>setContent({...content,columns:[...content.columns,'New column'],rows:content.rows.map((row:any[])=>[...row,''])})}>Add column</Button></div></div>}
 {selected.kind==='chart'&&<div className="artifact-chart">{content.points.map((point:{label:string;value:number},index:number)=><div className="artifact-chart-row" key={index}><Input aria-label={'Series '+(index+1)+' label'} value={point.label} onChange={event=>setContent({points:content.points.map((old:any,position:number)=>position===index?{...old,label:event.target.value}:old)})}/><div role="img" className="artifact-chart-bar" style={{width:Math.abs(point.value)/chartMax*100+'%'}} aria-label={point.label+': '+point.value}/><Input type="number" aria-label={'Series '+(index+1)+' value'} value={point.value} onChange={event=>setContent({points:content.points.map((old:any,position:number)=>position===index?{...old,value:Number(event.target.value)}:old)})}/></div>)}<Button variant="ghost" onClick={()=>setContent({points:[...content.points,{label:'New series',value:0}]})}>Add series</Button></div>}
 {selected.kind==='deck'&&<div className="artifact-slides">{content.map((slide:Slide,index:number)=><article key={index} className="artifact-slide"><label>Slide {index+1} title<Input value={slide.title} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,title:event.target.value}:old))}/></label><textarea className="artifact-editor" aria-label={'Slide '+(index+1)+' body'} value={slide.body} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,body:event.target.value}:old))}/><label>Speaker notes<Input value={slide.notes||''} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,notes:event.target.value}:old))}/></label></article>)}<Button variant="ghost" onClick={()=>setContent([...content,{title:'',body:'',notes:''}])}>Add slide</Button></div>}
 {preview&&selected.mime?.startsWith('image/')&&<img className="artifact-preview" src={preview} alt={selected.title}/>}{preview&&selected.mime?.startsWith('audio/')&&<audio controls src={preview} aria-label={selected.title}/>} {preview&&selected.mime?.startsWith('video/')&&<video className="artifact-preview" controls src={preview} aria-label={selected.title}/>}
 <div className="creation-actions">{!selected.mime&&<Button disabled={busy} onClick={()=>act(async()=>{const value=await request<Artifact>('/api/media/artifacts/'+selected.id,json('PUT',{version:selected.version,content}));if(ownerId){const rows=snapshotArtifactDrafts(ownerId).filter(row=>row.key!==(draftKey||selected.id));await persistArtifactDrafts(ownerId,rows);setDrafts(rows)}await choose(value)})}>Save new version</Button>}{(formats[selected.kind]||['original']).map(format=><Button key={format} variant="secondary" disabled={busy} onClick={()=>act(()=>download('/api/media/artifacts/'+selected.id+'/export?format='+format+'&version='+selected.version,selected.title+'.'+(format==='original'?(selected.mime?.split('/')[1]||'bin'):format)))}>Export {format}</Button>)}{selected.kind==='input'&&<Button variant="secondary" disabled={busy} onClick={()=>act(async()=>{const context=await request<{text:string;attachments:unknown[];disclosure:string}>('/api/media/inputs/'+selected.id+'/context',json('POST',{}));setNotice(context.disclosure);onContext?.(context.text,context.attachments)})}>Add converted context to chat</Button>}{selected.kind==='document'&&onContext&&<Button variant="secondary" onClick={()=>onContext(content,[])}>Add text to chat</Button>}</div></>}</div></div>
 <section className="creation-form"><h2>Voice & image creation</h2>{operations.length>0&&<details><summary>Recent provider operations</summary>{operations.map(item=><div className="creation-actions" key={item.id}><span>{item.result?.title||'Provider operation'} · {item.status}</span>{item.result&&<Button variant="secondary" onClick={()=>act(()=>choose(item.result!))}>Inspect output</Button>}{item.status==='unknown'&&<span>The provider outcome is uncertain. Check your provider account before starting a new operation; this request will not be replayed.</span>}</div>)}</details>}<div className="artifact-voice"><Button variant="secondary" disabled={busy} onClick={capture}>{recording?'Stop recording':'Record voice'}</Button>{recording&&<span role="status" className="recording-indicator">Microphone recording · visible until stopped</span>}</div><form onSubmit={event=>{event.preventDefault();void act(generate)}}><div className="creation-fields"><label>Operation<Select aria-label="Operation" value={operation} onChange={event=>{setOperation(event.target.value)}}><option value="image-generate">Generate image</option><option value="image-edit">Edit selected image</option><option value="transcribe">Transcribe selected audio</option><option value="speak">Read text aloud</option></Select></label><label>Configured account<Select aria-label="Configured account" required value={provider} onChange={event=>{setProvider(event.target.value);setModel(providers.find(row=>row.id===event.target.value)?.model||'')}}><option value="">Select an account</option>{providers.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></label><label>Capability model<Input required value={model} onChange={event=>{setModel(event.target.value)}}/></label>{operation==='speak'&&<label>Voice<Input value={voice} onChange={event=>setVoice(event.target.value)}/></label>}</div><label>Prompt or text<Input value={prompt} onChange={event=>{setPrompt(event.target.value)}}/></label><label className="billing-consent"><span><input type="checkbox" checked={billing} onChange={event=>setBilling(event.target.checked)}/> Use this configured account; provider charges may apply.</span></label><Button type="submit" disabled={busy||!billing||!provider||!model}>{busy?'Creating…':'Run selected capability'}</Button>{!providers.length&&<p>Configure an account with image or audio capability in Models & engines.</p>}</form></section></section>
}
