import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import Media from './Media';
import {request} from '../lib/api';
import {restoreArtifactDrafts,persistArtifactDrafts,snapshotArtifactDrafts,type ArtifactDraft} from '../lib/artifact-drafts';
vi.mock('../lib/api',()=>({request:vi.fn(),gql:vi.fn(async()=>({agent_providers:[]})),json:(method:string,data:unknown)=>({method,body:JSON.stringify(data)})}));
vi.mock('../lib/transfers',()=>({download:vi.fn(),transfer:vi.fn()}));
vi.mock('../lib/artifact-drafts',()=>({restoreArtifactDrafts:vi.fn(),persistArtifactDrafts:vi.fn(),snapshotArtifactDrafts:vi.fn()}));
let local:ArtifactDraft[]=[];const artifact={id:'a',project:'project',kind:'document',title:'Notes',version:3,content:'Saved text'};
beforeEach(()=>{local=[];vi.clearAllMocks();vi.mocked(restoreArtifactDrafts).mockImplementation(async()=>structuredClone(local));vi.mocked(snapshotArtifactDrafts).mockImplementation(()=>structuredClone(local));vi.mocked(persistArtifactDrafts).mockImplementation(async(_,rows)=>{local=structuredClone(rows)});vi.mocked(request).mockImplementation(async(path,init)=>{if(path.startsWith('/api/media/operations'))return [];if(path==='/api/media/artifacts?project_id=project')return [artifact];if(path==='/api/media/artifacts/a/versions')return [{version:3,created:1}];if(path==='/api/media/artifacts/a'&&init?.method==='PUT')throw Error('Resource changed');if(path==='/api/media/artifacts/a')return artifact;return []})});
afterEach(cleanup);
it('preserves unsaved artifact content across hidden layout and an actual unmount/reload and keeps conflict edits',async()=>{const view=render(<Media ownerId="owner" projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:/Notes/}));const editor=await screen.findByRole('textbox',{name:'Artifact content'});fireEvent.change(editor,{target:{value:'Local document edit'}});await waitFor(()=>expect(local[0]?.content).toBe('Local document edit'));view.rerender(<Media ownerId="owner" projectId="project" visible={false}/>);expect(editor).toHaveValue('Local document edit');view.unmount();render(<Media ownerId="owner" projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:/^Notes/}));const restored=await screen.findByRole('textbox',{name:'Artifact content'});expect(restored).toHaveValue('Local document edit');fireEvent.click(screen.getByRole('button',{name:'Save new version'}));await screen.findByRole('alert');expect(restored).toHaveValue('Local document edit');expect(local[0].version).toBe(3)});
it('revalidates recovered artifact access and refuses to silently rebase an old edit onto a newer server version',async()=>{local=[{key:'a',artifact_id:'a',project_id:'project',kind:'document',title:'Notes',version:2,content:'Older unsent edit'}];render(<Media ownerId="owner" projectId="project"/>);await screen.findByText('Unsaved artifact drafts');fireEvent.click(await screen.findByRole('button',{name:'Restore draft Notes',hidden:true}));await screen.findByRole('textbox',{name:'Artifact content'});expect(screen.getByRole('textbox',{name:'Artifact content'})).toHaveValue('Older unsent edit');fireEvent.click(screen.getByRole('button',{name:'Save new version'}));await screen.findByRole('alert');const call=vi.mocked(request).mock.calls.find(([,init])=>init?.method==='PUT');expect(JSON.parse(String(call?.[1]?.body)).version).toBe(2);expect(local[0].content).toBe('Older unsent edit')});

it('keeps returned conflict-copy identity after activating and editing either preserved draft',async()=>{local=[{key:'a',artifact_id:'a',project_id:'project',kind:'document',title:'Notes',version:3,content:'Main edit'},{key:'a:handoff:receipt',artifact_id:'a',project_id:'project',kind:'document',title:'Notes (returned copy)',version:2,content:'Returned edit'}];render(<Media ownerId="owner" projectId="project"/>);await screen.findByText('Unsaved artifact drafts');fireEvent.click(await screen.findByRole('button',{name:'Restore draft Notes (returned copy)',hidden:true}));const editor=await screen.findByRole('textbox',{name:'Artifact content'});await waitFor(()=>expect(editor).toHaveValue('Returned edit'));fireEvent.change(editor,{target:{value:'Returned revised'}});await waitFor(()=>expect(local.find(row=>row.key==='a:handoff:receipt')?.content).toBe('Returned revised'));expect(local.find(row=>row.key==='a:handoff:receipt')?.title).toBe('Notes (returned copy)');fireEvent.click(screen.getByRole('button',{name:'Restore draft Notes',hidden:true}));await waitFor(()=>expect(editor).toHaveValue('Main edit'));expect(screen.getByRole('button',{name:'Restore draft Notes (returned copy)',hidden:true})).toBeInTheDocument();expect(local.find(row=>row.key==='a:handoff:receipt')?.version).toBe(2);expect(vi.mocked(request).mock.calls.some(([,init])=>init?.method==='PUT')).toBe(false)});

it('discards microphone permission arriving after a workspace lock without starting or uploading a recorder',async()=>{let resolve!:(value:MediaStream)=>void;const stop=vi.fn(),record=vi.fn();Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:vi.fn(()=>new Promise<MediaStream>(done=>resolve=done))}});vi.stubGlobal('MediaRecorder',record);render(<Media ownerId="owner" projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:'Record voice'}));fireEvent(window,new Event('termx-locked'));resolve({getTracks:()=>[{stop}]} as unknown as MediaStream);await waitFor(()=>expect(stop).toHaveBeenCalled());expect(record).not.toHaveBeenCalled();expect(vi.mocked(request).mock.calls.some(([path])=>path.startsWith('/api/media/inputs'))).toBe(false);vi.unstubAllGlobals()});

it('inspects history without replacing or deleting a dirty editor, and copies an old version into a separate draft',async()=>{const original=vi.mocked(request).getMockImplementation()!;vi.mocked(request).mockImplementation((path,init)=>path==='/api/media/artifacts/a/versions'?Promise.resolve([{version:3,created:1},{version:2,created:0}]):path==='/api/media/artifacts/a?version=2'?Promise.resolve({...artifact,version:2,content:'Historical saved text'}):original(path,init));render(<Media ownerId="owner" projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:/^Notes/}));const editor=await screen.findByRole('textbox',{name:'Artifact content'});fireEvent.change(editor,{target:{value:'Unsaved current edit'}});await waitFor(()=>expect(local[0]?.content).toBe('Unsaved current edit'));fireEvent.change(screen.getByRole('combobox',{name:'Inspect version'}),{target:{value:'2'}});await screen.findByRole('region',{name:'Saved artifact content version 2'});expect(editor).toHaveValue('Unsaved current edit');expect(local.find(row=>row.key==='a')?.content).toBe('Unsaved current edit');fireEvent.click(screen.getByRole('button',{name:'Copy saved version to a separate draft'}));await waitFor(()=>expect(editor).toHaveValue('Historical saved text'));expect(local.find(row=>row.key==='a')?.content).toBe('Unsaved current edit');expect(local.find(row=>row.key!=='a')?.version).toBe(3);expect(screen.getByRole('button',{name:'Restore draft Notes (restored v2)',hidden:true})).toBeInTheDocument();expect(vi.mocked(request).mock.calls.some(([,init])=>init?.method==='PUT')).toBe(false)});

it('keeps newer visible edits when a historical-copy persistence completes late',async()=>{let complete!:()=>void;const original=vi.mocked(request).getMockImplementation()!;vi.mocked(request).mockImplementation((path,init)=>path==='/api/media/artifacts/a/versions'?Promise.resolve([{version:3,created:1},{version:2,created:0}]):path==='/api/media/artifacts/a?version=2'?Promise.resolve({...artifact,version:2,content:'Historical saved text'}):original(path,init));vi.mocked(persistArtifactDrafts).mockImplementation(async(_,rows)=>{local=structuredClone(rows);if(rows.some(row=>row.title.includes('(restored v2)'))&&!complete)await new Promise<void>(resolve=>complete=resolve)});render(<Media ownerId="owner" projectId="project"/>);fireEvent.click(await screen.findByRole('button',{name:/^Notes/}));const editor=await screen.findByRole('textbox',{name:'Artifact content'});fireEvent.change(editor,{target:{value:'Original unsaved edit'}});fireEvent.change(screen.getByRole('combobox',{name:'Inspect version'}),{target:{value:'2'}});await screen.findByRole('region',{name:'Saved artifact content version 2'});fireEvent.click(screen.getByRole('button',{name:'Copy saved version to a separate draft'}));await waitFor(()=>expect(complete).toBeTypeOf('function'));fireEvent.change(editor,{target:{value:'Newer visible edit while copy waits'}});complete();await screen.findByText('Saved version copied to a separate draft. Your newer editor changes remain active.');expect(editor).toHaveValue('Newer visible edit while copy waits');expect(local.find(row=>row.key==='a')?.content).toBe('Newer visible edit while copy waits');expect(local.find(row=>row.key!=='a')?.content).toBe('Historical saved text');expect(vi.mocked(request).mock.calls.some(([,init])=>init?.method==='PUT')).toBe(false)});
