import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {gql,json,request,type Provider} from '../lib/api';
import {download,transfer} from '../lib/transfers';
import './creation.css';
import {mediaIntent,clearMediaIntent} from '../lib/media-intent';
type Artifact={id:string;title:string;kind:string;version:number;content:any;mime?:string};
type MediaOperation={id:string;status:string;created:number|null;result:Artifact|null};
type Slide={title:string;body:string;notes?:string};
const formats:Record<string,string[]>={document:['docx','txt'],table:['xlsx','csv','json'],deck:['pptx','json'],chart:['svg','json'],code:['txt'],image:['original'],audio:['original'],video:['original'],input:['original']};
export default function Media({projectId,ownerId,onContext}:{projectId:string|null;ownerId?:string;onContext?:(text:string,attachments:unknown[])=>void}){
 const [rows,setRows]=useState<Artifact[]>([]),[selected,setSelected]=useState<Artifact|null>(null),[content,setContent]=useState<any>(''),[versions,setVersions]=useState<{version:number;created:number}[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[providers,setProviders]=useState<Provider[]>([]),[provider,setProvider]=useState(''),[model,setModel]=useState(''),[prompt,setPrompt]=useState(''),[operation,setOperation]=useState('image-generate'),[billing,setBilling]=useState(false),[title,setTitle]=useState(''),[kind,setKind]=useState('document'),[voice,setVoice]=useState('alloy'),[preview,setPreview]=useState(''),[recording,setRecording]=useState(false);
 const [operations,setOperations]=useState<MediaOperation[]>([]);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),previewUrl=useRef('');
 const account=providers.find(row=>row.id===provider);
 async function load(){const query=projectId?'?project_id='+encodeURIComponent(projectId):'';setRows(await request<Artifact[]>('/api/media/artifacts'+query));setOperations(await request<MediaOperation[]>('/api/media/operations'+query))}
 async function choose(row:Artifact){const value=await request<Artifact>('/api/media/artifacts/'+row.id);setSelected(value);setContent(structuredClone(value.content));setVersions(await request('/api/media/artifacts/'+row.id+'/versions'));setPreview('');if(value.mime){const blob=await transfer('/api/media/artifacts/'+row.id+'/export?format=original');if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);previewUrl.current=URL.createObjectURL(blob);setPreview(previewUrl.current)}}
 useEffect(()=>{void load().catch(error=>setError(String(error)));gql<{agent_providers:Provider[]}>('{agent_providers{id name model capabilities secret_configured}}').then(data=>setProviders(data.agent_providers.filter(row=>row.capabilities.some(capability=>['image','audio'].includes(capability))))).catch(error=>setError(String(error)));return()=>{recorder.current?.stop();stream.current?.getTracks().forEach(track=>track.stop());if(previewUrl.current)URL.revokeObjectURL(previewUrl.current)}},[projectId]);
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await load()}catch(error){setError(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 async function upload(file:Blob,name:string){const blob=await transfer('/api/media/inputs?name='+encodeURIComponent(name)+(projectId?'&project_id='+encodeURIComponent(projectId):''),{method:'POST',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});const row=JSON.parse(await blob.text()) as Artifact;await choose(row);return row}
 async function capture(){if(recording){recorder.current?.stop();setRecording(false);return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const chunks:Blob[]=[];const mime=['audio/webm','audio/mp4','audio/ogg'].find(type=>MediaRecorder.isTypeSupported(type));recorder.current=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);recorder.current.ondataavailable=event=>chunks.push(event.data);recorder.current.onstop=()=>{const type=recorder.current?.mimeType||'audio/webm';stream.current?.getTracks().forEach(track=>track.stop());void act(()=>upload(new Blob(chunks,{type}),'Voice recording'))};recorder.current.start();setRecording(true)}catch(error){setError('Microphone access failed. Allow access or upload an audio file.')}}
 async function generate(){const args={project_id:projectId,operation,provider_id:provider,model,prompt,voice,input_id:selected?.id,acknowledge_billing:billing};const intent=await mediaIntent(ownerId,projectId,args);try{const value=await request<Artifact>('/api/media/generate',json('POST',{request_id:intent.id,...args}));clearMediaIntent(intent.key,intent.id);await choose(value);setNotice(operation==='transcribe'?'Transcript ready. Inspect it before adding to a conversation.':'Output created using '+account?.name)}finally{await load()}}

 function newContent(){return kind==='table'?{columns:['Column 1'],rows:[['']]}:kind==='chart'?{points:[{label:'Series 1',value:0}]}:kind==='deck'?[{title:'',body:'',notes:''}]:''}
 function tableCell(row:number,column:number,value:string){setContent((previous:any)=>({...previous,rows:previous.rows.map((cells:any[],index:number)=>index===row?cells.map((cell:any,index:number)=>index===column?value:cell):cells)}))}
 const chartMax=selected?.kind==='chart'?Math.max(1,...(content.points||[]).map((point:{value:number})=>Math.abs(point.value))):1;
 return <section className="creation-page" aria-label="Media and artifacts"><div className="creation-heading"><div><h1>Media & artifacts</h1><p>Create, inspect and revise. Every saved version remains available.</p></div><label>Upload input<Input type="file" accept="image/*,audio/*,video/*,.pdf,.docx,.txt,.md,.csv,.json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void act(()=>upload(file,file.name))}}/></label></div>{error&&<p role="alert" className="inline-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <details className="creation-form"><summary>Create an artifact</summary><form onSubmit={event=>{event.preventDefault();void act(async()=>{const value=await request<Artifact>('/api/media/artifacts',json('POST',{project_id:projectId,kind,title,content:newContent()}));await choose(value)})}}><div className="creation-fields"><label>Title<Input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Kind<Select aria-label="Kind" value={kind} onChange={event=>setKind(event.target.value)}>{['document','table','chart','deck','code'].map(kind=><option key={kind}>{kind}</option>)}</Select></label></div><Button type="submit" disabled={busy}>Create artifact</Button></form></details>
 <div className="artifact-workspace"><nav className="artifact-list" aria-label="Artifact versions">{rows.map(row=><Button key={row.id} variant={selected?.id===row.id?'secondary':'ghost'} onClick={()=>act(()=>choose(row))}><span>{row.title}<small> · {row.kind} · v{row.version}</small></span></Button>)}{!rows.length&&<p>Create an artifact or upload an input to begin.</p>}</nav><div>{selected&&<><div className="creation-heading"><h2>{selected.title}</h2><Select aria-label="Inspect version" value={selected.version} onChange={event=>act(async()=>{const item=await request<Artifact>('/api/media/artifacts/'+selected.id+'?version='+event.target.value);setSelected(item);setContent(structuredClone(item.content))})}>{versions.map(version=><option key={version.version} value={version.version}>Version {version.version} · {new Date(version.created*1000).toLocaleString()}</option>)}</Select></div>
 {['document','code'].includes(selected.kind)&&<textarea className="artifact-editor" aria-label="Artifact content" value={content||''} onChange={event=>setContent(event.target.value)}/>}
 {selected.kind==='table'&&<div className="artifact-grid"><table><thead><tr>{content.columns.map((column:string,index:number)=><th key={index}><Input aria-label={'Column '+(index+1)+' heading'} value={column} onChange={event=>setContent({...content,columns:content.columns.map((old:string,position:number)=>position===index?event.target.value:old)})}/></th>)}</tr></thead><tbody>{content.rows.map((row:any[],index:number)=><tr key={index}>{row.map((cell:any,column:number)=><td key={column}><Input aria-label={'Row '+(index+1)+', column '+(column+1)} value={String(cell??'')} onChange={event=>tableCell(index,column,event.target.value)}/></td>)}</tr>)}</tbody></table><div className="creation-actions"><Button variant="ghost" onClick={()=>setContent({...content,rows:[...content.rows,content.columns.map(()=> '')]})}>Add row</Button><Button variant="ghost" onClick={()=>setContent({...content,columns:[...content.columns,'New column'],rows:content.rows.map((row:any[])=>[...row,''])})}>Add column</Button></div></div>}
 {selected.kind==='chart'&&<div className="artifact-chart">{content.points.map((point:{label:string;value:number},index:number)=><div className="artifact-chart-row" key={index}><Input aria-label={'Series '+(index+1)+' label'} value={point.label} onChange={event=>setContent({points:content.points.map((old:any,position:number)=>position===index?{...old,label:event.target.value}:old)})}/><div className="artifact-chart-bar" style={{width:Math.abs(point.value)/chartMax*100+'%'}} aria-label={point.label+': '+point.value}/><Input type="number" aria-label={'Series '+(index+1)+' value'} value={point.value} onChange={event=>setContent({points:content.points.map((old:any,position:number)=>position===index?{...old,value:Number(event.target.value)}:old)})}/></div>)}<Button variant="ghost" onClick={()=>setContent({points:[...content.points,{label:'New series',value:0}]})}>Add series</Button></div>}
 {selected.kind==='deck'&&<div className="artifact-slides">{content.map((slide:Slide,index:number)=><article key={index} className="artifact-slide"><label>Slide {index+1} title<Input value={slide.title} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,title:event.target.value}:old))}/></label><textarea className="artifact-editor" aria-label={'Slide '+(index+1)+' body'} value={slide.body} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,body:event.target.value}:old))}/><label>Speaker notes<Input value={slide.notes||''} onChange={event=>setContent(content.map((old:Slide,position:number)=>position===index?{...old,notes:event.target.value}:old))}/></label></article>)}<Button variant="ghost" onClick={()=>setContent([...content,{title:'',body:'',notes:''}])}>Add slide</Button></div>}
 {preview&&selected.mime?.startsWith('image/')&&<img className="artifact-preview" src={preview} alt={selected.title}/>}{preview&&selected.mime?.startsWith('audio/')&&<audio controls src={preview} aria-label={selected.title}/>} {preview&&selected.mime?.startsWith('video/')&&<video className="artifact-preview" controls src={preview} aria-label={selected.title}/>}
 <div className="creation-actions">{!selected.mime&&<Button disabled={busy} onClick={()=>act(async()=>{const value=await request<Artifact>('/api/media/artifacts/'+selected.id,json('PUT',{version:selected.version,content}));await choose(value)})}>Save new version</Button>}{(formats[selected.kind]||['original']).map(format=><Button key={format} variant="secondary" disabled={busy} onClick={()=>act(()=>download('/api/media/artifacts/'+selected.id+'/export?format='+format+'&version='+selected.version,selected.title+'.'+(format==='original'?(selected.mime?.split('/')[1]||'bin'):format)))}>Export {format}</Button>)}{selected.kind==='input'&&<Button variant="secondary" disabled={busy} onClick={()=>act(async()=>{const context=await request<{text:string;attachments:unknown[];disclosure:string}>('/api/media/inputs/'+selected.id+'/context',json('POST',{}));setNotice(context.disclosure);onContext?.(context.text,context.attachments)})}>Add converted context to chat</Button>}{selected.kind==='document'&&onContext&&<Button variant="secondary" onClick={()=>onContext(content,[])}>Add text to chat</Button>}</div></>}</div></div>
 <section className="creation-form"><h2>Voice & image creation</h2>{operations.length>0&&<details><summary>Recent provider operations</summary>{operations.map(item=><div className="creation-actions" key={item.id}><span>{item.result?.title||'Provider operation'} · {item.status}</span>{item.result&&<Button variant="secondary" onClick={()=>act(()=>choose(item.result!))}>Inspect output</Button>}{item.status==='unknown'&&<span>The provider outcome is uncertain. Check your provider account before starting a new operation; this request will not be replayed.</span>}</div>)}</details>}<div className="artifact-voice"><Button variant="secondary" disabled={busy} onClick={capture}>{recording?'Stop recording':'Record voice'}</Button>{recording&&<span role="status" className="recording-indicator">Microphone recording · visible until stopped</span>}</div><form onSubmit={event=>{event.preventDefault();void act(generate)}}><div className="creation-fields"><label>Operation<Select aria-label="Operation" value={operation} onChange={event=>{setOperation(event.target.value)}}><option value="image-generate">Generate image</option><option value="image-edit">Edit selected image</option><option value="transcribe">Transcribe selected audio</option><option value="speak">Read text aloud</option></Select></label><label>Configured account<Select aria-label="Configured account" required value={provider} onChange={event=>{setProvider(event.target.value);setModel(providers.find(row=>row.id===event.target.value)?.model||'')}}><option value="">Select an account</option>{providers.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></label><label>Capability model<Input required value={model} onChange={event=>{setModel(event.target.value)}}/></label>{operation==='speak'&&<label>Voice<Input value={voice} onChange={event=>setVoice(event.target.value)}/></label>}</div><label>Prompt or text<Input value={prompt} onChange={event=>{setPrompt(event.target.value)}}/></label><label className="billing-consent"><span><input type="checkbox" checked={billing} onChange={event=>setBilling(event.target.checked)}/> Use this configured account; provider charges may apply.</span></label><Button type="submit" disabled={busy||!billing||!provider||!model}>{busy?'Creating…':'Run selected capability'}</Button>{!providers.length&&<p>Configure an account with image or audio capability in Models & engines.</p>}</form></section></section>
}
