import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {gql} from '../lib/api';
import {useModelFavorites} from '../lib/model-favorites';
type Engine={id:string;label:string;installed:boolean};type Account={id:string;name:string;model?:string};
export default function ModelFavoritesManager({ownerId,engines,accounts,search}:{ownerId:string;engines:Engine[];accounts:Account[];search:string}){
 const {favorites,toggle}=useModelFavorites(ownerId),[catalogs,setCatalogs]=useState<Record<string,string[]>>({}),[pending,setPending]=useState(''),[error,setError]=useState('');const generation=useRef(0);
 useEffect(()=>{generation.current++;setCatalogs({});setPending('');setError('')},[ownerId,JSON.stringify(engines.map(engine=>[engine.id,engine.installed]))]);
 async function discover(engine:Engine){if(pending)return;const ticket=++generation.current;setPending(engine.id);setError('');try{const data=await gql<{engine_models:string[]}>('query($id:String!){engine_models(engine_id:$id)}',{id:engine.id});if(ticket===generation.current)setCatalogs(current=>({...current,[engine.id]:data.engine_models.filter(value=>typeof value==='string').slice(0,500)}))}catch(reason){if(ticket===generation.current)setError(reason instanceof Error?reason.message:'Model catalog could not be loaded.')}finally{if(ticket===generation.current)setPending('')}}
 const catalogRows=[...accounts.flatMap(account=>(account.model||'').split(/[\n,]/).map(value=>value.trim()).filter(Boolean).map(model=>({key:JSON.stringify(['internal',account.id,model]),label:account.name,model}))),...engines.filter(engine=>engine.id!=='internal').flatMap(engine=>(catalogs[engine.id]||[]).map(model=>({key:JSON.stringify([engine.id,null,model]),label:engine.label,model})))];
 const rows=[...new Map(catalogRows.map(row=>[row.key,row])).values()];const available=new Set(rows.map(row=>row.key));
 return <section aria-label="Model favorites"><h2>Model favorites</h2><p className="manager-help">Favorites appear in your conversation model lists on this device. Adding a favorite keeps each session's selected model and running task unchanged.</p>{error&&<p role="alert" className="manager-error">{error}</p>}<div className="model-catalog-actions">{engines.filter(engine=>engine.id!=='internal'&&engine.installed).map(engine=><Button key={engine.id} variant="outline" disabled={!!pending} onClick={()=>void discover(engine)}>{pending===engine.id?'Loading catalog…':'Inspect '+engine.label+' model catalog'}</Button>)}</div>{rows.filter(row=>(row.label+' '+row.model).toLowerCase().includes(search.toLowerCase())).map(row=><article className="manager-item" key={row.key}><div><h3>{row.model}</h3><p>{row.label}</p></div><Button variant="secondary" aria-pressed={favorites.includes(row.key)} aria-label={(favorites.includes(row.key)?'Remove favorite ':'Favorite ')+row.model+' · '+row.label} onClick={()=>{try{toggle(row.key);setError('')}catch{setError('Favorites could not be saved on this device.')}}}>{favorites.includes(row.key)?'Remove favorite':'Favorite'}</Button></article>)}{!rows.length&&<p>Inspect an installed engine's catalog or configure account models to see available favorites.</p>}{favorites.filter(key=>!available.has(key)&&key.toLowerCase().includes(search.toLowerCase())).map(key=>{const [engine,account,model]=JSON.parse(key);return <article className="manager-item" key={key}><div><h3>{model}</h3><p>{account||engine} · catalog not loaded or currently unavailable</p></div><Button variant="outline" onClick={()=>{try{toggle(key)}catch{setError('Favorites could not be saved on this device.')}}}>Remove unavailable favorite</Button></article>})}</section>
}
