import {afterEach,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import Chat from './Chat';
import PresetPicker from './PresetPicker';
import {request,type Session} from '../lib/api';
vi.mock('../lib/api',()=>({request:vi.fn(),gql:vi.fn(),json:(method:string,value:unknown)=>({method,body:JSON.stringify(value)})}));
vi.mock('./VoiceControls',()=>({default:()=>null}));
afterEach(()=>{cleanup();vi.clearAllMocks()});
const preset={id:'approved-preset',name:'Source guide',description:'Explain selected code',engine:'internal',workspace_revision:'reviewed-revision'};
const session:Session={id:'conversation-a',title:'A',engine:'internal',mode:'ask',pinned:false,archived:false,draft_text:'',revision:1,scroll:0,updated_at:1,turns:[]};
function transport(){vi.mocked(request).mockImplementation(async(path)=>path.startsWith('/api/workspace/presets')?{presets:[preset]} as any:path.includes('available-extensions')?{extensions:[]} as any:path==='/api/runners'?{runners:[]} as any:path.includes('runner-agents')?{accounts:[]} as any:{...session} as any)}
it('names explicit new-conversation selection and sends only the chosen stable preset ID',()=>{const onChange=vi.fn();render(<PresetPicker presets={[preset]} onChange={onChange} label="New conversation agent preset"/>);fireEvent.change(screen.getByLabelText('New conversation agent preset'),{target:{value:preset.id}});expect(onChange).toHaveBeenCalledWith(preset.id)});
it('changes only the selected conversation and exposes explicit preset renewal',async()=>{transport();const onRefresh=vi.fn();const {rerender}=render(<Chat session={session} providers={[]} engines={[]} onSelect={()=>{}} onRefresh={onRefresh} onError={()=>{}}/>);await waitFor(()=>expect(screen.getByRole('option',{name:'Source guide · internal'})).toBeInTheDocument());fireEvent.change(screen.getByLabelText('Session agent preset'),{target:{value:preset.id}});await waitFor(()=>expect(request).toHaveBeenCalledWith('/api/workspace/sessions/conversation-a',expect.objectContaining({method:'PATCH'})));const change=vi.mocked(request).mock.calls.find(([,init])=>init?.method==='PATCH');expect(JSON.parse(change![1]!.body as string)).toEqual({revision:1,changes:{custom_agent_id:preset.id}});rerender(<Chat session={{...session,custom_agent_id:preset.id}} providers={[]} engines={[]} onSelect={()=>{}} onRefresh={onRefresh} onError={()=>{}}/>);fireEvent.click(screen.getByText('Refresh preset binding'));await waitFor(()=>expect(vi.mocked(request).mock.calls.filter(([,init])=>init?.method==='PATCH')).toHaveLength(2));expect(vi.mocked(request).mock.calls.every(([path])=>!path.includes('conversation-b'))).toBe(true)});
it('prevents preset retargeting during an active run and keeps unavailable IDs inspectable',async()=>{transport();render(<Chat session={{...session,custom_agent_id:'unavailable',turns:[{id:'turn',prompt:'Active',task:{id:'task',status:'running',engine:'internal',events:[],approvals:[],result:''} as any} as any]}} providers={[]} engines={[]} onSelect={()=>{}} onRefresh={()=>{}} onError={()=>{}}/>);expect(screen.getByLabelText('Session agent preset')).toBeDisabled();expect(await screen.findByText('Selected preset unavailable')).toBeInTheDocument();expect(screen.getByText('Refresh preset binding')).toBeDisabled()});
