import {useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
type Account={id:string;name:string;kind:string;base_url:string;model:string;capabilities:string[]};
const choices=[['shell','Shell tools'],['functions','Function tools'],['computer','Computer tools'],['image','Image generation and editing'],['audio','Audio transcription and speech']];
export default function ProviderAccountForm({account,onSave,onCancel,busy}:{account?:Account;onSave:(input:Account&{api_key:string|null})=>Promise<unknown>;onCancel?:()=>void;busy:boolean}){
 const [id,setId]=useState(account?.id||''),[name,setName]=useState(account?.name||''),[url,setUrl]=useState(account?.base_url||'https://api.openai.com/v1'),[model,setModel]=useState(account?.model||''),[secret,setSecret]=useState(''),[capabilities,setCapabilities]=useState<string[]>(account?.capabilities||['shell','functions']);
 return <form className="manager-form" aria-label={account?'Edit provider account':'Add provider account'} onSubmit={event=>{event.preventDefault();void onSave({id:id.trim(),name,kind:account?.kind||'openai-compatible',base_url:url.trim(),model,capabilities,api_key:secret||null}).then(result=>{if(result!==null)setSecret('')})}}><label>Account ID<Input required value={id} disabled={busy||!!account} onChange={event=>setId(event.target.value)}/></label><label>Display name<Input value={name} disabled={busy} onChange={event=>setName(event.target.value)}/></label><label>Provider API address<Input required type="url" value={url} disabled={busy} onChange={event=>setUrl(event.target.value)}/></label><label>{account?'Replace API key (leave blank to keep current key)':'API key'}<Input type="password" autoComplete="new-password" value={secret} disabled={busy} onChange={event=>setSecret(event.target.value)}/></label><label>Default for future sessions<Input value={model} disabled={busy} onChange={event=>setModel(event.target.value)}/></label><fieldset className="provider-capabilities"><legend>Declared account capabilities</legend>{choices.map(([value,label])=><label key={value}><span><input type="checkbox" checked={capabilities.includes(value)} disabled={busy} onChange={event=>setCapabilities(prior=>event.target.checked?[...prior,value]:prior.filter(item=>item!==value))}/>{label}</span></label>)}</fieldset><p className="manager-help">These declarations make the account available for matching operations. Verify each model and your account entitlement; declaring a capability does not prove provider support or authorize charges.</p><div className="manager-item-actions"><Button type="submit" disabled={busy||!id.trim()||!capabilities.length}>{account?'Save account changes':'Save account'}</Button>{onCancel&&<Button type="button" variant="secondary" disabled={busy} onClick={onCancel}>Cancel account edit</Button>}</div></form>;
}
