import {useEffect,useRef,useState} from 'react';
import {Select} from '../components/ui/select';
import {json,request,type Session} from '../lib/api';
type Option={id:string;name?:string;category?:string;type?:string;currentValue?:string;options?:{value:string;name?:string}[]};
type Configuration={config_options?:Option[];model_configurations?:Record<string,{config_options?:Option[]}>;stale?:boolean;refresh_error?:string|null};
export default function ReasoningPicker({session,onUpdated,onError,disabled=false}:{session:Session;onUpdated:(session:Session)=>void;onError:(error:unknown)=>void;disabled?:boolean}){
 const [configuration,setConfiguration]=useState<Configuration|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const selection=JSON.stringify([session.id,session.engine,session.model,session.runner_id]);
 const current=useRef({selection,generation:0,operation:0});if(current.current.selection!==selection)current.current={selection,generation:current.current.generation+1,operation:current.current.operation+1};
 useEffect(()=>{let cancelled=false;setSaving(false);setConfiguration(null);setLoading(false);if(session.engine==='internal'||session.runner_id)return;setLoading(true);request<Configuration>('/api/workspace/sessions/'+session.id+'/reasoning').then(result=>{if(!cancelled)setConfiguration(result)}).catch(error=>{if(!cancelled)onError(error)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[selection]);
 const selected=session.model?configuration?.model_configurations?.[session.model]:configuration;
 const options=(selected?.config_options||[]).filter(option=>['thought_level','reasoning','effort'].includes(option.category||'')&&option.type==='select'&&option.options?.length);
 const unavailable=!options.length||configuration?.stale||!!configuration?.refresh_error;
 const choose=async(id:string,value:string)=>{const sessionId=session.id,generation=current.current.generation,operation=++current.current.operation;const owns=()=>current.current.generation===generation&&current.current.operation===operation;setSaving(true);try{const reasoning_config={...session.reasoning_config};if(value)reasoning_config[id]=value;else delete reasoning_config[id];const result=await request<Session>('/api/workspace/sessions/'+sessionId,json('PATCH',{revision:session.revision,changes:{reasoning_config}}));if(owns())onUpdated(result)}catch(error){if(owns())onError(error)}finally{if(owns())setSaving(false)}};
 if(unavailable)return <label>Reasoning<Select aria-label="Reasoning" disabled value=""><option value="">{loading?'Loading supported reasoning…':configuration?.stale?'Refresh engine capabilities':'Engine default'}</option></Select><small>{session.engine==='internal'||session.runner_id?'This account has no advertised reasoning selector.':configuration?.refresh_error?'Reasoning discovery failed; refresh this engine in Managers.':'This engine/model has no verified reasoning choices.'}</small></label>;
 return <div>{options.map(option=><label key={option.id}>{option.name||'Reasoning'}<Select aria-label={option.name||'Reasoning'} value={session.reasoning_config?.[option.id]||''} disabled={disabled||loading||saving} onChange={event=>void choose(option.id,event.target.value)}><option value="">Engine default{option.currentValue?' · '+option.currentValue:''}</option>{option.options?.map(value=><option key={value.value} value={value.value}>{value.name||value.value}</option>)}</Select></label>)}<small>Applies to the next turn. Active turns retain their settings.</small></div>
}
