import {useObservationActive} from '../lib/use-observation-active';
import {useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Select} from '../components/ui/select';
import {gql,json,request,type Project} from '../lib/api';
import {download,transfer} from '../lib/transfers';
import {mediaIntent,clearMediaIntent} from '../lib/media-intent';
import './creation.css';
type Runner={id:string;project:string;status:string;expires:number;configuration:{image:string;endpoint?:string;cpu:number;memory_mb:number;network:string}};
type Job={id:string;status:string;started:number;result?:{stdout?:string;error?:string;exit_code?:number}};
export default function Runners({projectId,ownerId}:{projectId:string|null;ownerId:string}){
 const [rows,setRows]=useState<Runner[]>([]),[selected,setSelected]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[enroll,setEnroll]=useState(false);
 const [image,setImage]=useState(''),[endpoint,setEndpoint]=useState(''),[network,setNetwork]=useState('none'),[cpu,setCpu]=useState('1'),[memory,setMemory]=useState('512'),[lease,setLease]=useState('3600'),[command,setCommand]=useState(''),[seconds,setSeconds]=useState('60'),[secretName,setSecretName]=useState(''),[secretRef,setSecretRef]=useState(''),[resultPath,setResultPath]=useState('');
 const [projects,setProjects]=useState<Project[]>([]),[chosenProject,setChosenProject]=useState('');
 const active=useObservationActive(),epoch=useRef(0);
 const enrollmentProject=projectId||chosenProject;
 useEffect(()=>{let live=true;void gql<{projects:Project[]}>('{projects{id name path}}').then(value=>{if(live)setProjects(value.projects)}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[ownerId]);
 const current=rows.find(row=>row.id===selected);
 async function load(generation=epoch.current){const [nextRows,nextJobs]=await Promise.all([request<Runner[]>('/api/runners'),selected?request<Job[]>('/api/runners/'+selected+'/jobs'):Promise.resolve([])]);if(generation!==epoch.current)return;setRows(nextRows);setJobs(nextJobs)}
 useEffect(()=>{const generation=++epoch.current;setJobs([]);setBusy(false);if(!active)return;let busy=false;const poll=async()=>{if(busy||generation!==epoch.current)return;busy=true;try{await load(generation)}catch(error){if(generation===epoch.current)setError(String(error))}finally{busy=false}};void poll();const timer=setInterval(()=>void poll(),3000);return()=>{epoch.current++;clearInterval(timer)}},[selected,ownerId,active]);
 async function act(action:()=>Promise<unknown>){const generation=epoch.current;setBusy(true);setError('');try{await action();if(generation===epoch.current)await load(generation)}catch(error){if(generation===epoch.current)setError(error instanceof Error?error.message:String(error))}finally{if(generation===epoch.current)setBusy(false)}}
 async function runJob(){
  let argv:unknown;try{argv=JSON.parse(command)}catch{throw new Error('Command must be an argument array, for example ["python","main.py"]')}
  const args={runner_id:selected,argv,seconds:Number(seconds),secrets:secretName&&secretRef?{[secretName]:secretRef}:{}};
  const intent=await mediaIntent(ownerId,current?.project||projectId,args,'runner-job');
  const outcome=await request<Job>('/api/runners/'+selected+'/jobs',json('POST',{...args,runner_id:undefined,request_id:intent.id}));
  if(outcome.status==='outcome-unknown')throw new Error('The prior job outcome is unknown. Inspect its activity and results before starting another job.');
  if(outcome.status==='running')return;
  clearMediaIntent(intent.key,intent.id);
 }
 return <section className="creation-page" aria-label="Dedicated runners"><div className="creation-heading"><div><h1>Dedicated runners</h1><p>Your infrastructure. TermX sessions, permissions and audit history.</p></div><Button onClick={()=>setEnroll(!enroll)}>Enroll runner</Button></div>
 {error&&<p role="alert" className="inline-error">{error}<Button variant="ghost" onClick={()=>void act(()=>load())}>Retry runner refresh</Button></p>}
 {enroll&&<form className="creation-form" onSubmit={event=>{event.preventDefault();void act(async()=>{if(!enrollmentProject)throw new Error('Choose a project before enrolling');const row=await request<Runner>('/api/runners',json('POST',{project_id:enrollmentProject,image,endpoint,network,cpu:Number(cpu),memory_mb:Number(memory),lease_seconds:Number(lease)}));setSelected(row.id);setEnroll(false)})}}><h2>Provision a dedicated container</h2><p>Choose an image already installed on your Docker host. Remote hosts use your existing SSH keys and verified host keys. Workspace files are copied explicitly.</p><label>Project<Select aria-label="Runner project" value={enrollmentProject} disabled={!!projectId} onChange={event=>setChosenProject(event.target.value)}><option value="">Choose a project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</Select></label><label>Container image<Input required value={image} onChange={event=>setImage(event.target.value)} placeholder="Image name or immutable digest"/></label><label>Execution host<Input value={endpoint} onChange={event=>setEndpoint(event.target.value)} placeholder="Leave empty for this machine, or ssh://user@host"/></label><div className="creation-fields"><label>CPU cores<Input type="number" min="0.1" max="8" step="0.1" value={cpu} onChange={event=>setCpu(event.target.value)}/></label><label>Memory MiB<Input type="number" min="64" max="8192" value={memory} onChange={event=>setMemory(event.target.value)}/></label><label>Lease seconds<Input type="number" min="10" max="86400" value={lease} onChange={event=>setLease(event.target.value)}/></label><label>Network<Select value={network} onChange={event=>setNetwork(event.target.value)}><option value="none">Isolated · no network</option><option value="bridge">Allow outbound network</option></Select></label></div><Button type="submit" disabled={busy||!enrollmentProject}>{busy?'Provisioning…':'Create scoped runner'}</Button></form>}
 <div className="runner-records">{rows.map(row=><article className={'runner-record '+(selected===row.id?'selected':'')} key={row.id}><div className="creation-heading"><h2>{row.configuration.image}</h2><span className={'status-badge '+row.status}>{row.status}</span></div><p>{row.configuration.endpoint||'This machine'} · Dedicated container</p><dl className="runner-facts"><div><dt>Capacity</dt><dd>{row.configuration.cpu} CPU · {row.configuration.memory_mb} MiB</dd></div><div><dt>Project access</dt><dd>{row.project===projectId?'Selected project':row.project}</dd></div><div><dt>Network</dt><dd>{row.configuration.network==='none'?'Isolated':'Outbound enabled'}</dd></div><div><dt>Lease expires</dt><dd>{new Date(row.expires*1000).toLocaleString()}</dd></div></dl><div className="creation-actions"><Button variant="secondary" onClick={()=>setSelected(row.id)}>View activity</Button><Button variant="ghost" disabled={busy||row.status!=='ready'} onClick={()=>act(()=>request('/api/runners/'+row.id+'/stop',json('POST',{})))}>Stop runner</Button><Button variant="ghost" disabled={busy||row.status==='removed'} onClick={()=>act(()=>request('/api/runners/'+row.id,{method:'DELETE'}))}>Tear down</Button></div></article>)}</div>
 {!rows.length&&!enroll&&<p className="creation-empty">Enroll a dedicated runner for this project to start remote work.</p>}
 {current&&<section className="creation-form"><h2>Activity · {current.configuration.endpoint||'This machine'}</h2><label>Copy workspace tar archive<Input type="file" accept=".tar,.tar.gz,application/x-tar" disabled={busy||current.status!=='ready'} onChange={event=>{const file=event.target.files?.[0];if(file)void act(()=>transfer('/api/runners/'+selected+'/workspace',{method:'POST',body:file,headers:{'Content-Type':'application/x-tar'}}))}}/></label><form onSubmit={event=>{event.preventDefault();void act(runJob)}}><label>Command arguments<Input value={command} onChange={event=>setCommand(event.target.value)} placeholder={'["python", "main.py"]'} required/></label><label>Time budget in seconds<Input type="number" min="1" max="3600" value={seconds} onChange={event=>setSeconds(event.target.value)}/></label><details><summary>Inject a scoped credential</summary><label>Environment name<Input value={secretName} placeholder="TERMX_SECRET_TOKEN" onChange={event=>setSecretName(event.target.value)}/></label><label>Host credential reference<Input value={secretRef} onChange={event=>setSecretRef(event.target.value)}/></label><p>Only the reference is saved. Values are injected into this job and redacted from displayed logs.</p></details><Button type="submit" disabled={busy||current.status!=='ready'}>Run on this runner</Button></form><div className="creation-actions"><Input aria-label="Result file path" value={resultPath} onChange={event=>setResultPath(event.target.value)} placeholder="Result path inside runner workspace"/><Button variant="secondary" disabled={!resultPath||busy} onClick={()=>act(()=>download('/api/runners/'+selected+'/results?path='+encodeURIComponent(resultPath),'runner-results.tar'))}>Download results</Button></div>{jobs.map(job=><article key={job.id} className="runner-job"><h3>{job.status} <small>{new Date(job.started*1000).toLocaleString()}</small></h3>{job.result?.error&&<p role="status">{job.result.error}</p>}{job.result?.stdout&&<pre aria-label="Runner output">{job.result.stdout}</pre>}</article>)}</section>}
 <p className="creation-footnote">Bring your own VM or container. Leases stop work on expiry or authorization changes. Existing local runs remain on their chosen machine.</p></section>
}
