import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {SafetyManager} from './SafetyManager';
import {request} from '../lib/api';
vi.mock('../lib/api',()=>({request:vi.fn()}));
const api=vi.mocked(request);
afterEach(()=>{cleanup();vi.resetAllMocks()});
const report={id:'report',provider_id:'fixture',model:'small',reviewer_version:'pinned-v1',qualified:true,activation_eligible:false,false_allow_count:0,case_count:21,structured_valid_count:21,escalation_rate:0.9,p95_latency_ms:25,created_at:Date.now()/1000,limit:'Frozen fixture scope.',usage:{input_tokens:2100,cached_input_tokens:840,output_tokens:210,missing_usage_requests:0},cost:{reported:true,amount:'0.00462',currency:'USD',reason:'Estimate, not a billed charge.',pricing:{currency:'USD',input_per_million:'2',cached_input_per_million:'0.5',output_per_million:'8',source:'Explicit test pricing',effective_date:'2026-01-01',version:'price-v1'}}};
function setup(){api.mockImplementation(async(path)=>{if(path==='/api/browser/reviewer')return {configuration:{provider_id:'fixture',model:'small',version:'pinned-v1'},evaluations:[report],active:false};if(path==='/api/browser/reviews'||path==='/api/browser/rules')return [];if(path==='/auth/me')return {principal:{scopes:['host-admin']}};if(path==='/graphql')return {data:{agent_providers:[{id:'fixture',name:'Fixture account',kind:'openai-compatible',model:'small',secret_configured:true}]}};if(path==='/api/browser/reviewer/evaluate')return report;throw Error(path)})}
it('requires supplied pricing fields, freezes exact submitted rates, and does not activate stale account qualification',async()=>{
 setup();render(<SafetyManager/>);fireEvent.click(await screen.findByRole('button',{name:'Configure'}));expect(screen.getByRole('button',{name:'Activate qualified reviewer'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox',{name:'Include an administrator pricing snapshot'}));
 expect(screen.getByLabelText('Input rate per million tokens')).toHaveValue('');fireEvent.click(screen.getByRole('button',{name:'Evaluate 21 safety cases'}));await screen.findByRole('alert');expect(api).not.toHaveBeenCalledWith('/api/browser/reviewer/evaluate',expect.anything());
 for(const [label,value] of [['Currency (3 uppercase letters)','USD'],['Input rate per million tokens','2'],['Cached input rate per million tokens','0.5'],['Output rate per million tokens','8'],['Pricing source','Explicit test pricing'],['Pricing effective date','2026-01-01'],['Pricing snapshot version','price-v1']])fireEvent.change(screen.getByLabelText(label),{target:{value}});
 fireEvent.click(screen.getByRole('button',{name:'Evaluate 21 safety cases'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/api/browser/reviewer/evaluate',expect.objectContaining({body:JSON.stringify({provider_id:'fixture',model:'small',version:'pinned-v1',pricing:report.cost.pricing})})));expect(screen.getByRole('button',{name:'Activate qualified reviewer'})).toBeDisabled();
});
it('distinguishes transparent estimated cost and usage from an actual bill',async()=>{setup();render(<SafetyManager/>);await screen.findByText(/Estimated cost: 0.00462 USD/);expect(screen.getByText(/2100 input · 840 known cached input · 210 output/)).toBeInTheDocument();expect(screen.getByText(/Estimates are not billed charges/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Export qualification report'})).toBeEnabled()});
