import {useCallback,useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request} from '../lib/api';
import './browser.css';
type Config={provider_id:string;model:string;version:string;evaluation_id:string};
type Evaluation={id:string;provider_id:string;model:string;reviewer_version:string;qualified:boolean;false_allow_count:number;case_count:number;structured_valid_count:number;escalation_rate:number;p95_latency_ms:number;created_at:number;limit:string};
type Provider={id:string;name:string;model:string;kind:string;secret_configured:boolean};
type Review={id:string;status:string;decision:string;reason:string;target:string;effect:string;tool_id:string;project_id:string;expires_at:number;run_id:string};
type Rule={id:string;decision:string;expires_at:number;scope:{project_id:string;tool_id:string;target:string;intended_effect:string;run_id:string}};
const post=(body:unknown):RequestInit=>({method:'POST',body:JSON.stringify(body)});
export function SafetyManager(){
 const [state,setState]=useState<{configuration:Config|null;evaluations:Evaluation[];active:boolean}|null>(null),[providers,setProviders]=useState<Provider[]>([]),[reviews,setReviews]=useState<Review[]>([]),[rules,setRules]=useState<Rule[]>([]);
 const [providerId,setProviderId]=useState(''),[version,setVersion]=useState(''),[configure,setConfigure]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[admin,setAdmin]=useState(false);
 const provider=providers.find(p=>p.id===providerId);
 const load=useCallback(async()=>{
  const [configuration,history,remembered,me]=await Promise.all([request<{configuration:Config|null;evaluations:Evaluation[];active:boolean}>('/api/browser/reviewer'),request<Review[]>('/api/browser/reviews'),request<Rule[]>('/api/browser/rules'),request<{principal:{scopes:string[]}}>('/auth/me')]);
  setState(configuration);setReviews(history);setRules(remembered);const canConfigure=!!me.principal?.scopes?.includes('host-admin');setAdmin(canConfigure);
  if(canConfigure){const body=await request<{data?:{agent_providers:Provider[]};errors?:{message:string}[]}>('/graphql',post({query:'query { agent_providers { id name kind model secret_configured } }'}));if(body.errors)throw new Error(body.errors[0]?.message||'Provider catalog unavailable');setProviders((body.data?.agent_providers||[]).filter(p=>['openai','openai-compatible'].includes(p.kind)));}
  setProviderId(current=>current||configuration.configuration?.provider_id||'');setVersion(current=>current||configuration.configuration?.version||'');
 },[]);
 const run=useCallback(async(job:()=>Promise<unknown>)=>{setBusy(true);setError('');setMessage('');try{await job()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}},[]);
 useEffect(()=>{void run(load)},[load,run]);
 const evaluate=()=>run(async()=>{if(!provider?.model||!version.trim())throw new Error('Choose a configured model and pin its reviewer version.');const report=await request<Evaluation>('/api/browser/reviewer/evaluate',post({provider_id:provider.id,model:provider.model,version:version.trim()}));setMessage(report.qualified?'Qualification passed. You can activate this pinned reviewer.':'Qualification failed. This model cannot approve actions.');await load()});
 const activate=()=>run(async()=>{await request('/api/browser/reviewer',post({provider_id:providerId,model:provider?.model,version:version.trim()}));setConfigure(false);setMessage('Pinned reviewer activated.');await load()});
 const qualified=state?.evaluations.some(e=>e.qualified&&e.provider_id===providerId&&e.model===provider?.model&&e.reviewer_version===version.trim()&&Date.now()/1000-e.created_at<30*86400);
 const remember=(id:string,decision:string)=>run(async()=>{await request('/api/browser/rules',post({action_id:id,decision,expires_in:3600}));await load()});
 return <section className="safety-manager" aria-label="Safety and Auto Review manager">
  <header><h2>Safety & Auto Review</h2><p>Less interruption. The same security boundaries.</p></header>
  {error&&<p className="browser-error" role="alert">{error}</p>}{message&&<p role="status" className="safety-notice">{message}</p>}
  <div className="safety-overview"><div><span className="browser-badge">{state?.active?'Auto Review enabled':'Safe rules active'}</span><span>{state?.configuration?`${state.configuration.model} · configured provider`:'A qualified review model has not been selected'}</span></div><div><p>Approvals only. No tool execution, credential access or policy editing.</p>{admin&&<Button variant="secondary" onClick={()=>setConfigure(!configure)}>Configure</Button>}</div></div>
  <p className="safety-order">Enforced rules → Remembered consent → Auto Review → You</p><p>The host validates scope and the exact action again before execution.</p>
  {configure&&admin&&<section className="safety-config" aria-label="Pinned reviewer configuration"><h3>Choose an evaluated reviewer</h3><p>Use an existing configured provider account. Evaluation sends 21 frozen safety cases to that account; its configured billing applies.</p><label>Provider<select value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Choose configured provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Configured model<Input readOnly value={provider?.model||''}/></label><label>Reviewer version<Input value={version} onChange={e=>setVersion(e.target.value)} placeholder="Pin model revision and policy version"/></label><div className="browser-actions"><Button variant="secondary" disabled={busy||!providerId||!version.trim()} onClick={()=>void evaluate()}>{busy?'Evaluating…':'Evaluate 21 safety cases'}</Button><Button disabled={busy||!qualified} onClick={()=>void activate()}>Activate qualified reviewer</Button>{state?.active&&<Button variant="ghost" disabled={busy} onClick={()=>void run(async()=>{await request('/api/browser/reviewer',{method:'DELETE'});await load()})}>Disable model review</Button>}</div><p>Required review failures pause the affected action. No larger model or alternate billing account is selected automatically.</p></section>}
  <div className="safety-explanation"><h3>What happens automatically</h3><p>Navigate approved tabs · Inspect pages · Scroll and find · Verify results</p><h3>What still needs you</h3><p>Publishing, payments, destructive actions, permission changes, uncertain effects and unapproved data destinations.</p><small>A model recommendation never overrides a sandbox or administrator restriction.</small></div>
  <section><h3>Recent decisions</h3>{!state?<p>Loading review history…</p>:!reviews.length?<p className="safety-empty">No actions have been reviewed yet.</p>:<div className="safety-table-wrap"><table className="safety-table"><thead><tr><th>Decision</th><th>Exact operation</th><th>Current scope</th><th>Rule</th></tr></thead><tbody>{reviews.slice(-50).reverse().map(r=><tr key={r.id}><td><span className={`browser-badge ${r.decision==='NEEDS_USER'?'attention':''}`}>{r.decision==='ALLOW'?'Allowed':r.decision==='BLOCK'?'Blocked':'Needs you'}</span></td><td>{r.tool_id}<small>{r.reason.replaceAll('_',' ')}</small></td><td>{r.target}<small>Project {r.project_id||'Unassigned'} · task {r.run_id.slice(0,8)}</small></td><td><Button variant="ghost" size="sm" disabled={busy} onClick={()=>void remember(r.id,'BLOCK')}>Remember deny · 1h</Button>{!['send','publish','purchase','delete','credential','privilege','export','upload','unknown'].includes(r.effect)&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void remember(r.id,'ALLOW')}>Remember scope · 1h</Button>}</td></tr>)}</tbody></table></div>}</section>
  <section><h3>Remembered rules</h3><p>Rules stay bound to their user, session, project, task, browser profile, origin and policy version.</p>{!rules.length?<p className="safety-empty">No remembered permissions.</p>:rules.map(rule=><div className="safety-rule" key={rule.id}><span>{rule.decision} · {rule.scope.tool_id}</span><span>{rule.scope.target}</span><small>Expires {new Date(rule.expires_at*1000).toLocaleString()}</small><Button variant="ghost" disabled={busy} onClick={()=>void run(async()=>{await request(`/api/browser/rules/${rule.id}`,{method:'DELETE'});await load()})}>Revoke</Button></div>)}</section>
  <section><h3>Reviewer qualification</h3>{!state?.evaluations.length?<p className="safety-empty">No model evaluations recorded.</p>:state.evaluations.map(e=><article className="safety-evaluation" key={e.id}><strong>{e.model} · {e.qualified?'Qualified':'Not qualified'}</strong><p>{e.false_allow_count} false allows across {e.case_count} frozen cases · {e.structured_valid_count} valid structured verdicts · p95 {e.p95_latency_ms} ms · escalation {Math.round(e.escalation_rate*100)}%</p><small>{e.limit} Provider billing costs are not reported by this evaluation.</small></article>)}</section>
  <section className="safety-explanation"><h3>Private login and takeover</h3><p>Takeover invalidates queued permits immediately. Private login also pauses agent and reviewer observations, page context and recordings. Resume requires a fresh task handoff and observation.</p><h3>Engine coverage</h3><p>Browser handoff works with TermX Agent and Claude Browser conversations. Choose Browser workflow before starting a Claude conversation. Codex and ACP handoffs are unavailable until their engines expose enforceable tool restrictions. Managed coding actions also use this broker: TermX Agent typed tools and Claude pre-execution hooks, Codex emitted approval requests, and ACP host file/terminal callbacks and permission requests. Codex sandbox fast paths retain native policy; ACP runner-owned tools require the runner’s permission cooperation.</p></section>
 </section>
}
export default SafetyManager;
