import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {json,request,type Session} from '../lib/api';
import {useObservationActive} from '../lib/use-observation-active';
import './schedules.css';

type Spec={kind:string;seconds?:number;time?:string;timezone?:string;expression?:string;at?:number};
type Schedule={id:string;revision:number;goal_id:string;grant_id:string;prompt:string;spec:Spec;enabled:boolean;archived?:boolean;state:string;runbook_id?:string;reason?:string;next_run:number|null;missed:string;overlap:string};
type Run={id:string;schedule_id:string;goal_id:string;task_id?:string;status:string;task_status?:string;reason?:string;due:number;manual?:boolean;runbook_run_id?:string;step_results?:{output?:string}[]};
type Catalog={schedule:Schedule[];schedule_run:Run[];goal:{id:string;conversation_id:string;success_criteria:string;runs_started:number;max_runs:number}[];delegation:{id:string;expires_at:number;used_runs:number;max_runs:number;revoked:boolean;runbook?:{name:string;steps:{command:string;confirm?:boolean}[]}}[]};
const empty:Catalog={schedule:[],schedule_run:[],goal:[],delegation:[]};
const date=(n?:number|null)=>n?new Date(n*1000).toLocaleString():'—';
const describe=(s:Spec)=>s.kind==='cron'?`${s.expression} · ${s.timezone}`:s.kind==='daily'?`Daily at ${s.time} · ${s.timezone}`:s.kind==='once'?`Once · ${date(s.at)}`:`Every ${(s.seconds||0)/60} minutes`;

export default function ScheduleManager({projectId,sessionId,search='',version=0}:{projectId:string|null;sessionId:string|null;search?:string;version?:number}){
 const [data,setData]=useState<Catalog>(empty),[sessions,setSessions]=useState<Session[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<Schedule|'new'|null>(null),[selected,setSelected]=useState(''),[conversation,setConversation]=useState(sessionId||'');
 const [taskKind,setTaskKind]=useState('agent'),[command,setCommand]=useState('');
 const [prompt,setPrompt]=useState(''),[criteria,setCriteria]=useState(''),[kind,setKind]=useState('daily'),[time,setTime]=useState('09:00'),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone),[cron,setCron]=useState('0 9 * * 1-5'),[minutes,setMinutes]=useState('60'),[at,setAt]=useState(''),[missed,setMissed]=useState('skip'),[overlap,setOverlap]=useState('skip'),[runs,setRuns]=useState('10'),[days,setDays]=useState('7'),[seconds,setSeconds]=useState('3600'),[consent,setConsent]=useState(false),[preview,setPreview]=useState<number[]>([]),[archived,setArchived]=useState(false);
 const active=useObservationActive(),epoch=useRef(0),intent=useRef({key:'',payload:''});
 const scope=projectId?'?project_id='+encodeURIComponent(projectId):'';
 const load=useCallback(async(generation=epoch.current)=>{const [catalog,chats]=await Promise.all([request<Catalog>('/api/workspace/automations'+scope),request<{sessions:Session[]}>('/api/workspace/sessions'+scope)]);if(generation===epoch.current){setData(catalog);setSessions(chats.sessions);setLoading(false)}},[scope]);
 useEffect(()=>{const generation=++epoch.current;setData(empty);setLoading(true);setBusy(false);setEditing(null);setSelected('');return()=>{if(epoch.current===generation)epoch.current++}},[scope]);
 useEffect(()=>{if(!active)return;let stopped=false,pending=false;const generation=epoch.current;const poll=async()=>{if(pending||stopped)return;pending=true;try{await load(generation)}catch(e){if(!stopped){setError(String(e));setLoading(false)}}finally{pending=false}};void poll();const timer=setInterval(()=>void poll(),5000);return()=>{stopped=true;clearInterval(timer)}},[active,load,version]);
 const spec=():Spec=>kind==='interval'?{kind,seconds:Number(minutes)*60}:kind==='cron'?{kind,expression:cron,timezone}:kind==='once'?{kind,at:new Date(at).getTime()/1000}:{kind,time,timezone};
 useEffect(()=>setPreview([]),[kind,time,timezone,cron,minutes,at]);
 async function act(job:()=>Promise<unknown>,message:string){if(busy)return;setBusy(true);setError('');setNotice('');try{await job();setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function edit(row:Schedule|'new') {setEditing(row);setPreview([]);setConsent(false);setError('');if(row==='new'){setTaskKind('agent');setCommand('');setPrompt('');setCriteria('');setConversation(sessionId||'');return}setPrompt(row.prompt);setKind(row.spec.kind);setTime(row.spec.time||'09:00');setTimezone(row.spec.timezone||'UTC');setCron(row.spec.expression||'0 9 * * 1-5');setMinutes(String((row.spec.seconds||3600)/60));setAt(row.spec.at?new Date(row.spec.at*1000-new Date(row.spec.at*1000).getTimezoneOffset()*60000).toISOString().slice(0,16):'');setMissed(row.missed);setOverlap(row.overlap)}
 async function save(){const current=spec();await request('/api/workspace/schedules/preview',json('POST',current));if(editing==='new'){
   const body={...(taskKind==='command'?{command}:{}),conversation_id:conversation,success_criteria:criteria,max_runs:Number(runs),limits:{max_steps:128,max_seconds:Number(seconds),shell_timeout_s:120,max_parallel_subagents:3,max_subagents_total:8},prompt,spec:current,grant_days:Number(days),missed,overlap};
   const payload=JSON.stringify(body);if(intent.current.payload!==payload)intent.current={key:crypto.randomUUID(),payload};
   await request('/api/workspace/automations',json('POST',{...body,request_id:intent.current.key}));intent.current={key:'',payload:''};
  }else if(editing)await request('/api/workspace/schedules/'+editing.id,json('PATCH',{revision:editing.revision,prompt,spec:current,missed,overlap}));setEditing(null);
 }
 const rows=data.schedule.filter(s=>(archived||!s.archived)&&[s.prompt,describe(s.spec),s.state].join(' ').toLowerCase().includes(search.toLowerCase()));
 const current=data.schedule.find(s=>s.id===selected),goal=data.goal.find(g=>g.id===current?.goal_id),grant=data.delegation.find(g=>g.id===current?.grant_id);
 return <section aria-label="Scheduled tasks" className="schedule-manager">
  <div className="schedule-heading"><div><h2>Scheduled tasks</h2><p>Run work on this host while your apps are closed. The host must be awake and running.</p></div><Button onClick={()=>edit('new')}>New scheduled task</Button></div>
  {error&&<p role="alert" className="manager-error">{error} <Button variant="secondary" onClick={()=>void act(()=>load(),'Schedules refreshed')}>Retry schedules</Button></p>}{notice&&<p role="status">{notice}</p>}
  <label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Show archived schedules</label>
  {loading?<p>Loading schedules…</p>:!rows.length?<div className="manager-empty">No scheduled tasks. Choose a conversation and set when it should run.</div>:<div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>Task</th><th>Schedule</th><th>Status</th><th>Next run</th><th>Controls</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button className="schedule-name" onClick={()=>setSelected(row.id)}>{row.prompt}</button></td><td>{describe(row.spec)}</td><td>{row.state.replaceAll('_',' ')}{row.runbook_id?' · command':''}</td><td>{row.enabled?date(row.next_run):'—'}</td><td><div className="schedule-actions"><Button variant="secondary" disabled={busy||row.archived} onClick={()=>void act(async()=>{const run=await request<Run>(`/api/workspace/schedules/${row.id}/run`,json('POST',{revision:row.revision}));if(run.status==='needs_attention')throw new Error(run.reason||'Run needs attention; inspect its history')},'Run submitted')}>Run now</Button><Button variant="ghost" disabled={busy||row.archived} onClick={()=>void act(()=>request('/api/workspace/schedules/'+row.id,json('PATCH',{revision:row.revision,enabled:!row.enabled})),'Schedule updated')}>{row.enabled?'Pause':'Resume'}</Button><Button variant="ghost" disabled={row.archived} onClick={()=>edit(row)}>Edit</Button></div></td></tr>)}</tbody></table></div>}
  {current&&<aside className="schedule-detail" aria-label="Schedule details"><h3>{current.prompt}</h3><p>{goal?.success_criteria}</p>{grant?.runbook&&<details><summary>Authorized command steps · {grant.runbook.name}</summary>{grant.runbook.steps.map((step,index)=><pre key={index}>{index+1}. {step.command}{step.confirm?' · confirmation required':''}</pre>)}</details>}<p>{goal?.runs_started||0} / {goal?.max_runs||0} runs used · Grant expires {date(grant?.expires_at)}</p><p>Missed runs: {current.missed==='once'?'Run once when the host returns':'Skip'} · Overlap: {current.overlap==='queue'?'Queue one occurrence':'Skip'}</p>{current.reason&&<p role="alert">{current.reason}</p>}{goal&&<a href={'/?session='+encodeURIComponent(goal.conversation_id)}>Open conversation and approvals</a>}<div className="schedule-actions"><Button variant="secondary" disabled={busy||current.archived} onClick={()=>void act(()=>request(`/api/workspace/schedules/${current.id}/archive`,json('POST',{revision:current.revision})),'Schedule archived; active runs continue')}>Archive schedule</Button>{grant&&!grant.revoked&&<Button variant="secondary" disabled={busy} onClick={()=>void act(()=>request(`/api/workspace/delegations/${grant.id}`,{method:'DELETE'}),'Authority revoked and active runs cancelled')}>Revoke and stop runs</Button>}</div><h4>Run history</h4>{data.schedule_run.filter(r=>r.schedule_id===current.id).map(run=><article key={run.id} className="schedule-run"><strong>{(run.status==='running'?run.task_status||run.status:run.status).replaceAll('_',' ')}</strong> · {date(run.due)}{run.manual?' · Run now':''}{run.reason&&<p>{run.reason}</p>}{run.task_id&&<code>{run.task_id}</code>}{run.step_results?.map((step,i)=><pre key={i}>{step.output}</pre>)}{run.status==='running'&&<div className="schedule-actions">{run.runbook_run_id&&run.task_status==='awaiting_confirmation'&&<Button disabled={busy} onClick={()=>void act(()=>request(`/api/workspace/schedule-runs/${run.id}/confirm`,json('POST',{})),'Step confirmed')}>Confirm step</Button>}<Button variant="secondary" disabled={busy} onClick={()=>void act(()=>request(`/api/workspace/schedule-runs/${run.id}/stop`,json('POST',{})),'Run stopped')}>Stop run</Button></div>}</article>)}{!data.schedule_run.some(r=>r.schedule_id===current.id)&&<p>No runs yet.</p>}</aside>}
  {editing&&<form className="manager-form schedule-editor" aria-label={editing==='new'?'Create scheduled task':'Edit scheduled task'} onSubmit={e=>{e.preventDefault();void act(save,'Schedule saved')}}><h3>{editing==='new'?'Create scheduled task':'Edit scheduled task'}</h3>
   {editing==='new'&&<><label>Task type<select value={taskKind} onChange={e=>setTaskKind(e.target.value)}><option value="agent">Agent task</option><option value="command">Shell cron job</option></select></label><label>Conversation<select required value={conversation} onChange={e=>setConversation(e.target.value)}><option value="">Choose a conversation</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>{!sessions.length&&<p>Create a conversation with its project, engine and model first.</p>}<label>Success criteria<Input required value={criteria} onChange={e=>setCriteria(e.target.value)}/></label></>}
   {editing==='new'&&taskKind==='command'&&<><label>Shell command<textarea required value={command} onChange={e=>setCommand(e.target.value)} placeholder="npm test"/></label><p className="manager-help">Runs directly in this conversation’s folder as the host OS user, without a model. The command is saved as an automation. Changing its saved steps requires a new schedule authorization.</p></>}
   <label>Task prompt<textarea required value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Run the project checks and report any failures"/></label>
   <div className="schedule-fields"><label>Frequency<select value={kind} onChange={e=>setKind(e.target.value)}><option value="once">Once</option><option value="daily">Daily</option><option value="interval">Every interval</option><option value="cron">Cron expression</option></select></label>
   {kind==='once'?<label>Date and time (this device)<Input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label>:kind==='interval'?<label>Interval in minutes<Input type="number" min="1" max="525600" required value={minutes} onChange={e=>setMinutes(e.target.value)}/></label>:<>{kind==='daily'?<label>Time<Input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label>:<label>Cron expression<Input required value={cron} onChange={e=>setCron(e.target.value)} placeholder="0 9 * * 1-5"/></label>}<label>Timezone<Input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label></>}</div>
   {kind==='cron'&&<p className="manager-help">Minute · hour · day of month · month · weekday (0 or 7 = Sunday). Supports *, lists, ranges and steps. Example: 0 9 * * 1-5 runs at 09:00 on weekdays. Missing DST times are skipped; repeated times run once.</p>}
   <div className="schedule-fields"><label>When the host misses a run<select value={missed} onChange={e=>setMissed(e.target.value)}><option value="skip">Skip missed runs</option><option value="once">Catch up once</option></select></label><label>When a previous task is active<select value={overlap} onChange={e=>setOverlap(e.target.value)}><option value="skip">Skip this occurrence</option><option value="queue">Queue one occurrence</option></select></label></div>
   {editing==='new'&&<><div className="schedule-fields"><label>Maximum runs<Input type="number" min="1" max="10000" required value={runs} onChange={e=>setRuns(e.target.value)}/></label><label>Grant expires after days<Input type="number" min="1" max="90" required value={days} onChange={e=>setDays(e.target.value)}/></label><label>Seconds per run<Input type="number" min="1" max="604800" required value={seconds} onChange={e=>setSeconds(e.target.value)}/></label></div><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Allow unattended runs within these limits. Existing tool approvals still apply.</label></>}
   <Button type="button" variant="secondary" disabled={busy} onClick={()=>void act(async()=>{const value=await request<{next_runs:number[]}>('/api/workspace/schedules/preview',json('POST',spec()));setPreview(value.next_runs)},'Preview ready')}>Preview next runs</Button>{preview.length>0&&<div><p>Upcoming runs (shown in this device’s timezone)</p><ol>{preview.map(n=><li key={n}>{date(n)}</li>)}</ol></div>}
   <div className="schedule-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit" disabled={busy||(editing==='new'&&(!consent||!conversation))}>{busy?'Saving…':editing==='new'?'Authorize and create schedule':'Save schedule'}</Button></div>
  </form>}
 </section>
}
