import {useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {json,request,type Task} from '../lib/api';
type Run=Task&{tree_budget?:{root_task_id:string;max_steps:number;used_steps:number;max_execution_seconds:number;used_execution_seconds:number;active_workers:number;version:number};cwd?:string;parent_id?:string;execution_location?:string;worktree?:{branch?:string;worktree_path?:string};children?:Run[]};
const active=(task:Task)=>['running','planning','awaiting_approval','paused','recovering','cancelling'].includes(task.status);
export default function TaskSupervisor({taskId,onClose,onError}:{taskId:string;onClose:()=>void;onError:(error:unknown)=>void}){
 const [root,setRoot]=useState<Run|null>(null),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{setRoot(await request<Run>('/api/workspace/tasks/'+taskId))}catch(error){onError(error)}}
 useEffect(()=>{void refresh();const timer=setInterval(refresh,1500);return ()=>clearInterval(timer)},[taskId]);
 const flatten=(task:Run):Run[]=>[task,...(task.children||[]).flatMap(flatten)];const tasks=root?flatten(root):[],chosen=tasks.find(task=>task.id===selected)||root;
 async function control(task:Run,action:'cancel'|'steer'|'retry'){setBusy(true);try{await request('/api/workspace/tasks/'+task.id+'/'+action,json('POST',action==='steer'?{message}:action==='retry'?{request_id:crypto.randomUUID()}:{}));setMessage('');await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
 function tree(task:Run,depth=0):React.ReactNode{return <div key={task.id}><button className={'supervision-row '+(chosen?.id===task.id?'selected':'')} style={{paddingLeft:12+depth*18}} onClick={()=>setSelected(task.id)}><span className={'status-dot '+task.status}/><strong>{task.prompt.slice(0,100)}</strong><small>{task.status.replaceAll('_',' ')}</small></button>{(task.children||[]).map(child=>tree(child,depth+1))}</div>}
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="wide-dialog"><DialogTitle>Task supervision</DialogTitle><DialogDescription>Inspect each task's execution location and budget. Steering targets the selected task; cancelling a parent also cancels its descendants.</DialogDescription>{root?<div className="supervision-grid"><div className="supervision-tree">{tree(root)}</div><div className="supervision-detail">{chosen&&<><h3>{chosen.id}</h3><p>{chosen.status.replaceAll('_',' ')} · {chosen.engine||'internal'}</p><label>Execution location<code>{chosen.execution_location||chosen.worktree?.worktree_path||chosen.cwd||'No directory'}</code></label>{chosen.worktree?.branch&&<label>Branch<code>{chosen.worktree.branch}</code></label>}{chosen.tree_budget&&<section aria-label="Shared task tree budget"><h4>Shared parent and child allowance</h4><p>{chosen.tree_budget.used_steps} / {chosen.tree_budget.max_steps} reserved tool calls · {chosen.tree_budget.used_execution_seconds.toFixed(1)} / {chosen.tree_budget.max_execution_seconds} summed active execution seconds</p><p>One shared pool for root {chosen.tree_budget.root_task_id}. Parallel workers consume this same allowance; human approval waits pause execution time. Tokens and billed costs are not measured.</p></section>}<label>Individual task ceiling<pre>{JSON.stringify(chosen.limits,null,2)}</pre></label>{chosen.error&&<p className="inline-error">{chosen.error}</p>}{chosen.result&&<details><summary>Task outcome</summary><pre>{chosen.result}</pre></details>}{!active(chosen)&&!chosen.parent_id&&<><p className="retry-disclosure">Retry starts a new turn with the original prompt and images, using this conversation's current model, tools and execution location.</p><Button disabled={busy} onClick={()=>control(chosen,'retry')}>Retry as a new turn</Button></>}{active(chosen)&&<><Input aria-label="Steer selected task" value={message} onChange={event=>setMessage(event.target.value)} placeholder="Instruction for this task"/><Button disabled={!message.trim()||busy} onClick={()=>control(chosen,'steer')}>Steer task</Button><Button variant="outline" disabled={busy} onClick={()=>control(chosen,'cancel')}>Cancel task and descendants</Button></>}</>}</div></div>:<p>Loading task tree…</p>}</DialogContent></Dialog>
}
