import {rememberTerminal,recalledTerminal} from '../lib/window-state';
import {readTerminalSelection,saveTerminalSelection} from '../lib/terminal-selection';
import {useEffect,useRef,useState} from 'react';
import {Terminal} from '@xterm/xterm';
import {FitAddon} from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import {gql,request,type Project} from '../lib/api';
import {Button} from '../components/ui/button';
import {terminalFrame} from '../lib/terminal-frames';
import {terminalKeyHandler} from '../lib/terminal-keyboard';
export function terminalTheme(){const css=getComputedStyle(document.documentElement);return {background:css.getPropertyValue('--background').trim()||'#151716',foreground:css.getPropertyValue('--foreground').trim()||'#f0f3ed',cursor:css.getPropertyValue('--accent').trim()||'#92d4a3'}}
export default function TerminalPanel({project,onError,workspaceSession,executionRoot,ownerId}:{ownerId?:string;workspaceSession?:string;executionRoot?:string;project:Project|null;onError:(error:unknown)=>void}){
 const host=useRef<HTMLDivElement>(null),terminal=useRef<Terminal|null>(null),socket=useRef<WebSocket|null>(null),fit=useRef<FitAddon|null>(null),toolbarSession=useRef<HTMLSelectElement>(null);
 const [sessions,setSessions]=useState<{id:string;title:string;cwd:string;exited:boolean}[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[state,setState]=useState('Disconnected'),[connectedId,setConnectedId]=useState(''),[transportEpoch,setTransportEpoch]=useState(0);
 const paused=useRef(false),inventoryTarget=useRef(''),selectionTarget=useRef('');const targetKey=JSON.stringify([project?.id,project?.path,executionRoot,workspaceSession,ownerId]);const targetGeneration=useRef({key:targetKey,generation:0});if(targetGeneration.current.key!==targetKey)targetGeneration.current={key:targetKey,generation:targetGeneration.current.generation+1};
 useEffect(()=>{const lock=()=>{paused.current=true;socket.current?.close();setState('Locked');setConnectedId('');if(terminal.current)terminal.current.options.disableStdin=true;setTransportEpoch(value=>value+1)};const unlock=()=>{paused.current=false;setTransportEpoch(value=>value+1)};window.addEventListener('termx-locked',lock);window.addEventListener('termx-session-unlocked',unlock);return()=>{window.removeEventListener('termx-locked',lock);window.removeEventListener('termx-session-unlocked',unlock)}},[]);
 useEffect(()=>{if(!host.current)return;const instance=new Terminal({fontFamily:'"Geist Mono Variable", "Geist Mono", ui-monospace, SFMono-Regular, monospace',fontSize:12,theme:terminalTheme(),scrollback:10000,convertEol:false,allowProposedApi:false});const addon=new FitAddon();instance.loadAddon(addon);instance.open(host.current);instance.attachCustomKeyEventHandler(terminalKeyHandler(()=>toolbarSession.current?.focus()));const input=host.current.querySelector('textarea');input?.setAttribute('aria-description','Tab completes shell commands. Shift+Tab returns to the terminal toolbar.');terminal.current=instance;fit.current=addon;const size=()=>{try{addon.fit();if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'resize',cols:instance.cols,rows:instance.rows}))}catch{}};const appearance=new MutationObserver(()=>{instance.options.theme=terminalTheme()});appearance.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});document.fonts?.ready.then(()=>{if(terminal.current===instance)size()});const observer=new ResizeObserver(size);observer.observe(host.current);instance.onData(data=>{if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'input',data}))});return ()=>{appearance.disconnect();observer.disconnect();socket.current?.close();instance.dispose();terminal.current=null}},[]);
 useEffect(()=>{if(paused.current)return;const target=JSON.stringify([project?.id,project?.path,executionRoot,workspaceSession,ownerId]);if(inventoryTarget.current!==target){inventoryTarget.current=target;setCreating(false);setSelected('');setConnectedId('');setState('Disconnected');if(terminal.current)terminal.current.options.disableStdin=true}let cancelled=false;gql<{sessions:{id:string;title:string;cwd:string;exited:boolean}[]}>('query{sessions{id title cwd exited}}').then(data=>{if(!cancelled&&!paused.current){const allowed=data.sessions.filter(s=>!s.exited&&(!project||s.cwd===(executionRoot||project.path)));setSessions(allowed);const remembered=workspaceSession?(recalledTerminal(workspaceSession)||(ownerId?readTerminalSelection(ownerId,workspaceSession):'')):'';selectionTarget.current=workspaceSession||'';setSelected(allowed.some(row=>row.id===remembered)?remembered:'')}}).catch(error=>{if(!cancelled&&!paused.current)onError(error)});return ()=>{cancelled=true}},[project?.id,project?.path,executionRoot,workspaceSession,ownerId,transportEpoch]);
 useEffect(()=>{if(!selected||paused.current)return;let stopped=false;let activeSocket:WebSocket|null=null;let reconnect:ReturnType<typeof setTimeout>;terminal.current?.reset();const connect=()=>{if(stopped||paused.current)return;const url=new URL('/api/sessions/'+selected+'/pty',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(url);activeSocket=ws;ws.binaryType='arraybuffer';socket.current=ws;const fresh=()=>!stopped&&!paused.current&&socket.current===ws;setConnectedId('');setState('Connecting');if(terminal.current)terminal.current.options.disableStdin=true;ws.onopen=()=>{if(!fresh())return;setState('Connected');setConnectedId(selected);if(terminal.current)terminal.current.options.disableStdin=false;fit.current?.fit();ws.send(JSON.stringify({type:'resize',cols:terminal.current?.cols||80,rows:terminal.current?.rows||24}))};ws.onmessage=event=>{if(!fresh())return;const frame=terminalFrame(event.data);if(frame.output!==undefined)terminal.current?.write(frame.output);if(frame.exit!==undefined)setState('Exited · '+frame.exit);if(frame.error)onError(new Error(frame.error))};ws.onclose=event=>{if(!fresh())return;setState('Disconnected');setConnectedId('');if(terminal.current)terminal.current.options.disableStdin=true;if(event.code===4401){request('/auth/me').then(()=>{if(fresh())connect()}).catch(error=>{if(fresh())onError(error)})}else if(event.code!==4403&&event.code!==4404){reconnect=setTimeout(connect,2000)}else onError(new Error(event.code===4404?'This terminal has exited. Open a new terminal.':'Terminal authority was revoked.'))};ws.onerror=()=>{if(fresh())setState('Connection interrupted')}};connect();return ()=>{stopped=true;clearTimeout(reconnect);activeSocket?.close();if(socket.current===activeSocket)socket.current=null}},[selected,transportEpoch]);
 useEffect(()=>{let current=true;const handoff=(event:Event)=>{const detail=(event as CustomEvent<{sessionId:string;id:string}>).detail;if(!current||paused.current||detail.sessionId!==workspaceSession)return;gql<{sessions:{id:string;title:string;cwd:string;exited:boolean}[]}>('query{sessions{id title cwd exited}}').then(data=>{if(!current||paused.current)return;const allowed=data.sessions.filter(row=>!row.exited&&row.cwd===(executionRoot||project?.path));if(!allowed.some(row=>row.id===detail.id))throw new Error('Transferred terminal is no longer available in this checkout');selectionTarget.current=workspaceSession||'';setSessions(allowed);setSelected(detail.id)}).catch(error=>{if(current&&!paused.current)onError(error)})};window.addEventListener('termx-terminal-handoff',handoff);return()=>{current=false;window.removeEventListener('termx-terminal-handoff',handoff)}},[workspaceSession,executionRoot,project?.id]);
 useEffect(()=>{if(workspaceSession&&selected&&selectionTarget.current===workspaceSession){rememberTerminal(workspaceSession,selected);if(ownerId)saveTerminalSelection(ownerId,workspaceSession,selected)}},[workspaceSession,selected,ownerId]);
 async function create(){if(!project||paused.current)return;const generation=targetGeneration.current.generation;setCreating(true);try{const data=workspaceSession?{create_session:await request<{id:string;title:string;cwd:string;exited:boolean}>('/api/workspace/sessions/'+workspaceSession+'/terminal',{method:'POST'})}:await gql<{create_session:{id:string;title:string;cwd:string;exited:boolean}}>('mutation($input:CreateSessionInput!){create_session(input:$input){id title cwd exited}}',{input:{cwd:project.path,sandbox_profile:'workspace',title:project.name}});if(targetGeneration.current.generation!==generation||paused.current)return;selectionTarget.current=workspaceSession||'';setSessions(rows=>[...rows,data.create_session]);setSelected(data.create_session.id)}catch(error){if(targetGeneration.current.generation===generation&&!paused.current)onError(error)}finally{if(targetGeneration.current.generation===generation)setCreating(false)}}
 return <section className="terminal-region" aria-label="Terminal" data-connected-session={connectedId}><div className="terminal-toolbar"><span>Terminal</span><select ref={toolbarSession} aria-label="Terminal session" value={selected} onChange={event=>{selectionTarget.current=workspaceSession||'';setSelected(event.target.value)}}><option value="">Select a terminal</option>{sessions.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select><small>{state}</small><small className="terminal-keyboard-hint">Shift+Tab to toolbar</small><span className="flex-spacer"/><Button variant="ghost" size="sm" disabled={!project||creating} onClick={create}>New terminal</Button>{selected&&<Button variant="ghost" size="sm" onClick={()=>socket.current?.send(JSON.stringify({type:'signal',name:'int'}))}>Interrupt</Button>}</div><div className="terminal-host" ref={host}/></section>
}
