import {rememberTerminal,recalledTerminal} from '../lib/window-state';
import {useEffect,useRef,useState} from 'react';
import {Terminal} from '@xterm/xterm';
import {FitAddon} from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import {gql,request,type Project} from '../lib/api';
import {Button} from '../components/ui/button';
import {terminalFrame} from '../lib/terminal-frames';
export default function TerminalPanel({project,onError,workspaceSession,executionRoot}:{workspaceSession?:string;executionRoot?:string;project:Project|null;onError:(error:unknown)=>void}){
 const host=useRef<HTMLDivElement>(null),terminal=useRef<Terminal|null>(null),socket=useRef<WebSocket|null>(null),fit=useRef<FitAddon|null>(null);
 const [sessions,setSessions]=useState<{id:string;title:string;cwd:string;exited:boolean}[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[state,setState]=useState('Disconnected'),[connectedId,setConnectedId]=useState('');
 useEffect(()=>{if(!host.current)return;const instance=new Terminal({fontFamily:'ui-monospace, SFMono-Regular, monospace',fontSize:12,theme:{background:'#151716',foreground:'#f0f3ed'},scrollback:10000,convertEol:false,allowProposedApi:false});const addon=new FitAddon();instance.loadAddon(addon);instance.open(host.current);terminal.current=instance;fit.current=addon;const size=()=>{try{addon.fit();if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'resize',cols:instance.cols,rows:instance.rows}))}catch{}};const observer=new ResizeObserver(size);observer.observe(host.current);instance.onData(data=>{if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'input',data}))});return ()=>{observer.disconnect();socket.current?.close();instance.dispose();terminal.current=null}},[]);
 useEffect(()=>{setSelected('');let cancelled=false;gql<{sessions:{id:string;title:string;cwd:string;exited:boolean}[]}>('query{sessions{id title cwd exited}}').then(data=>{if(!cancelled){const allowed=data.sessions.filter(s=>!s.exited&&(!project||s.cwd===(executionRoot||project.path)));setSessions(allowed);const remembered=workspaceSession?recalledTerminal(workspaceSession):'';if(allowed.some(row=>row.id===remembered))setSelected(remembered)}}).catch(onError);return ()=>{cancelled=true}},[project?.id,executionRoot]);
 useEffect(()=>{if(!selected)return;let stopped=false;let reconnect:ReturnType<typeof setTimeout>;terminal.current?.reset();const connect=()=>{if(stopped)return;const url=new URL('/api/sessions/'+selected+'/pty',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(url);ws.binaryType='arraybuffer';socket.current=ws;setState('Connecting');if(terminal.current)terminal.current.options.disableStdin=true;ws.onopen=()=>{setState('Connected');setConnectedId(selected);if(terminal.current)terminal.current.options.disableStdin=false;fit.current?.fit();ws.send(JSON.stringify({type:'resize',cols:terminal.current?.cols||80,rows:terminal.current?.rows||24}))};ws.onmessage=event=>{const frame=terminalFrame(event.data);if(frame.output!==undefined)terminal.current?.write(frame.output);if(frame.exit!==undefined)setState('Exited · '+frame.exit);if(frame.error)onError(new Error(frame.error))};ws.onclose=event=>{setState('Disconnected');setConnectedId('');if(terminal.current)terminal.current.options.disableStdin=true;if(stopped)return;if(event.code===4401){request('/auth/me').then(()=>{if(!stopped)connect()}).catch(onError)}else if(event.code!==4403&&event.code!==4404){reconnect=setTimeout(connect,2000)}else onError(new Error(event.code===4404?'This terminal has exited. Open a new terminal.':'Terminal authority was revoked.'))};ws.onerror=()=>setState('Connection interrupted')};connect();return ()=>{stopped=true;setConnectedId('');clearTimeout(reconnect);socket.current?.close()}},[selected]);
 useEffect(()=>{const handoff=(event:Event)=>{const detail=(event as CustomEvent<{sessionId:string;id:string}>).detail;if(detail.sessionId!==workspaceSession)return;gql<{sessions:{id:string;title:string;cwd:string;exited:boolean}[]}>('query{sessions{id title cwd exited}}').then(data=>{const allowed=data.sessions.filter(row=>!row.exited&&row.cwd===(executionRoot||project?.path));if(!allowed.some(row=>row.id===detail.id))throw new Error('Transferred terminal is no longer available in this checkout');setSessions(allowed);setSelected(detail.id)}).catch(onError)};window.addEventListener('termx-terminal-handoff',handoff);return()=>window.removeEventListener('termx-terminal-handoff',handoff)},[workspaceSession,executionRoot,project?.id]);
 useEffect(()=>{if(workspaceSession&&selected)rememberTerminal(workspaceSession,selected)},[workspaceSession,selected]);
 async function create(){if(!project)return;setCreating(true);try{const data=workspaceSession?{create_session:await request<{id:string;title:string;cwd:string;exited:boolean}>('/api/workspace/sessions/'+workspaceSession+'/terminal',{method:'POST'})}:await gql<{create_session:{id:string;title:string;cwd:string;exited:boolean}}>('mutation($input:CreateSessionInput!){create_session(input:$input){id title cwd exited}}',{input:{cwd:project.path,sandbox_profile:'workspace',title:project.name}});setSessions(rows=>[...rows,data.create_session]);setSelected(data.create_session.id)}catch(error){onError(error)}finally{setCreating(false)}}
 return <section className="terminal-region" aria-label="Terminal" data-connected-session={connectedId}><div className="terminal-toolbar"><span>Terminal</span><select aria-label="Terminal session" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a terminal</option>{sessions.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select><small>{state}</small><span className="flex-spacer"/><Button variant="ghost" size="sm" disabled={!project||creating} onClick={create}>New terminal</Button>{selected&&<Button variant="ghost" size="sm" onClick={()=>socket.current?.send(JSON.stringify({type:'signal',name:'int'}))}>Interrupt</Button>}</div><div className="terminal-host" ref={host}/></section>
}
