import {useEffect,useRef,useState} from 'react';
import {Circle,Lock,Monitor,Shield} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {request,json} from '../lib/api';

interface WindowTarget{id:string;pid:number;app:string;title:string;width:number;height:number}
interface Capture{id:string;private:boolean;recording:boolean;window:WindowTarget;expires_at:number;steps:unknown[]}
interface Draft{id:string;name:string;content:string;parameters:string[];test?:{steps_executed:number};published_version?:string}
const base='/api/desktop/recording';
export default function WindowRecordingPanel({onError}:{onError:(error:unknown)=>void}){
 const [targets,setTargets]=useState<WindowTarget[]>([]),[selected,setSelected]=useState(''),[capture,setCapture]=useState<Capture|null>(null),[image,setImage]=useState(''),[reason,setReason]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[name,setName]=useState('recorded-workflow'),[content,setContent]=useState(''),[text,setText]=useState(''),[parameter,setParameter]=useState('value'),[testTarget,setTestTarget]=useState(''),[safe,setSafe]=useState(false),[parameters,setParameters]=useState<Record<string,string>>({}),[version,setVersion]=useState('1.0.0'),[busy,setBusy]=useState(false),[redactions,setRedactions]=useState('[]');
 const consents=useRef<string[]>([]);
 useEffect(()=>{const stopped=(event:Event)=>{const ids=(event as CustomEvent<{stopped?:string[]}>).detail?.stopped||[];if(capture&&ids.includes(capture.id)){setCapture(null);setImage('')}consents.current=consents.current.filter(id=>!ids.includes(id))};window.addEventListener('termx-capture-changed',stopped);return()=>window.removeEventListener('termx-capture-changed',stopped)},[capture?.id]);
 const startCapture=async(window_id:string)=>{const row=await request<Capture>(base+'/captures',json('POST',{window_id}));consents.current.push(row.id);return row};
 const run=async(work:()=>Promise<void>)=>{setBusy(true);try{await work()}catch(error){onError(error)}finally{setBusy(false)}};
 const refresh=async()=>{const data=await request<{windows:WindowTarget[];reason:string}>(base+'/windows');setTargets(data.windows);setReason(data.reason)};
 useEffect(()=>{void refresh().catch(onError)},[]);
 useEffect(()=>{if(!capture)return;let stopped=false;let pending=false;const update=async()=>{if(pending)return;pending=true;try{const data=await request<{image:string}>(base+'/captures/'+capture.id+'/preview');if(!stopped)setImage(data.image)}catch(error){if(!stopped){setImage('');onError(error)}}finally{pending=false}};void update();const timer=setInterval(()=>{void update()},2000);return()=>{stopped=true;clearInterval(timer)}},[capture?.id,capture?.private,redactions]);
 useEffect(()=>()=>{for(const id of consents.current)void request(base+'/captures/'+id,json('DELETE')).catch(()=>{});consents.current=[]},[]);
 const configure=async(data:unknown)=>{if(capture)setCapture(await request<Capture>(base+'/captures/'+capture.id,json('PATCH',data)))};
 const input=async(event:unknown,param?:string)=>{if(!capture)return;await request(base+'/captures/'+capture.id+'/input',json('POST',{event,parameter:param}));};
 return <section className="window-recording-panel" aria-label="Window recording to skill">
  <header><Monitor size={16}/><strong>Window capture & skills</strong><span className="flex-spacer"/>{capture&&<small>{capture.private?<><Lock size={12}/> Private · models paused</>:capture.recording?<><Circle size={12}/> Recording</>:<><Shield size={12}/> Human preview</>}</small>}</header>
  <p>Select one application window. Capture consent expires after 10 minutes. Plain text is excluded from recordings; named parameters replace typed values.</p>
  <div className="window-recording-actions"><select aria-label="Application window" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose an application window</option>{targets.map(target=><option key={target.id} value={target.id}>{target.app} · {target.title||'Untitled window'} · {target.width} × {target.height}</option>)}</select><Button variant="outline" disabled={busy} onClick={()=>void run(refresh)}>Refresh windows</Button><Button disabled={busy||!selected||!!capture} onClick={()=>void run(async()=>setCapture(await startCapture(selected)))}>Start window capture</Button></div>
  {reason&&<p role="status">{reason}</p>}
  {capture&&<><div className="window-recording-actions"><Button variant="outline" disabled={busy||capture.private} onClick={()=>void run(()=>configure({recording:!capture.recording}))}>{capture.recording?'Stop recording':'Record my actions'}</Button><Button variant="outline" disabled={busy} onClick={()=>void run(()=>configure({private:!capture.private}))}>{capture.private?'End private mode':'Private mode'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void run(async()=>{await request(base+'/captures/'+capture.id,json('DELETE'));setCapture(null);setImage('')})}>Stop capture</Button></div>
   {image&&<img className="window-recording-preview" src={image} alt={capture.private?'Private application window, visible only to you':'Selected application window; click to send a recorded pointer action'} onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();void run(()=>input({type:'pointer',action:'click',x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height,button:1}))}}/>}
   <div className="window-recording-actions"><Input aria-label="Window text" value={text} onChange={event=>setText(event.target.value)} placeholder="Text to type into the selected frontmost window"/><Input aria-label="Recorded parameter name" value={parameter} onChange={event=>setParameter(event.target.value)} placeholder="Parameter name"/><Button disabled={busy||!text} onClick={()=>void run(async()=>{await input({type:'text',data:text},capture.recording&&!capture.private?parameter:undefined);setText('')})}>Type text</Button></div>
   <label>Redaction regions (normalized x, y, width, height)<textarea aria-label="Window redaction regions" value={redactions} onChange={event=>setRedactions(event.target.value)}/></label><Button variant="outline" disabled={busy} onClick={()=>void run(()=>configure({redactions:JSON.parse(redactions)}))}>Apply redactions</Button>
   <div className="window-recording-actions"><Input aria-label="Recorded skill name" value={name} onChange={event=>setName(event.target.value)}/><Button disabled={busy||capture.private} onClick={()=>void run(async()=>{await configure({recording:false});const row=await request<Draft>(base+'/captures/'+capture.id+'/draft',json('POST',{name}));setDraft(row);setContent(row.content)})}>Create editable skill draft</Button></div>
  </>}
  {draft&&<><label>Edit skill instructions<textarea aria-label="Recorded skill instructions" value={content} onChange={event=>{setContent(event.target.value);setSafe(false)}}/></label><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>setDraft(await request<Draft>(base+'/drafts/'+draft.id,json('PATCH',{content}))))}>Save draft</Button><label>Separate safe test window<select aria-label="Safe test window" value={testTarget} onChange={event=>{setTestTarget(event.target.value);setSafe(false)}}><option value="">Choose a separate window for replay</option>{targets.filter(target=>target.id!==capture?.window.id).map(target=><option key={target.id} value={target.id}>{target.app} · {target.title||target.id}</option>)}</select></label>{draft.parameters.map(key=><Input key={key} aria-label={'Test parameter '+key} placeholder={'Test value for '+key} type="password" value={parameters[key]||''} onChange={event=>setParameters({...parameters,[key]:event.target.value})}/>)}<label><input type="checkbox" checked={safe} onChange={event=>setSafe(event.target.checked)}/>I own this safe test window and approve replaying the displayed steps.</label><div className="window-recording-actions"><Button disabled={busy||!safe||!testTarget||content!==draft.content} onClick={()=>void run(async()=>{const target=await startCapture(testTarget);const row=await request<Draft>(base+'/drafts/'+draft.id+'/test',json('POST',{target_capture_id:target.id,parameters,safe_target:true}));setDraft(row);setParameters({})})}>Run scoped test</Button><Input aria-label="Recorded skill version" value={version} onChange={event=>setVersion(event.target.value)}/><Button disabled={busy||!draft.test||content!==draft.content} onClick={()=>void run(async()=>{await request(base+'/drafts/'+draft.id+'/publish',json('POST',{version}));setDraft({...draft,published_version:version})})}>Approve & activate version</Button></div>{draft.test&&<p role="status">Executed {draft.test.steps_executed} steps against the selected test window. Editing the draft requires a new test.</p>}{draft.published_version&&<p role="status">Activated version {draft.published_version}.</p>}</>}
 </section>
}
