import {useState,type ReactNode} from 'react';
import {GripVertical,ExternalLink} from 'lucide-react';
import {Button} from './ui/button';
import {type DockMap,type DockPanel,type DockRegion,type DockGeometry,defaultGeometry,regions} from '../lib/docking';
export default function DockWorkspace({map,onChange,children,onDetach,rightVisible,rightWidth,onRightWidth,geometry=defaultGeometry,onGeometry}:{map:DockMap;onChange:(map:DockMap)=>void;children:Record<DockPanel,ReactNode>;onDetach:(panel:DockPanel)=>void;rightVisible:boolean;rightWidth:number;onRightWidth?:(width:number)=>void;geometry?:DockGeometry;onGeometry?:(geometry:DockGeometry)=>void}){
 const [drag,setDrag]=useState<DockPanel|null>(null),[active,setActive]=useState<Partial<Record<DockRegion,DockPanel>>>({});
 const grouped=regions.filter(region=>region!=='hidden').map(region=>({region,panels:(Object.keys(map) as DockPanel[]).filter(panel=>map[panel]===region)}));
 const effective={...map};if(!rightVisible)for(const key of Object.keys(effective) as DockPanel[])if(effective[key]==='right')effective[key]='hidden';
 const move=(panel:DockPanel,region:DockRegion)=>{onChange({...map,[panel]:region});setActive(old=>({...old,[region]:panel}));setDrag(null)};
 const has=(region:DockRegion)=>Object.values(effective).includes(region);
 const columns=`${has('left')?geometry.left+'px':'0px'} minmax(0,1fr) ${has('split')?geometry.split+'px':'0px'} ${has('right')?rightWidth+'px':'0px'}`;
 function resize(region:DockRegion,delta:number){if(region==='right')onRightWidth?.(Math.max(240,Math.min(800,rightWidth+delta)));else if(['left','split','bottom'].includes(region)){const key=region as keyof DockGeometry;onGeometry?.({...geometry,[key]:Math.max(key==='bottom'?120:180,Math.min(key==='bottom'?700:800,geometry[key]+delta))})}}
 function dragResize(event:React.PointerEvent,region:DockRegion){event.preventDefault();const start=region==='bottom'?event.clientY:event.clientX,original=region==='right'?rightWidth:geometry[region as keyof DockGeometry];const move=(event:PointerEvent)=>{const delta=(region==='bottom'?event.clientY:event.clientX)-start;const direction=region==='left'?1:-1;const value=Math.max(region==='bottom'?120:region==='right'?240:180,Math.min(region==='bottom'?700:800,original+direction*delta));if(region==='right')onRightWidth?.(value);else onGeometry?.({...geometry,[region]:value})};const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end)}
 return <div className="dock-workspace" style={{gridTemplateColumns:columns,gridTemplateRows:`minmax(0,1fr) ${has('bottom')?geometry.bottom+'px':'0px'}`}}>{(Object.keys(map) as DockPanel[]).map(panel=>{const region=effective[panel];const group=(Object.keys(effective) as DockPanel[]).filter(item=>effective[item]===region);const selected=active[region]&&group.includes(active[region]!)?active[region]:group[0];const areas:Record<DockRegion,string>={left:'left',main:'main',split:'split',right:'right',bottom:'bottom',hidden:'main'};return <section key={panel} data-panel={panel} tabIndex={-1} className={'dock-pane dock-'+panel} style={{gridArea:areas[region],display:region==='hidden'||selected!==panel?'none':'flex'}} aria-label={panel+' panel'} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const value=event.dataTransfer.getData('application/termx-panel') as DockPanel;if(['editor','conversation','browser'].includes(value))move(value,region)}}><div className="dock-pane-header" draggable onDragStart={event=>{setDrag(panel);event.dataTransfer.setData('application/termx-panel',panel)}} onDragEnd={()=>setDrag(null)}><GripVertical size={13} aria-hidden="true"/>{group.map(item=><button key={item} className={item===panel?'active':''} onClick={()=>setActive(old=>({...old,[region]:item}))}>{item==='editor'?'Workbench':item[0].toUpperCase()+item.slice(1)}</button>)}<span className="flex-spacer"/><select aria-label={'Dock '+panel} value={map[panel]} onChange={event=>move(panel,event.target.value as DockRegion)}>{regions.map(region=><option key={region} value={region}>{region==='split'?'Split center':region[0].toUpperCase()+region.slice(1)}</option>)}</select><Button variant="ghost" size="icon" aria-label={'Detach '+panel} onClick={()=>onDetach(panel)}><ExternalLink size={12}/></Button></div><div className="dock-pane-content">{children[panel]}</div>{['left','split','right','bottom'].includes(region)&&<div role="separator" tabIndex={0} aria-label={'Resize '+region+' dock'} aria-valuemin={region==='bottom'?120:region==='right'?240:180} aria-valuemax={region==='bottom'?700:800} aria-valuenow={region==='right'?rightWidth:geometry[region as keyof DockGeometry]} aria-valuetext={(region==='right'?rightWidth:geometry[region as keyof DockGeometry])+' pixels'} aria-orientation={region==='bottom'?'horizontal':'vertical'} className={'dock-resizer resize-'+region} onPointerDown={event=>dragResize(event,region)} onKeyDown={event=>{if(['ArrowLeft','ArrowUp'].includes(event.key)){event.preventDefault();resize(region,-16)}if(['ArrowRight','ArrowDown'].includes(event.key)){event.preventDefault();resize(region,16)}}}/>}</section>})}{drag&&<div className="dock-drop-grid">{grouped.map(({region})=><div key={region} className={'drop-'+region} style={{gridArea:region}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();move(drag,region)}}>Dock {region==='split'?'split center':region}</div>)}</div>}</div>
}
