import {preserveBeforeLock} from '../lib/lock-preservation';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import LockScreen from './LockScreen';
import HostStop from './HostStop';
import {request,unlockWorkspace} from '../lib/api';
vi.mock('../lib/lock-preservation',()=>({preserveBeforeLock:vi.fn(async()=>[])}));
vi.mock('../lib/api',()=>({request:vi.fn(),unlockWorkspace:vi.fn(),beginUnlockOidc:vi.fn(),signOut:vi.fn(),json:(method:string,data:unknown)=>({method,body:JSON.stringify(data)})}));
const state={locked:true,principal:{id:'owner',display_name:'Owner'},session_id:'same-sid',host_id:'machine',methods:[{id:'local-password',label:'Local password',flow:'credentials' as const}]};
afterEach(cleanup);beforeEach(()=>vi.clearAllMocks());
it('keeps the lock dialog nondismissible, clears failed credentials and accepts only an explicit unlock',async()=>{vi.mocked(unlockWorkspace).mockRejectedValueOnce(Error('Wrong password')).mockResolvedValueOnce({principal:state.principal,session_id:'same-sid'});const done=vi.fn(async()=>{});render(<LockScreen state={state} onRetry={vi.fn()} onUnlocked={done}/>);expect(screen.queryByRole('button',{name:'Close'})).toBeNull();fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.getByRole('dialog',{name:'Workspace locked'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Password'),{target:{value:'incorrect'}});fireEvent.click(screen.getByRole('button',{name:'Unlock workspace'}));await screen.findByRole('alert');expect(screen.getByLabelText('Password')).toHaveValue('');expect(done).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Password'),{target:{value:'correct'}});fireEvent.click(screen.getByRole('button',{name:'Unlock workspace'}));await waitFor(()=>expect(done).toHaveBeenCalledWith({principal:state.principal,session_id:'same-sid'}));expect(unlockWorkspace).toHaveBeenLastCalledWith({method:'local-password',username:'Owner',password:'correct',assertion:''})});
it('keeps status recovery reachable when lock metadata is unavailable and forbids unlock during preservation',()=>{const retry=vi.fn();const view=render(<LockScreen state={null} onRetry={retry} onUnlocked={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Restore lock status'}));expect(retry).toHaveBeenCalledOnce();view.rerender(<LockScreen state={state} preparing onRetry={retry} onUnlocked={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Unlock workspace'})).toBeNull();expect(screen.getByRole('button',{name:'Sign out of this device'})).toBeDisabled()});
it('inspects the exact current host and requires acknowledgement before managed stop',async()=>{vi.mocked(request).mockImplementation(async(path)=>path==='/auth/me'?{principal:{id:'owner'},session_id:'same-sid'}:path==='/auth/host/lifecycle'?{host_id:'actual-host',can_stop:true,effects:['Disconnect clients','Pause schedules']}:({accepted:true}));render(<HostStop open onOpenChange={vi.fn()}/>);await screen.findByText('Host: actual-host');expect(screen.getByRole('button',{name:'Stop host now'})).toBeDisabled();expect(request).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Stop host now'}));await screen.findByText(/The host accepted shutdown/);expect(request).toHaveBeenLastCalledWith('/auth/host/stop',{method:'POST',body:JSON.stringify({host_id:'actual-host',acknowledge:true})});expect(screen.getByRole('button',{name:'Shutdown requested'})).toBeDisabled()});
it('refuses a previously inspected host stop after the same account receives another managed SID',async()=>{let sid='original';vi.mocked(request).mockImplementation(async(path)=>path==='/auth/me'?{principal:{id:'owner'},session_id:sid}:{host_id:'actual-host',can_stop:true,effects:['Disconnect clients']});render(<HostStop open onOpenChange={vi.fn()}/>);await screen.findByText('Host: actual-host');sid='fresh';fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Stop host now'}));await screen.findByText(/The signed-in session changed/);expect(vi.mocked(request).mock.calls.some(([path])=>path==='/auth/host/stop')).toBe(false)});

it('preserves exact owner changes before stopping and rejects a SID change during the pending flush',async()=>{let sid='original';vi.mocked(request).mockImplementation(async(path)=>path==='/auth/me'?{principal:{id:'owner'},session_id:sid}:{host_id:'actual-host',can_stop:true,effects:[]});let release!:(value:string[])=>void;vi.mocked(preserveBeforeLock).mockImplementationOnce(()=>new Promise(done=>release=done));render(<HostStop open onOpenChange={vi.fn()}/>);await screen.findByText('Host: actual-host');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Stop host now'}));await waitFor(()=>expect(preserveBeforeLock).toHaveBeenCalledWith('owner'));sid='fresh';release([]);await screen.findByText(/changed while preserving changes/);expect(vi.mocked(request).mock.calls.some(([path])=>path==='/auth/host/stop')).toBe(false)});
it('keeps shutdown inspectable and effects unexecuted when unsaved changes cannot be preserved',async()=>{vi.mocked(request).mockImplementation(async(path)=>path==='/auth/me'?{principal:{id:'owner'},session_id:'original'}:{host_id:'actual-host',can_stop:true,effects:['Disconnect clients']});vi.mocked(preserveBeforeLock).mockResolvedValueOnce(['Device storage unavailable']);render(<HostStop open onOpenChange={vi.fn()}/>);await screen.findByText('Host: actual-host');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Stop host now'}));await screen.findByText(/Unsaved changes need attention/);expect(vi.mocked(request).mock.calls.some(([path])=>path==='/auth/host/stop')).toBe(false);expect(screen.getByRole('button',{name:'Stop host now'})).toBeEnabled()});
