import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {LockKeyhole} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Select} from './ui/select';
import {beginUnlockOidc,unlockWorkspace,signOut,request,type LockState} from '../lib/api';
import './lock-screen.css';
export default function LockScreen({state,preparing=false,notice='',onUnlocked,onRetry,onRetryLock}:{state:LockState|null;preparing?:boolean;notice?:string;onUnlocked:(value:unknown)=>Promise<void>;onRetry:()=>void;onRetryLock?:()=>void}){
 const [method,setMethod]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[assertion,setAssertion]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!state)return;setMethod(state.methods[0]?.id||'');setUsername(state.principal.display_name);setPassword('');setAssertion('')},[state?.session_id]);
 const selected=state?.methods.find(row=>row.id===method);
 async function submit(){if(!selected||preparing)return;setBusy(true);setError('');try{if(selected.flow==='redirect'){const result=await beginUnlockOidc(method);location.assign(result.authorization_url)}else await onUnlocked(await unlockWorkspace({method,username,password,assertion}))}catch(error){setError(error instanceof Error?error.message:String(error))}finally{setPassword('');setAssertion('');setBusy(false)}}
 return <Dialog.Root open><Dialog.Portal><Dialog.Overlay className="lock-overlay"/><Dialog.Content className="lock-screen" onEscapeKeyDown={event=>event.preventDefault()} onPointerDownOutside={event=>event.preventDefault()} onInteractOutside={event=>event.preventDefault()}><LockKeyhole aria-hidden size={28}/><Dialog.Title>{preparing?'Locking workspace…':'Workspace locked'}</Dialog.Title><Dialog.Description>{state?`Unlock ${state.principal.display_name} on this machine. Your conversations and unsaved changes are preserved.`:'Observation is hidden. Restore the lock status to unlock this session.'}</Dialog.Description><p>Browser and computer access stay paused until you explicitly resume them. Enrolled background jobs may continue.</p>{notice&&<p role="status">{notice}</p>}{state&&!state.locked&&!preparing?<><p role="status">The host lock is not confirmed. Observation remains hidden on this device.</p><Button onClick={onRetryLock}>Retry locking workspace</Button><Button variant="outline" onClick={()=>void request('/auth/me',{},false).then(onUnlocked).catch(error=>setError(String(error)))}>Restore authenticated workspace</Button></>:state&&!preparing?<form onSubmit={event=>{event.preventDefault();void submit()}}><label>Unlock method<Select aria-label="Unlock method" value={method} onChange={event=>setMethod(event.target.value)} disabled={busy}>{state.methods.map(row=><option key={row.id} value={row.id}>{row.label||row.id}</option>)}</Select></label>{selected?.flow!=='redirect'&&<><label>Username<Input autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)} disabled={busy}/></label>{method==='local-password'?<label>Password<Input autoFocus type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} disabled={busy} required/></label>:<label>Identity assertion<Input type="password" autoComplete="off" value={assertion} onChange={event=>setAssertion(event.target.value)} disabled={busy} required/></label>}</>}<Button type="submit" disabled={busy||!selected}>{busy?'Unlocking…':selected?.flow==='redirect'?'Unlock with '+selected.label:'Unlock workspace'}</Button></form>:!preparing&&<Button onClick={onRetry}>Restore lock status</Button>}{error&&<p role="alert" className="inline-error">{error}</p>}<Button variant="ghost" disabled={busy||preparing} onClick={()=>void signOut().catch(error=>setError(String(error)))}>Sign out of this device</Button></Dialog.Content></Dialog.Portal></Dialog.Root>
}
